import { getSession, signInWithPassword, signUpWithPassword, signOut, ensureWorkspace } from './src/auth-session.js';
import { getInventorySnapshot, findExpectedReceipts, findInventory } from './src/live-data.js';

const M=document.getElementById('main');
const nav=[...document.querySelectorAll('[data-nav]')];
const state={wr:{},cr:{},session:null};
function active(name){nav.forEach(b=>b.classList.toggle('active',b.dataset.nav===name))}
function shell(eye,title,body){M.innerHTML=`<div class="eyebrow">${eye}</div><h1 class="title">${title}</h1>${body}`}
function v(id){return document.getElementById(id)?.value.trim()||''}
function esc(x=''){return String(x).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

function authScreen(message=''){
  shell('NODARA','Sign in.',`<p class="muted">Use your warehouse account. Your session stays signed in on this device.</p><div class="card" style="max-width:520px"><div class="field"><label>Email</label><input id="auth-email" type="email" autocomplete="email"></div><div class="field"><label>Password</label><input id="auth-password" type="password" autocomplete="current-password"></div>${message?`<div class="notice">${esc(message)}</div>`:''}<button class="primary" style="width:100%;margin-top:18px" onclick="login()">Sign in</button><button class="secondary" style="width:100%;margin-top:10px" onclick="signup()">Create account</button></div>`)
}
async function login(){try{const s=await signInWithPassword(v('auth-email'),v('auth-password'));state.session=s;await ensureWorkspace();home()}catch(e){authScreen(e.message)}}
async function signup(){try{const data=await signUpWithPassword(v('auth-email'),v('auth-password'));if(data.session){state.session=data.session;await ensureWorkspace();home()}else authScreen('Account created. If email confirmation is enabled, confirm your email once, then sign in with your password.')}catch(e){authScreen(e.message)}}
async function logout(){await signOut();state.session=null;authScreen()}

function home(){active('home');shell('Command','What needs to happen?',`<div class="top"><div class="muted">Signed in as ${esc(state.session?.user?.email||'')}</div><button class="subtle" onclick="logout()">Sign out</button></div><div class="card"><button class="choice" onclick="newWR()"><b>Receive cargo</b><small>Create or match a warehouse receipt</small></button><button class="choice" onclick="newCR()"><b>Release cargo</b><small>Create a cargo release from live inventory</small></button><button class="choice" onclick="inventory()"><b>Find inventory</b><small>Search SKU, part, UIN, lot, serial, WR, PO or customer</small></button></div>`)}
function newWR(){active('receive');state.wr={};shell('Warehouse · Receive','Identify the cargo.',`<p class="muted">Search actual expected receipts first. If nothing exists, create a new receipt.</p><div class="card"><div class="search"><input id="wr-search" placeholder="PO, BOL, PRO, tracking, reference…"><button class="primary" onclick="searchWR()">Find</button></div><button class="secondary" style="width:100%;margin-top:10px" onclick="wrDetails()">Create new receipt</button></div>`)}
async function searchWR(){const q=v('wr-search');if(!q)return;try{const rows=await findExpectedReceipts(q);if(!rows.length){shell('Warehouse · Receive','Nothing expected found.',`<div class="card"><div class="empty">No expected receipt matched ${esc(q)}.</div><button class="primary" style="width:100%" onclick="wrDetails('${esc(q)}')">Create receipt from this reference</button></div>`);return}shell('Warehouse · Receive','Expected receipt found.',`<div class="card">${rows.map(r=>`<button class="choice" onclick="wrDetails('${esc(q)}')"><b>${esc(r.description||r.id)}</b><small>${esc(r.status||'expected')}</small></button>`).join('')}</div>`)}catch(e){shell('Warehouse · Receive','Search failed.',`<div class="notice">${esc(e.message)}</div>` )}}
function wrDetails(ref=''){state.wr.reference=ref;shell('Warehouse · Receive','Cargo information.',`<div class="card"><div class="row"><div class="field"><label>Customer</label><input id="wr-customer" placeholder="Customer"></div><div class="field"><label>Shipper</label><input id="wr-shipper" placeholder="Shipper"></div><div class="field"><label>Consignee</label><input id="wr-consignee" placeholder="Consignee"></div><div class="field"><label>Reference</label><input id="wr-ref" value="${esc(ref)}" placeholder="PO / BOL / PRO / tracking"></div></div><div class="field"><label>Description / commodity</label><textarea id="wr-desc" placeholder="What is the cargo?"></textarea></div><div class="actions"><button class="secondary" onclick="newWR()">Back</button><button class="primary" onclick="wrCargo()">Continue</button></div></div>`)}
function wrCargo(){state.wr={customer:v('wr-customer'),shipper:v('wr-shipper'),consignee:v('wr-consignee'),reference:v('wr-ref'),description:v('wr-desc')};shell('Warehouse · Receive','What physically arrived?',`<div class="card"><div class="row"><div class="field"><label>Pallets</label><input id="wr-pallets" type="number" min="0"></div><div class="field"><label>Boxes / cartons</label><input id="wr-boxes" type="number" min="0"></div><div class="field"><label>Total units</label><input id="wr-units" type="number" min="0"></div><div class="field"><label>Part / SKU</label><input id="wr-sku"></div></div><div class="actions"><button class="secondary" onclick="wrDetails(state.wr.reference||'')">Back</button><button class="primary" onclick="wrReview()">Review</button></div></div>`)}
function wrReview(){Object.assign(state.wr,{pallets:v('wr-pallets'),boxes:v('wr-boxes'),units:v('wr-units'),sku:v('wr-sku')});shell('Warehouse · Receive','Review receipt.',`<div class="card">${summary(state.wr)}<div class="notice">Live WR creation will use the atomic receiving RPC in the next wiring pass. This screen contains only your entered/live data.</div></div>`)}
function newCR(){active('release');state.cr={};shell('Warehouse · Cargo Release','What should leave?',`<p class="muted">Search actual available inventory.</p><div class="card"><div class="search"><input id="cr-search" placeholder="SKU, part, UIN, lot, serial…"><button class="primary" onclick="searchCR()">Find</button></div></div>`)}
async function searchCR(){const q=v('cr-search');if(!q)return;try{const rows=await findInventory(q);if(!rows.length){shell('Warehouse · Cargo Release','No inventory found.',`<div class="card"><div class="empty">Nothing available matched ${esc(q)}.</div></div>`);return}shell('Warehouse · Cargo Release','Inventory found.',`<div class="card">${rows.map(r=>`<button class="choice" onclick="crManual('${esc(r.item_key||q)}')"><b>${esc(r.item_key||r.part_number||r.sku||'Item')}</b><small>${esc(r.total_units??0)} units · ${esc(r.carton_count??0)} cartons · ${esc(r.pallet_count??0)} pallets</small></button>`).join('')}</div>`)}catch(e){shell('Warehouse · Cargo Release','Search failed.',`<div class="notice">${esc(e.message)}</div>` )}}
function crManual(q=''){shell('Warehouse · Cargo Release','Release request.',`<div class="card"><div class="row"><div class="field"><label>Item / UIN / serial / lot</label><input id="cr-item" value="${esc(q)}"></div><div class="field"><label>Quantity</label><input id="cr-qty" type="number" min="1"></div></div><div class="field"><label>Release to / carrier</label><input id="cr-carrier"></div><div class="actions"><button class="secondary" onclick="newCR()">Back</button><button class="primary" onclick="crReview()">Review</button></div></div>`)}
function crReview(){state.cr={item:v('cr-item'),qty:v('cr-qty'),carrier:v('cr-carrier')};shell('Warehouse · Cargo Release','Review release.',`<div class="card">${summary(state.cr)}<div class="notice">Allocation will use live inventory only.</div></div>`)}
async function inventory(){active('inventory');shell('Inventory','Loading…','');try{const rows=await getInventorySnapshot();shell('Inventory','Inventory.',rows.length?`<div class="card">${rows.map(r=>`<div class="record"><strong>${esc(r.item_key||r.part_number||r.sku||'Item')}</strong><div class="summary"><div class="mini"><span>Available</span><b>${esc(r.total_units??0)}</b></div><div class="mini"><span>Cartons</span><b>${esc(r.carton_count??0)}</b></div><div class="mini"><span>Pallets</span><b>${esc(r.pallet_count??0)}</b></div></div></div>`).join('')}</div>`:`<div class="card"><div class="empty">No inventory yet.</div></div>`)}catch(e){shell('Inventory','Inventory error.',`<div class="notice">${esc(e.message)}</div>` )}}
function summary(o){return Object.entries(o).filter(([,x])=>x).map(([k,x])=>`<div class="status"><span>${esc(k.replaceAll('_',' '))}</span><b>${esc(x)}</b></div>`).join('')||'<div class="empty">No values entered</div>'}
window.home=home;window.newWR=newWR;window.searchWR=searchWR;window.wrDetails=wrDetails;window.wrCargo=wrCargo;window.wrReview=wrReview;window.newCR=newCR;window.searchCR=searchCR;window.crManual=crManual;window.crReview=crReview;window.inventory=inventory;window.login=login;window.signup=signup;window.logout=logout;
(async()=>{try{state.session=await getSession();if(state.session){await ensureWorkspace();home()}else authScreen()}catch(e){authScreen(e.message)}})();
