import './theme.js';
import './nav-icon-polish.js';
const main=document.getElementById('main');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function intent(text){const t=String(text||'').trim(),l=t.toLowerCase();if(!t)return{type:'empty'};if(/\b(create|new|receive).*\b(wr|warehouse receipt|receipt)\b|\bwarehouse receipt\b/.test(l))return{type:'route',route:'wr',label:'Open Warehouse Receipts / create WR'};if(/\b(create|new).*\b(cr|cargo release|release)\b|\bcargo release\b/.test(l))return{type:'route',route:'release',label:'Open Cargo Releases'};if(/\binventory|stock|on hand|available cargo\b/.test(l))return{type:'route',route:'inventory',label:'Open Inventory'};if(/\blocation|rack|bin|position\b/.test(l))return{type:'route',route:'warehouse_locations',label:'Open Locations'};if(/\brate|pricing agreement|rate book\b/.test(l))return{type:'route',route:'pricing_rates',label:'Open Rate Book'};if(/\bquote|rfq|rate request|pricing|air freight|ocean freight|drayage\b/.test(l)||t.length>160)return{type:'rfq',label:'Analyze as RFQ'};return{type:'ask',label:'Search / ask NODARA'}}
function extractRFQ(t){const s=String(t||''),mode=/\bocean|fcl|lcl|container|vessel\b/i.test(s)?'OCEAN':/\bair|airline|airport|awb\b/i.test(s)?'AIR':/\bdrayage|truck|ftl|ltl|pickup|delivery\b/i.test(s)?'GROUND':'UNDETERMINED',w=s.match(/([0-9]+(?:\.[0-9]+)?)\s*(kg|kgs|lb|lbs|pounds?)\b/i),dims=s.match(/([0-9]+(?:\.[0-9]+)?)\s*[x×]\s*([0-9]+(?:\.[0-9]+)?)\s*[x×]\s*([0-9]+(?:\.[0-9]+)?)/i),pcs=s.match(/([0-9]+)\s*(pallets?|boxes?|cartons?|crates?|pieces?|pcs)\b/i),from=s.match(/(?:from|origin[:\s]+)\s*([A-Z]{3}|[A-Za-z .'-]{3,30}?)(?=\s+(?:to|destination|dest)\b|[,\n])/i),to=s.match(/(?:to|destination|dest[:\s]+)\s*([A-Z]{3}|[A-Za-z .'-]{3,30}?)(?=[,\n]|\s+(?:cargo|weight|dims|dimensions|pickup|delivery)\b|$)/i);return{mode,origin:from?.[1]?.trim()||'',destination:to?.[1]?.trim()||'',pieces:pcs?`${pcs[1]} ${pcs[2].toUpperCase()}`:'',weight:w?`${w[1]} ${w[2].toUpperCase()}`:'',dimensions:dims?`${dims[1]} × ${dims[2]} × ${dims[3]}`:'',raw:s}}
function previewRFQ(data,host){host.innerHTML=`<div class="command-preview-head"><div><span class="eyebrow">RFQ DETECTED</span><h3>${esc(data.origin||'Origin?')} → ${esc(data.destination||'Destination?')}</h3></div><span class="status-pill">${esc(data.mode)}</span></div><div class="command-preview-grid"><div><span>Mode</span><b>${esc(data.mode)}</b></div><div><span>Cargo</span><b>${esc(data.pieces||'Not detected')}</b></div><div><span>Weight</span><b>${esc(data.weight||'Not detected')}</b></div><div><span>Dimensions</span><b>${esc(data.dimensions||'Not detected')}</b></div></div><div class="command-preview-actions"><button class="secondary compact-btn" data-command-edit>Edit details</button><button class="primary compact-btn" data-command-build>Build Quote</button></div>`;host.querySelector('[data-command-build]').onclick=()=>{sessionStorage.setItem('nodara:rfq-draft',JSON.stringify(data));window.nodaraGo?.('pricing_quotes')};host.querySelector('[data-command-edit]').onclick=()=>window.nodaraGo?.('pricing_quotes')}
function run(text,host){const i=intent(text);if(i.type==='empty')return;if(i.type==='route'){host.innerHTML=`<div class="command-result"><b>${esc(i.label)}</b><button class="primary compact-btn">Continue</button></div>`;host.querySelector('button').onclick=()=>window.nodaraGo?.(i.route);return}if(i.type==='rfq'){previewRFQ(extractRFQ(text),host);return}host.innerHTML=`<div class="command-result"><b>NODARA understood the request.</b><small>General AI Q&A and action execution will use this same command surface as the intelligence service is connected.</small></div>`}
function startVoice(textarea,button){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return alert('Voice input is not supported by this browser.');const r=new SR();r.lang='en-US';r.interimResults=true;r.continuous=false;const base=textarea.value.trim();r.onstart=()=>button.classList.add('active');r.onend=()=>button.classList.remove('active');r.onresult=e=>{let spoken='';for(let i=0;i<e.results.length;i++)spoken+=e.results[i][0].transcript;textarea.value=[base,spoken].filter(Boolean).join(base?' ':'');textarea.dispatchEvent(new Event('input',{bubbles:true}))};r.start()}
function box({pricing=false}={}){const wrap=document.createElement('section');wrap.className=`nodara-command-box ${pricing?'pricing-command-box':''}`;wrap.innerHTML=`<div class="command-box-head"><div><span class="eyebrow">${pricing?'SMART RFQ':'NODARA COMMAND'}</span><h2>${pricing?'What are we pricing?':'What do you want NODARA to do?'}</h2></div><span class="command-ai-dot">AI</span></div><textarea data-command-input rows="${pricing?5:4}" placeholder="${pricing?'Paste an RFQ or email, describe the lane, cargo and services, or use voice…':'Type a command, ask a question, paste an email, RFQ or operational instruction…'}"></textarea><div class="command-box-footer"><div class="command-hints"><span>Paste</span><span>Ask</span><span>Command</span></div><div class="command-box-actions"><button class="secondary compact-btn" data-command-voice>◉ Voice</button><button class="primary compact-btn" data-command-run>${pricing?'Analyze RFQ':'Run'}</button></div></div><div class="command-result-host" data-command-result></div>`;const input=wrap.querySelector('[data-command-input]'),result=wrap.querySelector('[data-command-result]'),runBtn=wrap.querySelector('[data-command-run]'),voice=wrap.querySelector('[data-command-voice]');runBtn.onclick=()=>run(input.value,result);voice.onclick=()=>startVoice(input,voice);input.onkeydown=e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();run(input.value,result)}};return wrap}
function enhanceHome(){if(window.__nodaraRoute!=='home'||main.querySelector('.nodara-command-box'))return;const heading=main.querySelector('.dash-heading')||main.firstElementChild,el=box();if(heading?.parentNode)heading.after(el);else main.prepend(el)}
function enhancePricing(){if(window.__nodaraRoute!=='pricing_dashboard'||main.querySelector('.pricing-command-box'))return;const heading=main.querySelector('.dash-heading')||main.firstElementChild,el=box({pricing:true});if(heading?.parentNode)heading.after(el);else main.prepend(el)}
function addFloating(){if(document.getElementById('nodara-float-ai'))return;const b=document.createElement('button');b.id='nodara-float-ai';b.className='nodara-float-ai';b.innerHTML='<span>N°</span><small>Ask</small>';b.onclick=()=>{document.querySelector('.nodara-float-panel')?.remove();const p=document.createElement('div');p.className='nodara-float-panel';p.appendChild(box());document.body.appendChild(p);const close=document.createElement('button');close.className='subtle nodara-float-close';close.textContent='×';close.onclick=()=>p.remove();p.prepend(close)};document.body.appendChild(b)}
function enhance(){if(!window.__nodaraAuthenticated)return;enhanceHome();enhancePricing();addFloating()}
let queued=false;new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;enhance()})}).observe(main,{childList:true,subtree:true});setTimeout(enhance,700);