const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const store=(key,val)=>val===undefined?JSON.parse(localStorage.getItem(`nodara:view:${key}`)||'null'):localStorage.setItem(`nodara:view:${key}`,JSON.stringify(val));
export function mountDataView({container,key,rows,columns,onOpen,defaultColumns,searchText}){
 let cfg=store(key)||{columns:defaultColumns||columns.map(c=>c.key),sort:null,dir:'asc',group:null,density:'comfortable',saved:{}};
 cfg.columns=cfg.columns.filter(k=>columns.some(c=>c.key===k));if(!cfg.columns.length)cfg.columns=defaultColumns||columns.map(c=>c.key);
 let query='',panel=false;
 const col=k=>columns.find(c=>c.key===k),val=(r,k)=>col(k)?.value?.(r)??r[k]??'',text=r=>searchText?searchText(r):columns.map(c=>String(val(r,c.key))).join(' ');
 function processed(){let out=rows.filter(r=>!query||text(r).toLowerCase().includes(query.toLowerCase()));if(cfg.sort){const k=cfg.sort;out=[...out].sort((a,b)=>String(val(a,k)).localeCompare(String(val(b,k)),undefined,{numeric:true,sensitivity:'base'}));if(cfg.dir==='desc')out.reverse()}return out}
 function save(){store(key,cfg)}
 function paint(){const out=processed(),visible=cfg.columns.map(col).filter(Boolean);container.innerHTML=`<div class="view-manager-bar"><div class="view-search"><span>⌕</span><input data-view-search placeholder="Search this view…" value="${esc(query)}"></div><div class="view-manager-actions"><button class="secondary compact-btn" data-view-density>${cfg.density==='compact'?'Compact':'Comfortable'}</button><button class="secondary compact-btn" data-view-config>☷ View</button></div></div>${panel?configPanel():''}<div class="smart-grid-wrap"><div class="smart-grid ${cfg.density==='compact'?'compact':''}" style="--cols:${visible.map(c=>c.width||'minmax(120px,1fr)').join(' ')}"><div class="smart-grid-row head">${visible.map(c=>`<button data-sort="${c.key}">${esc(c.label)}${cfg.sort===c.key?(cfg.dir==='asc'?' ↑':' ↓'):''}</button>`).join('')}<span></span></div>${cfg.group?grouped(out,visible):out.map(r=>rowHtml(r,visible)).join('')}</div></div>`;
  container.querySelector('[data-view-search]').oninput=e=>{query=e.target.value;paint()};container.querySelector('[data-view-config]').onclick=()=>{panel=!panel;paint()};container.querySelector('[data-view-density]').onclick=()=>{cfg.density=cfg.density==='compact'?'comfortable':'compact';save();paint()};container.querySelectorAll('[data-sort]').forEach(b=>b.onclick=()=>{cfg.dir=cfg.sort===b.dataset.sort&&cfg.dir==='asc'?'desc':'asc';cfg.sort=b.dataset.sort;save();paint()});container.querySelectorAll('[data-grid-open]').forEach(b=>b.onclick=()=>onOpen?.(b.dataset.gridOpen));bindConfig();
 }
 function rowHtml(r,visible){return `<button class="smart-grid-row body" data-grid-open="${r.id}">${visible.map(c=>`<div>${c.render?c.render(r):esc(val(r,c.key))}</div>`).join('')}<i>›</i></button>`}
 function grouped(out,visible){const groups=new Map();for(const r of out){const g=String(val(r,cfg.group)||'Unassigned');if(!groups.has(g))groups.set(g,[]);groups.get(g).push(r)}return [...groups].map(([g,rs])=>`<div class="smart-grid-group"><div class="smart-grid-group-title"><b>${esc(g)}</b><span>${rs.length}</span></div>${rs.map(r=>rowHtml(r,visible)).join('')}</div>`).join('')}
 function configPanel(){return `<div class="view-config-panel"><div class="view-config-head"><div><b>Configure view</b><small>Columns, order, grouping and saved layouts</small></div><button class="subtle" data-close-view>×</button></div><div class="view-config-grid"><section><label>Columns</label>${columns.map(c=>{const i=cfg.columns.indexOf(c.key);return `<div class="column-option"><input type="checkbox" data-col-toggle="${c.key}" ${i>=0?'checked':''}><span>${esc(c.label)}</span>${i>=0?`<button data-col-up="${c.key}" ${i===0?'disabled':''}>↑</button><button data-col-down="${c.key}" ${i===cfg.columns.length-1?'disabled':''}>↓</button>`:''}</div>`}).join('')}</section><section><label>Group by</label><select data-group><option value="">No grouping</option>${columns.map(c=>`<option value="${c.key}" ${cfg.group===c.key?'selected':''}>${esc(c.label)}</option>`).join('')}</select><label>Save current view</label><div class="save-view-row"><input data-view-name placeholder="e.g. Receiving Today"><button class="secondary" data-save-view>Save</button></div><label>Saved views</label><div class="saved-view-list">${Object.keys(cfg.saved||{}).map(n=>`<button data-load-view="${esc(n)}">${esc(n)}</button>`).join('')||'<small>No saved views yet.</small>'}</div></section></div></div>`}
 function bindConfig(){if(!panel)return;container.querySelector('[data-close-view]')?.addEventListener('click',()=>{panel=false;paint()});container.querySelectorAll('[data-col-toggle]').forEach(x=>x.onchange=()=>{cfg.columns=x.checked?[...cfg.columns,x.dataset.colToggle]:cfg.columns.filter(k=>k!==x.dataset.colToggle);save();paint()});container.querySelectorAll('[data-col-up]').forEach(b=>b.onclick=()=>move(b.dataset.colUp,-1));container.querySelectorAll('[data-col-down]').forEach(b=>b.onclick=()=>move(b.dataset.colDown,1));container.querySelector('[data-group]').onchange=e=>{cfg.group=e.target.value||null;save();paint()};container.querySelector('[data-save-view]').onclick=()=>{const n=container.querySelector('[data-view-name]').value.trim();if(!n)return;cfg.saved=cfg.saved||{};cfg.saved[n]={columns:[...cfg.columns],sort:cfg.sort,dir:cfg.dir,group:cfg.group,density:cfg.density};save();paint()};container.querySelectorAll('[data-load-view]').forEach(b=>b.onclick=()=>{Object.assign(cfg,cfg.saved[b.dataset.loadView]);save();paint()})}
 function move(k,d){const i=cfg.columns.indexOf(k),j=i+d;if(i<0||j<0||j>=cfg.columns.length)return;[cfg.columns[i],cfg.columns[j]]=[cfg.columns[j],cfg.columns[i]];save();paint()}
 paint();return{refresh:newRows=>{rows=newRows;paint()}};
}
