import { supabase } from './supabase-client.js';
const main=document.getElementById('main');
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const CATS=['GENERAL','RECEIVING','SHIPPING','TRANSPORTATION','COMMERCIAL','CUSTOMER','POD','PHOTO','REGULATORY','FTZ'];
let state={context:null,docs:[],links:[],selected:new Set(),q:'',cat:'',status:'ACTIVE'};
async function org(){const{data}=await supabase.from('organization_members').select('organization_id').limit(1).maybeSingle();return data?.organization_id}
const title=d=>d.display_name||d.file_name||'Untitled document';
async function audit(d,action,detail={}){await supabase.from('document_activity').insert({organization_id:d.organization_id,document_id:d.id,action,detail})}
async function signed(d,seconds=600){const{data,error}=await supabase.storage.from('nodara-documents').createSignedUrl(d.storage_path,seconds);if(error)throw error;return data.signedUrl}
async function load(){let q=supabase.from('documents').select('*').eq('is_current',true).order('created_at',{ascending:false}).limit(1500);const{data,error}=await q;if(error)throw error;state.docs=data||[];if(state.context){const{data:l}=await supabase.from('document_links').select('*').eq('context_type',state.context.type).eq('context_id',state.context.id);state.links=l||[];const ids=new Set(state.links.map(x=>x.document_id));state.docs=state.docs.filter(d=>ids.has(d.id)||(state.context.type==='WR'&&d.warehouse_receipt_id===state.context.id))}}
function filtered(){const q=state.q.toLowerCase();return state.docs.filter(d=>(!state.cat||d.category===state.cat)&&(!state.status||String(d.status||'ACTIVE').toUpperCase()===state.status)&&(!q||[title(d),d.document_type,d.category,d.document_number,d.notes].filter(Boolean).join(' ').toLowerCase().includes(q)))}
function contextLabel(d){if(d.warehouse_receipt_id)return 'Warehouse Receipt';if(d.transaction_id)return 'Transaction';const l=state.links.find(x=>x.document_id===d.id);return l?.context_reference||l?.context_type||'Organization'}
function render(){
 const rows=filtered(),n=state.selected.size;
 main.innerHTML=`<div class="dm-shell"><div class="dm-head"><div>${state.context?'<button class="dm-context-back" id="dm-back">‹ '+esc(state.context.backLabel||'Back to record')+'</button>':''}<div><div class="eyebrow">NODARA RECORDS</div><h1 class="title">${esc(state.context?.label||'Documents')}</h1><p class="muted">${state.context?'Documents linked to this record.':'One canonical repository across operations, warehouse and compliance.'}</p></div><div class="dm-capture"><button class="secondary" id="dm-scan">▣ Scan</button><button class="secondary" id="dm-photo">◎ Photo</button><button class="primary" id="dm-upload">＋ Upload</button></div></div>
 <div class="dm-toolbar"><div class="inventory-searchbox"><span>⌕</span><input id="dm-search" placeholder="Search name, type, number, notes…" value="${esc(state.q)}"></div><select id="dm-cat"><option value="">All categories</option>${CATS.map(x=>`<option ${state.cat===x?'selected':''}>${x}</option>`).join('')}</select><select id="dm-status"><option value="ACTIVE">Active</option><option value="">All statuses</option><option value="SUPERSEDED">Superseded</option><option value="VOID">Void</option></select></div>
 ${n?`<div class="dm-selection"><b>${n} selected</b><span></span><button data-batch="download">Download</button><button data-batch="zip">Download ZIP</button><button data-batch="share">Share</button><button data-batch="email">Email</button><button class="danger" data-batch="void">Void</button><button id="dm-clear">×</button></div>`:''}
 <div class="dm-table"><div class="dm-row dm-th"><input type="checkbox" id="dm-all" ${rows.length&&rows.every(d=>state.selected.has(d.id))?'checked':''}><span>Name</span><span>Category</span><span>Related to</span><span>Uploaded</span><span>Status</span><span></span></div>
 ${rows.map(d=>`<div class="dm-row" data-open="${d.id}"><input type="checkbox" data-select="${d.id}" ${state.selected.has(d.id)?'checked':''}><span class="dm-name"><i>${d.mime_type?.startsWith('image/')?'IMG':d.mime_type?.includes('pdf')?'PDF':'DOC'}</i><span><b>${esc(title(d))}</b><small>${esc(d.document_type||'Document')}${d.version_no>1?' · v'+d.version_no:''}${d.ftz_controlled?' · FTZ':''}</small></span></span><span><b>${esc(d.category||'GENERAL')}</b></span><span>${esc(contextLabel(d))}</span><span>${new Date(d.created_at).toLocaleDateString()}<small>${new Date(d.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small></span><span class="status-pill">${esc(d.status||'ACTIVE')}</span><button class="icon-btn" data-more="${d.id}">•••</button></div>`).join('')||'<div class="empty">No documents match this view.</div>'}</div></div>`;
 bind()
}
function bind(){ document.getElementById('dm-back')?.addEventListener('click',()=>state.context?.onBack?.());
 document.getElementById('dm-search').oninput=e=>{state.q=e.target.value;render()};document.getElementById('dm-cat').onchange=e=>{state.cat=e.target.value;render()};document.getElementById('dm-status').onchange=e=>{state.status=e.target.value;render()};
 document.querySelectorAll('[data-select]').forEach(x=>x.onclick=e=>{e.stopPropagation();x.checked?state.selected.add(x.dataset.select):state.selected.delete(x.dataset.select);render()});
 document.getElementById('dm-all')?.addEventListener('change',e=>{filtered().forEach(d=>e.target.checked?state.selected.add(d.id):state.selected.delete(d.id));render()});document.getElementById('dm-clear')?.addEventListener('click',()=>{state.selected.clear();render()});
 document.querySelectorAll('[data-open]').forEach(x=>x.onclick=e=>{if(e.target.closest('input,button'))return;preview(state.docs.find(d=>d.id===x.dataset.open))});document.querySelectorAll('[data-more]').forEach(x=>x.onclick=e=>{e.stopPropagation();preview(state.docs.find(d=>d.id===x.dataset.more))});
 document.getElementById('dm-upload').onclick=()=>pick(false,false);document.getElementById('dm-photo').onclick=()=>pick(true,false);document.getElementById('dm-scan').onclick=()=>pick(true,true);document.querySelectorAll('[data-batch]').forEach(b=>b.onclick=()=>batch(b.dataset.batch))
}
function pick(camera,scan){const i=document.createElement('input');i.type='file';i.accept=camera?'image/*':'image/*,.pdf,.doc,.docx,.xls,.xlsx,.csv,.txt';i.multiple=!camera;if(camera)i.setAttribute('capture','environment');i.onchange=()=>upload(i.files,scan?'SCAN':camera?'PHOTO':'UPLOAD');i.click()}
async function upload(files,source){const oid=await org();if(!oid)return alert('Organization context is unavailable.');for(const f of [...files]){const safe=f.name.replace(/[^a-zA-Z0-9._-]/g,'_'),path=`${oid}/canonical/${crypto.randomUUID()}_${safe}`;const{error:up}=await supabase.storage.from('nodara-documents').upload(path,f,{contentType:f.type||'application/octet-stream'});if(up)return alert(up.message);const cat=source==='PHOTO'?'PHOTO':'GENERAL';const payload={organization_id:oid,document_type:source==='SCAN'?'SCANNED_DOCUMENT':'DOCUMENT',storage_path:path,file_name:f.name,mime_type:f.type||null,display_name:f.name,category:cat,source,status:'ACTIVE',metadata:{surface:'CANONICAL_DOCUMENT_MANAGER'},provenance:{capture_source:source}};if(state.context?.type==='WR')payload.warehouse_receipt_id=state.context.id;const{data:d,error}=await supabase.from('documents').insert(payload).select().single();if(error)return alert(error.message);if(state.context){const link={organization_id:oid,document_id:d.id,context_type:state.context.type,context_id:state.context.id,context_reference:state.context.reference||state.context.label||null,link_role:'SUPPORTING',provenance:{surface:'CANONICAL_DOCUMENT_MANAGER'}};await supabase.from('document_links').insert(link)}await audit(d,'UPLOADED',{source})}await load();render()}
async function preview(d){if(!d)return;let url='';try{url=await signed(d)}catch{}const{data:acts}=await supabase.from('document_activity').select('*').eq('document_id',d.id).order('created_at',{ascending:false}).limit(30);const m=document.createElement('div');m.className='modal-overlay dm-preview-overlay';m.innerHTML=`<div class="modal-card dm-preview"><div class="dm-preview-head"><div><div class="eyebrow">${esc(d.category||'DOCUMENT')}</div><h2>${esc(title(d))}</h2><small>${esc(d.document_type||'Document')} · v${d.version_no||1}${d.ftz_controlled?' · FTZ controlled':''}</small></div><button class="icon-btn" data-close>×</button></div><div class="dm-preview-grid"><div class="dm-viewer">${d.mime_type?.startsWith('image/')&&url?`<img src="${url}">`:url?`<iframe src="${url}"></iframe>`:'<div class="empty">Preview unavailable</div>'}</div><aside><label>Name</label><div class="row"><input id="dmp-name" value="${esc(title(d))}"><button id="dmp-rename">Save</button></div><label>Category</label><select id="dmp-cat">${CATS.map(x=>`<option ${d.category===x?'selected':''}>${x}</option>`).join('')}</select><div class="dm-meta"><span>Uploaded<b>${new Date(d.created_at).toLocaleString()}</b></span><span>Status<b>${esc(d.status||'ACTIVE')}</b></span><span>Related to<b>${esc(contextLabel(d))}</b></span></div><div class="row dm-actions"><button id="dmp-download">Download</button><button id="dmp-share">Share</button><button id="dmp-email">Email</button></div><h3>Activity</h3><div class="dm-activity">${(acts||[]).map(a=>`<div><b>${esc(a.action)}</b><small>${new Date(a.created_at).toLocaleString()}</small></div>`).join('')||'<small>No activity recorded yet.</small>'}</div></aside></div></div>`;document.body.appendChild(m);m.querySelector('[data-close]').onclick=()=>m.remove();m.onclick=e=>{if(e.target===m)m.remove()};m.querySelector('#dmp-download').onclick=()=>download(d);m.querySelector('#dmp-share').onclick=()=>shareDocs([d]);m.querySelector('#dmp-email').onclick=()=>emailDocs([d]);m.querySelector('#dmp-rename').onclick=async()=>{const name=m.querySelector('#dmp-name').value.trim(),category=m.querySelector('#dmp-cat').value;if(!name)return;await supabase.from('documents').update({display_name:name,category,updated_at:new Date().toISOString()}).eq('id',d.id);await audit(d,'METADATA_UPDATED',{name,category});m.remove();await load();render()}}
async function download(d){const u=await signed(d);const a=document.createElement('a');a.href=u;a.download=title(d);a.click();await audit(d,'DOWNLOADED')}
async function shareDocs(ds){const links=await Promise.all(ds.map(async d=>({d,url:await signed(d,3600)})));const text=links.map(x=>title(x.d)+': '+x.url).join('\n');if(navigator.share)await navigator.share({title:'NODARA Documents',text});else await navigator.clipboard.writeText(text);for(const d of ds)await audit(d,'SHARED')}
async function emailDocs(ds){const links=await Promise.all(ds.map(async d=>title(d)+': '+await signed(d,3600)));location.href='mailto:?subject='+encodeURIComponent('NODARA Documents')+'&body='+encodeURIComponent(links.join('\n\n'));for(const d of ds)await audit(d,'EMAIL_PREPARED')}
async function batch(kind){const ds=state.docs.filter(d=>state.selected.has(d.id));if(!ds.length)return;if(kind==='share')return shareDocs(ds);if(kind==='email')return emailDocs(ds);if(kind==='download'){for(const d of ds)await download(d);return}if(kind==='zip'){if(!window.JSZip)return alert('ZIP service is still loading.');const z=new JSZip();for(const d of ds){const u=await signed(d);z.file(title(d),await(await fetch(u)).blob())}const blob=await z.generateAsync({type:'blob'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='NODARA_Documents_'+new Date().toISOString().slice(0,10)+'.zip';a.click();ds.forEach(d=>audit(d,'DOWNLOADED_ZIP'));return}if(kind==='void'){if(!confirm('Void selected documents? Files remain preserved for audit history.'))return;for(const d of ds){await supabase.from('documents').update({status:'VOID',is_current:false,updated_at:new Date().toISOString()}).eq('id',d.id);await audit(d,'VOIDED',{reason:'User bulk action'})}state.selected.clear();await load();render()}}
export async function open(context=null){state={context,docs:[],links:[],selected:new Set(),q:'',cat:'',status:'ACTIVE'};try{await load();render()}catch(e){main.innerHTML=`<div class="notice warning">${esc(e.message)}</div>`}}
window.NodaraDocuments={open};window.nodaraDocuments=()=>open();
