import { supabase } from './supabase-client.js';
const main=document.getElementById('main');
const ROLES=['customer','vendor','shipper','consignee','carrier','trucker','broker','driver','billing_party','airline','steamship_line','warehouse','agent','cfs','ftz_operator','customs_broker'];
const EVIDENCE_TYPES=['GENERAL_PHOTO','FRONT','BACK','LEFT','RIGHT','LABEL_PHOTO','SERIAL_PHOTO','HT_STAMP_PHOTO','DAMAGE_PHOTO','SEAL_PHOTO','WEIGHT_PHOTO','DIMENSION_PHOTO','POD_PHOTO','OTHER'];
const RECEIVE_BY=['service','handling_unit','part_number','sku','lot','serial','unit'];
const SERVICES=['STORAGE','DISTRIBUTION','FULFILLMENT','CROSS_DOCK','FREIGHT_FORWARDING','AIR','OCEAN','GROUND','FTZ','BONDED','PICKUP_DELIVERY','OTHER'];
const RELATIONSHIP_TYPES=['PARENT_COMPANY','SUBSIDIARY','BILL_TO','BROKER','CUSTOMS_BROKER','FREIGHT_FORWARDER','CARRIER','TRUCKER','WAREHOUSE','CFS','AGENT','SHIPPER','CONSIGNEE','VENDOR','OTHER'];
const RATE_BASIS=['FLAT','PER_RECEIPT','PER_PALLET','PER_PACKAGE','PER_UNIT','PER_LB','PER_CWT','PER_CBM','PER_DAY','PER_MONTH','PER_HOUR','PER_MILE','PERCENT'];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function org(){const{data,error}=await supabase.rpc('bootstrap_workspace',{p_name:'NODARA Workspace'});if(error)throw error;return data}
async function rows(){const{data,error}=await supabase.from('entities').select('id,name,code,roles,email,phone,sop,updated_at').order('name');if(error)throw error;return data||[]}
export async function openEntitiesModule(){window.nodaraSetActive?.('entities');main.innerHTML='<div class="eyebrow">Settings</div><h1 class="title">Entities</h1><p class="muted">Loading master data…</p>';const data=await rows();renderList(data)}
function renderList(data){main.innerHTML=`<div class="eyebrow">Settings · Master Data</div><div class="module-landing-head"><div><h1 class="title">Entities</h1><p class="muted">Reusable parties, contacts, addresses, SOPs and commercial rules.</p></div><button class="primary compact-btn" id="new-entity">＋ New Entity</button></div><div class="context-bar"><div class="context-search"><span>⌕</span><input id="entity-search" placeholder="Search name, code, role…"></div></div><div id="entity-list"></div>`;const paint=list=>{document.getElementById('entity-list').innerHTML=`<div class="entity-table">${list.map(e=>`<button class="entity-row" data-entity="${e.id}"><div><b>${esc(e.name)}</b><small>${esc(e.code||'')}</small></div><div class="role-chips">${(e.roles||[]).slice(0,5).map(r=>`<span>${esc(r.replaceAll('_',' '))}</span>`).join('')}${(e.roles||[]).length>5?`<span>+${e.roles.length-5}</span>`:''}</div><div>${esc(e.email||e.phone||'')}</div><i>›</i></button>`).join('')}</div>`;document.querySelectorAll('[data-entity]').forEach(b=>b.onclick=()=>editEntity(list.find(e=>e.id===b.dataset.entity)))};paint(data);document.getElementById('entity-search').oninput=e=>{const q=e.target.value.toLowerCase();paint(data.filter(x=>[x.name,x.code,x.email,x.phone,...(x.roles||[])].filter(Boolean).some(v=>String(v).toLowerCase().includes(q))))};document.getElementById('new-entity').onclick=()=>editEntity({name:'',code:'',roles:[],email:'',phone:'',sop:{}})}
async function editEntity(e){
 const sop=e.sop||{};let roles=[...(e.roles||[])];let contacts=[...(sop.contacts||[])];let addresses=[...(sop.addresses||[])];let evidence=[...(sop.receiving?.evidence||[])];let rates=[...(sop.rates||[])];let services=[...(sop.services||[])];
 let summary=null,vendorSummary=null,vendorCompliance=null,vendorProfile=null,vendorRequirements=[],customerOps=[],customerCharges=[],customerDocs=[],customerInventory=[],relatedEntities=[]; if(e.id&&roles.includes('customer')){try{const oid=await org();const [{data:s},{data:wr},{data:cr},{data:sh},{data:to},{data:charges},{data:docs},{data:inv},{data:rels}]=await Promise.all([supabase.rpc('nodara_customer_summary',{p_organization_id:oid,p_customer_id:e.id}),supabase.rpc('nodara_customer_receipts',{p_organization_id:oid,p_customer_id:e.id,p_limit:8}),supabase.from('cargo_releases').select('id,release_number,status,created_at').eq('customer_id',e.id).order('created_at',{ascending:false}).limit(8),supabase.from('shipments').select('id,shipment_number,status,created_at').eq('customer_id',e.id).order('created_at',{ascending:false}).limit(8),supabase.from('transport_orders').select('id,order_number,status,created_at').eq('customer_id',e.id).order('created_at',{ascending:false}).limit(8),supabase.from('operational_charges').select('id,source_type,description,sell_amount,currency,billing_status,created_at').eq('customer_id',e.id).order('created_at',{ascending:false}).limit(12),supabase.from('document_links').select('id,document_id,link_role,created_at,documents(display_name,file_name,document_type,status)').eq('entity_id',e.id).order('created_at',{ascending:false}).limit(12),supabase.rpc('nodara_customer_inventory',{p_organization_id:oid,p_customer_id:e.id}),supabase.from('entity_relationships').select('id,relationship_type,notes,related_entity_id,entities!entity_relationships_related_entity_id_fkey(name,code,roles)').eq('entity_id',e.id).eq('active',true)]);summary=s;customerOps=[...(wr||[]).map(x=>({...x,type:'WR',ref:x.reference})),...(cr||[]).map(x=>({...x,type:'CR',ref:x.release_number})),...(sh||[]).map(x=>({...x,type:'SHIPMENT',ref:x.shipment_number})),...(to||[]).map(x=>({...x,type:'TRANSPORT',ref:x.order_number}))].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).slice(0,12);customerCharges=charges||[];customerDocs=docs||[];customerInventory=inv||[];relatedEntities=rels||[]}catch(_){}}
 if(e.id&&(roles.includes('vendor')||roles.includes('carrier')||roles.includes('trucker')||roles.includes('customs_broker'))){try{const oid=await org();const [{data:v},{data:vc},{data:vp},{data:vr}]=await Promise.all([supabase.rpc('nodara_vendor_summary',{p_organization_id:oid,p_vendor_id:e.id}),supabase.rpc('nodara_vendor_compliance_summary',{p_organization_id:oid,p_vendor_id:e.id}),supabase.from('vendor_profiles').select('*').eq('organization_id',oid).eq('entity_id',e.id).maybeSingle(),supabase.from('entity_compliance_requirements').select('*').eq('organization_id',oid).eq('entity_id',e.id).order('expires_on',{ascending:true,nullsFirst:false})]);vendorSummary=v;vendorCompliance=vc;vendorProfile=vp;vendorRequirements=vr||[]}catch(_){}}
 const rec=sop.receiving||{},bill=sop.billing||{},ship=sop.shipments||{};
 if(!contacts.length&&(e.email||e.phone))contacts.push({name:'Primary',title:'',email:e.email||'',phone:e.phone||'',roles:['primary']});
 if(!evidence.length&&Number(rec.photo_sides||0)>=4)evidence=[{type:'FRONT',min:1,scope:'top_level_piece',when:'always'},{type:'BACK',min:1,scope:'top_level_piece',when:'always'},{type:'LEFT',min:1,scope:'top_level_piece',when:'always'},{type:'RIGHT',min:1,scope:'top_level_piece',when:'always'}];
 function render(){
  main.innerHTML=`<div class="record-commandbar"><button class="secondary compact-btn" id="entity-back">‹ Entities</button></div><div class="eyebrow">Settings · Entity Master</div><div class="record-header"><div><h1 class="title">${esc(e.name||'New Entity')}</h1><p class="muted">One reusable profile across pricing, warehouse, operations, accounting and FTZ.</p></div><span class="status-pill">Master data</span></div>
  <div class="record-tabs entity-tabs"><button class="${summary||vendorSummary?'active':''}" data-jump="${summary?'overview':vendorSummary?'vendor-overview':'identity'}">Overview</button><button class="${summary||vendorSummary?'':'active'}" data-jump="identity">Identity</button><button data-jump="contacts">Contacts <span>${contacts.length}</span></button><button data-jump="addresses">Addresses <span>${addresses.length}</span></button><button data-jump="sop">SOP</button><button data-jump="rates">Rates <span>${rates.length}</span></button><button data-jump="customer-operations" ${summary?'':'hidden'}>Operations</button><button data-jump="customer-inventory" ${summary?'':'hidden'}>Inventory</button><button data-jump="customer-related" ${summary?'':'hidden'}>Related</button><button data-jump="customer-billing" ${summary?'':'hidden'}>Billing</button><button data-jump="customer-documents" ${summary?'':'hidden'}>Documents</button><button data-jump="vendor-profile" ${vendorSummary?'':'hidden'}>Vendor</button><button data-jump="vendor-compliance" ${vendorSummary?'':'hidden'}>Compliance <span>${vendorRequirements.length}</span></button></div>
<section class="record-section" id="vendor-overview" ${vendorSummary?'':'hidden'}><div class="section-heading"><div><h3>Vendor 360</h3><span class="muted">Operational usage, spend and payable exposure in one place.</span></div></div><div class="customer-summary-grid"><div><small>Transport orders</small><b>${vendorSummary?.transport_orders??0}</b></div><div><small>Open transport</small><b>${vendorSummary?.transport_open??0}</b></div><div><small>Delivered</small><b>${vendorSummary?.transport_delivered??0}</b></div><div><small>Shipments</small><b>${vendorSummary?.shipments??0}</b></div><div><small>Spend</small><b>${Number(vendorSummary?.spend||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}</b></div><div><small>Open payables</small><b>${vendorSummary?.open_payables??0}</b><em>${Number(vendorSummary?.open_payable_amount||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}</em></div><div><small>Vendor charges</small><b>${vendorSummary?.charges??0}</b></div><div><small>Documents</small><b>${vendorSummary?.documents??0}</b></div></div><div class="customer-health-strip"><span class="${vendorProfile?.approval_status==='APPROVED'?'':'attention'}">${vendorProfile?.approval_status||'REVIEW'} vendor</span><span class="${(vendorCompliance?.expired||vendorCompliance?.missing)?'attention':''}">${vendorCompliance?((vendorCompliance.expired||0)+' expired · '+(vendorCompliance.missing||0)+' missing'):'Compliance not configured'}</span><span><i></i> ${vendorSummary?.transport_open>0?vendorSummary.transport_open+' active transport order'+(vendorSummary.transport_open===1?'':'s'):'No open transport'}</span><span class="${vendorSummary?.open_payables>0?'attention':''}">${vendorSummary?.open_payables>0?vendorSummary.open_payables+' payable item'+(vendorSummary.open_payables===1?'':'s'):'Payables clear'}</span></div><div class="customer-summary-actions"><button class="secondary compact-btn" data-jump="contacts">Contacts</button><button class="secondary compact-btn" data-jump="rates">Buy rates</button><button class="secondary compact-btn" data-jump="sop">SOP / requirements</button></div></section>
<section class="record-section" id="vendor-profile" ${vendorSummary?'':'hidden'}><div class="section-heading"><div><h3>Vendor Management</h3><span class="muted">Approval, commercial terms, service coverage and capabilities.</span></div></div><div class="detail-grid"><div class="field"><label>Approval status</label><select id="vendor-approval">${['REVIEW','APPROVED','CONDITIONAL','SUSPENDED','INACTIVE'].map(x=>`<option ${vendorProfile?.approval_status===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Payment terms</label><input id="vendor-terms" value="${esc(vendorProfile?.payment_terms||'')}" placeholder="Net 30"></div><div class="field span2"><label>Service areas</label><input id="vendor-areas" value="${esc((vendorProfile?.service_areas||[]).join(', '))}" placeholder="Miami, South Florida, PortMiami"></div><div class="field span2"><label>Equipment / capabilities</label><input id="vendor-equipment" value="${esc((vendorProfile?.equipment_capabilities||[]).join(', '))}" placeholder="53 FT, reefer, flatbed, bonded carrier"></div><div class="field span2"><label>Vendor notes</label><textarea id="vendor-notes" rows="3">${esc(vendorProfile?.notes||'')}</textarea></div></div><div class="record-footer-actions"><button class="secondary" id="vendor-docs">Documents</button><button class="primary" id="vendor-profile-save">Save Vendor Profile</button></div></section>
<section class="record-section" id="vendor-compliance" ${vendorSummary?'':'hidden'}><div class="section-heading"><div><h3>Vendor Compliance</h3><span class="muted">Requirements, expirations and supporting evidence.</span></div><button class="secondary compact-btn" id="add-vendor-requirement">＋ Requirement</button></div><div class="customer-360-list">${vendorRequirements.length?vendorRequirements.map(x=>{const expired=x.expires_on&&new Date(x.expires_on+'T12:00:00')<new Date();const soon=x.expires_on&&!expired&&(new Date(x.expires_on+'T12:00:00')-new Date())<2592000000;return `<div><span class="status-pill ${expired||x.status==='MISSING'?'attention':''}">${expired?'EXPIRED':esc(x.status)}</span><b>${esc(x.label)}</b><span>${esc(x.reference||x.requirement_type.replaceAll('_',' '))}</span><small>${x.expires_on?(soon?'Expires ':'')+new Date(x.expires_on+'T12:00:00').toLocaleDateString():'No expiration'}</small><button class="subtle" data-edit-vendor-req="${x.id}">Edit</button></div>`}).join(''):'<div class="empty compact">No compliance requirements configured.</div>'}</div></section>
<section class="record-section" id="overview" ${summary?'':'hidden'}><div class="section-heading"><div><h3>Customer 360</h3><span class="muted">Operations, commercial and account health in one place.</span></div><button class="secondary compact-btn" id="customer-soa">Statement of Account</button></div><div class="customer-summary-grid"><div><small>Transactions</small><b>${summary?.transactions??0}</b></div><div><small>Warehouse receipts</small><b>${summary?.warehouse_receipts??0}</b></div><div><small>Cargo releases</small><b>${summary?.cargo_releases??0}</b></div><div><small>Shipments</small><b>${summary?.shipments??0}</b></div><div><small>Transport orders</small><b>${summary?.transport_orders??0}</b></div><div><small>Unbilled</small><b>${summary?.unbilled_charges??0}</b></div><div><small>Charges</small><b>${Number(summary?.charge_amount||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}</b></div><div><small>Active rates</small><b>${summary?.active_rates??0}</b></div><div><small>Documents</small><b>${summary?.documents??0}</b></div></div><div class="customer-health-strip"><span><i></i> ${summary?.inventory_quantity>0?'Inventory on hand':'No inventory on hand'}</span><span class="${summary?.unbilled_charges>0?'attention':''}">${summary?.unbilled_charges>0?summary.unbilled_charges+' unbilled charge'+(summary.unbilled_charges===1?'':'s'):'Billing clear'}</span><span>${summary?.active_rates||0} active rate${summary?.active_rates===1?'':'s'}</span></div><div class="customer-summary-actions"><button class="secondary compact-btn" data-jump="contacts">Contacts</button><button class="secondary compact-btn" data-jump="rates">Rates</button><button class="secondary compact-btn" data-jump="sop">SOP / onboarding</button></div></section>
  <section class="record-section" id="customer-operations" ${summary?'':'hidden'}><div class="section-heading"><div><h3>Recent Operations</h3><span class="muted">Latest customer transactions across operational modules.</span></div></div><div class="customer-360-list">${customerOps.length?customerOps.map(x=>`<div><span class="status-pill">${esc(x.type)}</span><b>${esc(x.ref||'—')}</b><span>${esc(x.status||'—')}</span><small>${x.created_at?new Date(x.created_at).toLocaleDateString():''}</small></div>`).join(''):'<div class="empty compact">No customer operations yet.</div>'}</div></section>
  <section class="record-section" id="customer-inventory" ${summary?'':'hidden'}><div class="section-heading"><div><h3>Inventory</h3><span class="muted">Current customer-owned balances by item.</span></div></div><div class="customer-360-list inventory">${customerInventory.length?customerInventory.map(x=>`<div><span class="status-pill">${esc(x.sku||x.part_number||'ITEM')}</span><b>${esc(x.description||x.part_number||x.sku||'Inventory item')}</b><span>${Number(x.available||0).toLocaleString()} available · ${Number(x.reserved||0).toLocaleString()} reserved</span><small>${x.locations||0} loc.</small></div>`).join(''):'<div class="empty compact">No inventory balances on hand.</div>'}</div></section>
  <section class="record-section" id="customer-related" ${summary?'':'hidden'}><div class="section-heading"><div><h3>Related Entities</h3><span class="muted">Subsidiaries, brokers, vendors, carriers and other customer relationships.</span></div><button class="secondary compact-btn" id="add-related-entity">＋ Relationship</button></div><div class="customer-360-list">${relatedEntities.length?relatedEntities.map(x=>`<div><span class="status-pill">${esc(x.relationship_type)}</span><b>${esc(x.entities?.name||'Entity')}</b><span>${esc((x.entities?.roles||[]).join(' · '))}</span><small>${esc(x.entities?.code||'')}</small></div>`).join(''):'<div class="empty compact">No related entities yet.</div>'}</div></section>
  <section class="record-section" id="customer-billing" ${summary?'':'hidden'}><div class="section-heading"><div><h3>Billing & SOA</h3><span class="muted">Operational charges and billing readiness.</span></div><button class="secondary compact-btn" id="customer-soa-2">Statement of Account</button></div><div class="customer-360-list">${customerCharges.length?customerCharges.map(x=>`<div><span class="status-pill">${esc(x.billing_status||'UNBILLED')}</span><b>${esc(x.description||x.source_type||'Charge')}</b><span>${esc(x.currency||'USD')} ${Number(x.sell_amount||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}</span><small>${x.created_at?new Date(x.created_at).toLocaleDateString():''}</small></div>`).join(''):'<div class="empty compact">No operational charges yet.</div>'}</div></section>
  <section class="record-section" id="customer-documents" ${summary?'':'hidden'}><div class="section-heading"><div><h3>Documents & Onboarding</h3><span class="muted">Customer-level agreements, onboarding and supporting documents.</span></div><button class="secondary compact-btn" id="customer-doc-manager">Open Documents</button></div><div class="customer-360-list">${customerDocs.length?customerDocs.map(x=>`<div><span class="status-pill">${esc(x.documents?.document_type||x.link_role||'DOCUMENT')}</span><b>${esc(x.documents?.display_name||x.documents?.file_name||'Document')}</b><span>${esc(x.documents?.status||'')}</span><small>${x.created_at?new Date(x.created_at).toLocaleDateString():''}</small></div>`).join(''):'<div class="empty compact">No customer documents yet.</div>'}</div></section>
  <section class="record-section" id="identity"><div class="section-heading"><h3>Identity & Roles</h3><span class="section-state">Multiple roles allowed</span></div><div class="detail-grid"><div class="field"><label>Name</label><input id="ent-name" value="${esc(e.name||'')}"></div><div class="field"><label>Code</label><input id="ent-code" value="${esc(e.code||'')}"></div><div class="field"><label>Primary Email</label><input id="ent-email" value="${esc(e.email||'')}"></div><div class="field"><label>Primary Phone</label><input id="ent-phone" value="${esc(e.phone||'')}"></div></div><div class="flag-block"><label>Roles</label><div class="flag-grid">${ROLES.map(r=>`<button class="flag-chip ${roles.includes(r)?'selected':''}" data-role="${r}">${esc(r.replaceAll('_',' '))}</button>`).join('')}</div></div><div class="flag-block"><label>Services / relationship scope</label><div class="flag-grid">${SERVICES.map(s=>`<button class="flag-chip ${services.includes(s)?'selected':''}" data-service="${s}">${s.replaceAll('_',' ')}</button>`).join('')}</div></div></section>
  <section class="record-section" id="contacts"><div class="section-heading"><div><h3>Contacts</h3><span class="muted">Operations, billing, warehouse, after-hours, etc.</span></div><button class="secondary compact-btn" id="add-contact">＋ Contact</button></div><div id="contact-list">${contacts.length?contacts.map((c,i)=>contactRow(c,i)).join(''):'<div class="empty compact">No contacts yet.</div>'}</div></section>
  <section class="record-section" id="addresses"><div class="section-heading"><div><h3>Addresses</h3><span class="muted">Billing, pickup, delivery, warehouse, office, port/CFS.</span></div><button class="secondary compact-btn" id="add-address">＋ Address</button></div><div id="address-list">${addresses.length?addresses.map((a,i)=>addressRow(a,i)).join(''):'<div class="empty compact">No addresses yet.</div>'}</div></section>
  <section class="record-section" id="sop"><div class="section-heading"><div><h3>SOP · Receiving & Evidence</h3><span class="muted">Rules can be repeated and conditional.</span></div><button class="secondary compact-btn" id="add-evidence">＋ Evidence rule</button></div><div class="detail-grid"><div class="field"><label>Default receiving granularity</label><select id="receive-by">${RECEIVE_BY.map(x=>`<option value="${x}" ${rec.receive_by===x?'selected':''}>${x.replaceAll('_',' ')}</option>`).join('')}</select></div><div class="field"><label>Default service / workflow</label><select id="default-service"><option value="">No default</option>${SERVICES.map(x=>`<option value="${x}" ${rec.default_service===x?'selected':''}>${x.replaceAll('_',' ')}</option>`).join('')}</select></div></div><div class="sop-grid"><label><input id="sop-weight" type="checkbox" ${rec.require_weight?'checked':''}> Weight required</label><label><input id="sop-dims" type="checkbox" ${rec.require_dimensions?'checked':''}> Dimensions required</label><label><input id="sop-po" type="checkbox" ${ship.require_po?'checked':''}> PO/reference required</label><label><input id="sop-serial" type="checkbox" ${rec.require_serial_capture?'checked':''}> Serial capture required when present</label></div><div class="field"><label>Required receiving documents</label><input id="sop-docs" value="${esc((rec.required_documents||[]).join(', '))}" placeholder="BOL, PACKING_LIST, COMMERCIAL_INVOICE"></div><div class="field"><label>Evidence rules</label><div id="evidence-list">${evidence.length?evidence.map((r,i)=>evidenceRow(r,i)).join(''):'<div class="empty compact">No photo/evidence requirements. Add only what this entity actually requires.</div>'}</div></div><div class="field"><label>Operational instructions</label><textarea id="sop-notes" rows="4" placeholder="Free-form customer/vendor operating instructions…">${esc(sop.notes||'')}</textarea></div></section>
  <section class="record-section" id="rates"><div class="section-heading"><div><h3>Entity Rates</h3><span class="muted">Customer sell rates or vendor/carrier buy rates by service/basis.</span></div><button class="secondary compact-btn" id="add-rate">＋ Rate</button></div><div id="rate-list">${rates.length?rates.map((r,i)=>rateRow(r,i)).join(''):'<div class="empty compact">No saved rates.</div>'}</div><div class="field"><label>Automatic / expected charge types</label><input id="sop-charges" value="${esc((bill.auto_charges||[]).join(', '))}" placeholder="RECEIVING, STORAGE, LABEL"></div></section>
  <div class="record-footer-actions"><button class="danger-btn" id="entity-delete" ${e.id?'':'hidden'}>Delete</button><button class="primary" id="entity-save">Save Entity</button></div>`;
  bind();
 }
 function contactRow(c,i){return `<div class="master-row contact-master-row"><div class="field"><label>Name</label><input data-c-name="${i}" value="${esc(c.name||'')}"></div><div class="field"><label>Title / Role</label><input data-c-title="${i}" value="${esc(c.title||'')}"></div><div class="field"><label>Email</label><input data-c-email="${i}" value="${esc(c.email||'')}"></div><div class="field"><label>Phone</label><input data-c-phone="${i}" value="${esc(c.phone||'')}"></div><button class="subtle danger-text" data-remove-contact="${i}">×</button></div>`}
 function addressRow(a,i){return `<div class="master-row address-master-row"><div class="field"><label>Type</label><select data-a-type="${i}">${['office','billing','warehouse','pickup','delivery','port','cfs','other'].map(x=>`<option ${a.type===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Name / Facility</label><input data-a-name="${i}" value="${esc(a.name||'')}"></div><div class="field span2"><label>Address</label><input data-a-line1="${i}" value="${esc(a.line1||'')}" placeholder="Street, city, state, ZIP, country"></div><button class="subtle danger-text" data-remove-address="${i}">×</button></div>`}
 function evidenceRow(r,i){return `<div class="master-row evidence-master-row"><div class="field"><label>Evidence</label><select data-e-type="${i}">${EVIDENCE_TYPES.map(x=>`<option ${r.type===x?'selected':''}>${x.replaceAll('_',' ')}</option>`).join('')}</select></div><div class="field"><label>Minimum</label><input data-e-min="${i}" type="number" min="1" value="${Number(r.min||1)}"></div><div class="field"><label>Applies to</label><select data-e-scope="${i}">${['receipt','top_level_piece','each_package','each_item','each_serial','damaged_piece'].map(x=>`<option value="${x}" ${r.scope===x?'selected':''}>${x.replaceAll('_',' ')}</option>`).join('')}</select></div><div class="field"><label>When</label><select data-e-when="${i}">${['always','if_present','if_damaged','if_ht_wood','if_serialized','if_dg','if_ftz','if_bonded'].map(x=>`<option value="${x}" ${r.when===x?'selected':''}>${x.replaceAll('_',' ')}</option>`).join('')}</select></div><button class="subtle danger-text" data-remove-evidence="${i}">×</button></div>`}
 function rateRow(r,i){return `<div class="master-row rate-master-row"><div class="field"><label>Service / Charge</label><input data-r-charge="${i}" value="${esc(r.charge||'')}" placeholder="Receiving / Storage / Drayage"></div><div class="field"><label>Side</label><select data-r-side="${i}"><option ${r.side==='sell'?'selected':''}>sell</option><option ${r.side==='buy'?'selected':''}>buy</option></select></div><div class="field"><label>Basis</label><select data-r-basis="${i}">${RATE_BASIS.map(x=>`<option ${r.basis===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Rate</label><input data-r-rate="${i}" type="number" step="0.01" min="0" value="${Number(r.rate||0)}"></div><div class="field"><label>Minimum</label><input data-r-min="${i}" type="number" step="0.01" min="0" value="${Number(r.minimum||0)}"></div><button class="subtle danger-text" data-remove-rate="${i}">×</button></div>`}
 function sync(){
  contacts=contacts.map((c,i)=>({...c,name:document.querySelector(`[data-c-name="${i}"]`)?.value.trim()||'',title:document.querySelector(`[data-c-title="${i}"]`)?.value.trim()||'',email:document.querySelector(`[data-c-email="${i}"]`)?.value.trim()||'',phone:document.querySelector(`[data-c-phone="${i}"]`)?.value.trim()||''}));
  addresses=addresses.map((a,i)=>({...a,type:document.querySelector(`[data-a-type="${i}"]`)?.value||'office',name:document.querySelector(`[data-a-name="${i}"]`)?.value.trim()||'',line1:document.querySelector(`[data-a-line1="${i}"]`)?.value.trim()||''}));
  evidence=evidence.map((r,i)=>({...r,type:document.querySelector(`[data-e-type="${i}"]`)?.value||'GENERAL_PHOTO',min:Math.max(1,Number(document.querySelector(`[data-e-min="${i}"]`)?.value||1)),scope:document.querySelector(`[data-e-scope="${i}"]`)?.value||'top_level_piece',when:document.querySelector(`[data-e-when="${i}"]`)?.value||'always'}));
  rates=rates.map((r,i)=>({...r,charge:document.querySelector(`[data-r-charge="${i}"]`)?.value.trim()||'',side:document.querySelector(`[data-r-side="${i}"]`)?.value||'sell',basis:document.querySelector(`[data-r-basis="${i}"]`)?.value||'FLAT',rate:Number(document.querySelector(`[data-r-rate="${i}"]`)?.value||0),minimum:Number(document.querySelector(`[data-r-min="${i}"]`)?.value||0),currency:'USD'}));
 }
 function bind(){
  document.getElementById('entity-back').onclick=openEntitiesModule;document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.jump)?.scrollIntoView({behavior:'smooth',block:'start'}));
  document.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{roles=roles.includes(b.dataset.role)?roles.filter(x=>x!==b.dataset.role):[...roles,b.dataset.role];b.classList.toggle('selected')});
  document.querySelectorAll('[data-service]').forEach(b=>b.onclick=()=>{services=services.includes(b.dataset.service)?services.filter(x=>x!==b.dataset.service):[...services,b.dataset.service];b.classList.toggle('selected')});
  document.getElementById('add-contact').onclick=()=>{sync();contacts.push({name:'',title:'',email:'',phone:'',roles:[]});render()};document.querySelectorAll('[data-remove-contact]').forEach(b=>b.onclick=()=>{sync();contacts.splice(+b.dataset.removeContact,1);render()});
  document.getElementById('add-address').onclick=()=>{sync();addresses.push({type:'office',name:'',line1:''});render()};document.querySelectorAll('[data-remove-address]').forEach(b=>b.onclick=()=>{sync();addresses.splice(+b.dataset.removeAddress,1);render()});
  document.getElementById('add-evidence').onclick=()=>{sync();evidence.push({type:'GENERAL_PHOTO',min:1,scope:'top_level_piece',when:'always'});render()};document.querySelectorAll('[data-remove-evidence]').forEach(b=>b.onclick=()=>{sync();evidence.splice(+b.dataset.removeEvidence,1);render()});
  document.getElementById('add-rate').onclick=()=>{sync();rates.push({charge:'',side:'sell',basis:'FLAT',rate:0,minimum:0,currency:'USD'});render()};document.querySelectorAll('[data-remove-rate]').forEach(b=>b.onclick=()=>{sync();rates.splice(+b.dataset.removeRate,1);render()});
  document.getElementById('add-vendor-requirement')?.addEventListener('click',()=>openVendorRequirement());document.querySelectorAll('[data-edit-vendor-req]').forEach(b=>b.onclick=()=>openVendorRequirement(vendorRequirements.find(x=>x.id===b.dataset.editVendorReq)));document.getElementById('vendor-docs')?.addEventListener('click',()=>window.NodaraDocuments?.open?.({type:'ENTITY',id:e.id,reference:e.code||e.name,label:e.name+' · Vendor Documents',backLabel:e.name,onBack:()=>editEntity(e)}));document.getElementById('vendor-profile-save')?.addEventListener('click',saveVendorProfile);const soa=()=>alert('SOA workspace will use this customer’s billing ledger and document delivery history.');document.getElementById('customer-soa')?.addEventListener('click',soa);document.getElementById('customer-soa-2')?.addEventListener('click',soa);document.getElementById('add-related-entity')?.addEventListener('click',openRelationshipEditor);document.getElementById('customer-doc-manager')?.addEventListener('click',()=>window.NodaraDocuments?.open?.({type:'ENTITY',id:e.id,reference:e.code||e.name,label:e.name+' · Documents',backLabel:e.name,onBack:()=>editEntity(e)}));document.getElementById('entity-save').onclick=save;document.getElementById('entity-delete')?.addEventListener('click',remove);
 }



 async function openVendorRequirement(req={}){const oid=await org();const wrap=document.createElement('div');wrap.className='record-modal';wrap.innerHTML=`<button class="record-modal-backdrop" data-vr-close></button><div class="record-modal-panel"><div class="section-heading"><div><h3>${req.id?'Edit':'Add'} compliance requirement</h3><span class="muted">Track the requirement separately from its supporting document.</span></div><button class="subtle" data-vr-close>×</button></div><div class="detail-grid"><div class="field"><label>Type</label><select id="vr-type">${['INSURANCE_COI','W9','OPERATING_AUTHORITY','BOND','LICENSE','AGREEMENT','SECURITY','OTHER'].map(x=>`<option value="${x}" ${req.requirement_type===x?'selected':''}>${x.replaceAll('_',' ')}</option>`).join('')}</select></div><div class="field"><label>Status</label><select id="vr-status">${['REQUIRED','MISSING','VALID','PENDING','WAIVED','VOID'].map(x=>`<option ${req.status===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field span2"><label>Label</label><input id="vr-label" value="${esc(req.label||'')}" placeholder="Certificate of Insurance"></div><div class="field"><label>Issued</label><input id="vr-issued" type="date" value="${esc(req.issued_on||'')}"></div><div class="field"><label>Expires</label><input id="vr-expires" type="date" value="${esc(req.expires_on||'')}"></div><div class="field span2"><label>Reference / policy number</label><input id="vr-ref" value="${esc(req.reference||'')}"></div><div class="field span2"><label>Notes</label><textarea id="vr-notes" rows="3">${esc(req.notes||'')}</textarea></div></div><div class="record-footer-actions"><button class="secondary" data-vr-close>Cancel</button><button class="primary" id="vr-save">Save Requirement</button></div></div>`;document.body.appendChild(wrap);wrap.querySelectorAll('[data-vr-close]').forEach(b=>b.onclick=()=>wrap.remove());wrap.querySelector('#vr-save').onclick=async()=>{const label=wrap.querySelector('#vr-label').value.trim();if(!label)return alert('Label is required');const payload={organization_id:oid,entity_id:e.id,requirement_type:wrap.querySelector('#vr-type').value,label,status:wrap.querySelector('#vr-status').value,issued_on:wrap.querySelector('#vr-issued').value||null,expires_on:wrap.querySelector('#vr-expires').value||null,reference:wrap.querySelector('#vr-ref').value.trim()||null,notes:wrap.querySelector('#vr-notes').value.trim()||null,updated_at:new Date().toISOString()};const q=req.id?supabase.from('entity_compliance_requirements').update(payload).eq('id',req.id):supabase.from('entity_compliance_requirements').insert(payload);const{error}=await q;if(error)return alert(error.message);wrap.remove();await editEntity(e)}}

 async function saveVendorProfile(){const oid=await org();const payload={organization_id:oid,entity_id:e.id,approval_status:document.getElementById('vendor-approval').value,payment_terms:document.getElementById('vendor-terms').value.trim()||null,service_areas:document.getElementById('vendor-areas').value.split(',').map(x=>x.trim()).filter(Boolean),equipment_capabilities:document.getElementById('vendor-equipment').value.split(',').map(x=>x.trim()).filter(Boolean),notes:document.getElementById('vendor-notes').value.trim()||null,updated_at:new Date().toISOString()};const{error}=await supabase.from('vendor_profiles').upsert(payload,{onConflict:'organization_id,entity_id'});if(error)return alert(error.message);vendorProfile=payload;await editEntity(e)}

 async function openRelationshipEditor(){
  if(!e.id)return alert('Save the entity first.');
  const oid=await org();const {data:choices,error}=await supabase.from('entities').select('id,name,code,roles').eq('organization_id',oid).neq('id',e.id).order('name');if(error)return alert(error.message);
  const wrap=document.createElement('div');wrap.className='record-modal';wrap.innerHTML=`<button class="record-modal-backdrop" data-rel-close></button><div class="record-modal-panel"><div class="section-heading"><div><h3>Add relationship</h3><span class="muted">Link an existing entity. No duplicate master record is created.</span></div><button class="subtle" data-rel-close>×</button></div><div class="field"><label>Related entity</label><input id="rel-search" placeholder="Search entity…"><div id="rel-results" class="relationship-results"></div></div><div class="field"><label>Relationship</label><select id="rel-type">${RELATIONSHIP_TYPES.map(x=>`<option value="${x}">${x.replaceAll('_',' ')}</option>`).join('')}</select></div><div class="field"><label>Notes</label><textarea id="rel-notes" rows="3" placeholder="Optional relationship notes"></textarea></div><div class="record-footer-actions"><button class="secondary" data-rel-close>Cancel</button><button class="primary" id="rel-save" disabled>Save relationship</button></div></div>`;document.body.appendChild(wrap);let selected=null;const paint=q=>{const f=(choices||[]).filter(x=>!q||[x.name,x.code,...(x.roles||[])].filter(Boolean).some(v=>String(v).toLowerCase().includes(q.toLowerCase()))).slice(0,12);wrap.querySelector('#rel-results').innerHTML=f.map(x=>`<button data-rel-id="${x.id}"><b>${esc(x.name)}</b><small>${esc(x.code||'')} · ${esc((x.roles||[]).join(', '))}</small></button>`).join('')||'<div class="empty compact">No matching entity.</div>';wrap.querySelectorAll('[data-rel-id]').forEach(b=>b.onclick=()=>{selected=b.dataset.relId;wrap.querySelectorAll('[data-rel-id]').forEach(x=>x.classList.toggle('selected',x===b));wrap.querySelector('#rel-save').disabled=false})};paint('');wrap.querySelector('#rel-search').oninput=x=>paint(x.target.value);wrap.querySelectorAll('[data-rel-close]').forEach(b=>b.onclick=()=>wrap.remove());wrap.querySelector('#rel-save').onclick=async()=>{if(!selected)return;const payload={organization_id:oid,entity_id:e.id,related_entity_id:selected,relationship_type:wrap.querySelector('#rel-type').value,notes:wrap.querySelector('#rel-notes').value.trim()||null};const {error:err}=await supabase.from('entity_relationships').upsert(payload,{onConflict:'organization_id,entity_id,related_entity_id,relationship_type'});if(err)return alert(err.message);wrap.remove();await editEntity(e)};
 }

 async function save(){sync();const name=document.getElementById('ent-name').value.trim();if(!name)return alert('Name is required');const payload={name,code:document.getElementById('ent-code').value.trim()||null,email:document.getElementById('ent-email').value.trim()||null,phone:document.getElementById('ent-phone').value.trim()||null,roles,sop:{...sop,services,contacts:contacts.filter(x=>x.name||x.email||x.phone),addresses:addresses.filter(x=>x.name||x.line1),receiving:{...rec,receive_by:document.getElementById('receive-by').value,default_service:document.getElementById('default-service').value||null,require_weight:document.getElementById('sop-weight').checked,require_dimensions:document.getElementById('sop-dims').checked,require_serial_capture:document.getElementById('sop-serial').checked,required_documents:document.getElementById('sop-docs').value.split(',').map(x=>x.trim()).filter(Boolean),evidence},shipments:{...ship,require_po:document.getElementById('sop-po').checked},billing:{...bill,auto_charges:document.getElementById('sop-charges').value.split(',').map(x=>x.trim()).filter(Boolean)},rates:rates.filter(x=>x.charge),notes:document.getElementById('sop-notes').value.trim()}};let error;if(e.id)({error}=await supabase.from('entities').update(payload).eq('id',e.id));else{const organization_id=await org();({error}=await supabase.from('entities').insert({...payload,organization_id}))}if(error)return alert(error.message);openEntitiesModule()}
 async function remove(){if(!confirm(`Delete ${e.name}? Existing records will keep historical display data where available.`))return;const{error}=await supabase.from('entities').delete().eq('id',e.id);if(error)return alert(error.message);openEntitiesModule()}
 render();
}
window.nodaraEntities=openEntitiesModule;