import { supabase } from './supabase-client.js';
const main=document.getElementById('main');
const ROLES=['customer','vendor','shipper','consignee','carrier','trucker','broker','driver','billing_party','airline','steamship_line','warehouse','agent','cfs','ftz_operator','customs_broker'];
const EVIDENCE_TYPES=['GENERAL_PHOTO','FRONT','BACK','LEFT','RIGHT','LABEL_PHOTO','SERIAL_PHOTO','HT_STAMP_PHOTO','DAMAGE_PHOTO','SEAL_PHOTO','WEIGHT_PHOTO','DIMENSION_PHOTO','POD_PHOTO','OTHER'];
const RECEIVE_BY=['service','handling_unit','part_number','sku','lot','serial','unit'];
const SERVICES=['STORAGE','DISTRIBUTION','FULFILLMENT','CROSS_DOCK','FREIGHT_FORWARDING','AIR','OCEAN','GROUND','FTZ','BONDED','PICKUP_DELIVERY','OTHER'];
const RATE_BASIS=['FLAT','PER_RECEIPT','PER_PALLET','PER_PACKAGE','PER_UNIT','PER_LB','PER_CWT','PER_CBM','PER_DAY','PER_MONTH','PER_HOUR','PER_MILE','PERCENT'];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function org(){const{data,error}=await supabase.rpc('bootstrap_workspace',{p_name:'NODARA Workspace'});if(error)throw error;return data}
async function rows(){const{data,error}=await supabase.from('entities').select('id,name,code,roles,email,phone,sop,updated_at').order('name');if(error)throw error;return data||[]}
export async function openEntitiesModule(){window.nodaraSetActive?.('entities');main.innerHTML='<div class="eyebrow">Settings</div><h1 class="title">Entities</h1><p class="muted">Loading master data…</p>';const data=await rows();renderList(data)}
function renderList(data){main.innerHTML=`<div class="eyebrow">Settings · Master Data</div><div class="module-landing-head"><div><h1 class="title">Entities</h1><p class="muted">Reusable parties, contacts, addresses, SOPs and commercial rules.</p></div><button class="primary compact-btn" id="new-entity">＋ New Entity</button></div><div class="context-bar"><div class="context-search"><span>⌕</span><input id="entity-search" placeholder="Search name, code, role…"></div></div><div id="entity-list"></div>`;const paint=list=>{document.getElementById('entity-list').innerHTML=`<div class="entity-table">${list.map(e=>`<button class="entity-row" data-entity="${e.id}"><div><b>${esc(e.name)}</b><small>${esc(e.code||'')}</small></div><div class="role-chips">${(e.roles||[]).slice(0,5).map(r=>`<span>${esc(r.replaceAll('_',' '))}</span>`).join('')}${(e.roles||[]).length>5?`<span>+${e.roles.length-5}</span>`:''}</div><div>${esc(e.email||e.phone||'')}</div><i>›</i></button>`).join('')}</div>`;document.querySelectorAll('[data-entity]').forEach(b=>b.onclick=()=>editEntity(list.find(e=>e.id===b.dataset.entity)))};paint(data);document.getElementById('entity-search').oninput=e=>{const q=e.target.value.toLowerCase();paint(data.filter(x=>[x.name,x.code,x.email,x.phone,...(x.roles||[])].filter(Boolean).some(v=>String(v).toLowerCase().includes(q))))};document.getElementById('new-entity').onclick=()=>editEntity({name:'',code:'',roles:[],email:'',phone:'',sop:{}})}
function editEntity(e){
 const sop=e.sop||{};let roles=[...(e.roles||[])];let contacts=[...(sop.contacts||[])];let addresses=[...(sop.addresses||[])];let evidence=[...(sop.receiving?.evidence||[])];let rates=[...(sop.rates||[])];let services=[...(sop.services||[])];
 const rec=sop.receiving||{},bill=sop.billing||{},ship=sop.shipments||{};
 if(!contacts.length&&(e.email||e.phone))contacts.push({name:'Primary',title:'',email:e.email||'',phone:e.phone||'',roles:['primary']});
 if(!evidence.length&&Number(rec.photo_sides||0)>=4)evidence=[{type:'FRONT',min:1,scope:'top_level_piece',when:'always'},{type:'BACK',min:1,scope:'top_level_piece',when:'always'},{type:'LEFT',min:1,scope:'top_level_piece',when:'always'},{type:'RIGHT',min:1,scope:'top_level_piece',when:'always'}];
 function render(){
  main.innerHTML=`<div class="record-commandbar"><button class="secondary compact-btn" id="entity-back">‹ Entities</button></div><div class="eyebrow">Settings · Entity Master</div><div class="record-header"><div><h1 class="title">${esc(e.name||'New Entity')}</h1><p class="muted">One reusable profile across pricing, warehouse, operations, accounting and FTZ.</p></div><span class="status-pill">Master data</span></div>
  <div class="record-tabs entity-tabs"><button class="active" data-jump="identity">Identity</button><button data-jump="contacts">Contacts <span>${contacts.length}</span></button><button data-jump="addresses">Addresses <span>${addresses.length}</span></button><button data-jump="sop">SOP</button><button data-jump="rates">Rates <span>${rates.length}</span></button></div>
  <section class="record-section" id="identity"><div class="section-heading"><h3>Identity & Roles</h3><span class="section-state">Multiple roles allowed</span></div><div class="detail-grid"><div class="field"><label>Name</label><input id="ent-name" value="${esc(e.name||'')}"></div><div class="field"><label>Code</label><input id="ent-code" value="${esc(e.code||'')}"></div><div class="field"><label>Primary Email</label><input id="ent-email" value="${esc(e.email||'')}"></div><div class="field"><label>Primary Phone</label><input id="ent-phone" value="${esc(e.phone||'')}"></div></div><div class="flag-block"><label>Roles</label><div class="flag-grid">${ROLES.map(r=>`<button class="flag-chip ${roles.includes(r)?'selected':''}" data-role="${r}">${esc(r.replaceAll('_',' '))}</button>`).join('')}</div></div><div class="flag-block"><label>Services / relationship scope</label><div class="flag-grid">${SERVICES.map(s=>`<button class="flag-chip ${services.includes(s)?'selected':''}" data-service="${s}">${s.replaceAll('_',' ')}</button>`).join('')}</div></div></section>
  <section class="record-section" id="contacts"><div class="section-heading"><div><h3>Contacts</h3><span class="muted">Operations, billing, warehouse, after-hours, etc.</span></div><button class="secondary compact-btn" id="add-contact">＋ Contact</button></div><div id="contact-list">${contacts.length?contacts.map((c,i)=>contactRow(c,i)).join(''):'<div class="empty compact">No contacts yet.</div>'}</div></section>
  <section class="record-section" id="addresses"><div class="section-heading"><div><h3>Addresses</h3><span class="muted">Billing, pickup, delivery, warehouse, office, port/CFS.</span></div><button class="secondary compact-btn" id="add-address">＋ Address</button></div><div id="address-list">${addresses.length?addresses.map((a,i)=>addressRow(a,i)).join(''):'<div class="empty compact">No addresses yet.</div>'}</div></section>
  <section class="record-section" id="sop"><div class="section-heading"><div><h3>SOP · Receiving & Evidence</h3><span class="muted">Rules can be repeated and conditional.</span></div><button class="secondary compact-btn" id="add-evidence">＋ Evidence rule</button></div><div class="detail-grid"><div class="field"><label>Default receiving granularity</label><select id="receive-by">${RECEIVE_BY.map(x=>`<option value="${x}" ${rec.receive_by===x?'selected':''}>${x.replaceAll('_',' ')}</option>`).join('')}</select></div><div class="field"><label>Default service / workflow</label><select id="default-service"><option value="">No default</option>${SERVICES.map(x=>`<option value="${x}" ${rec.default_service===x?'selected':''}>${x.replaceAll('_',' ')}</option>`).join('')}</select></div></div><div class="sop-grid"><label><input id="sop-weight" type="checkbox" ${rec.require_weight?'checked':''}> Weight required</label><label><input id="sop-dims" type="checkbox" ${rec.require_dimensions?'checked':''}> Dimensions required</label><label><input id="sop-po" type="checkbox" ${ship.require_po?'checked':''}> PO/reference required</label><label><input id="sop-serial" type="checkbox" ${rec.require_serial_capture?'checked':''}> Serial capture required when present</label></div><div class="field"><label>Required receiving documents</label><input id="sop-docs" value="${esc((rec.required_documents||[]).join(', '))}" placeholder="BOL, PACKING_LIST, COMMERCIAL_INVOICE"></div><div class="field"><label>Evidence rules</label><div id="evidence-list">${evidence.length?evidence.map((r,i)=>evidenceRow(r,i)).join(''):'<div class="empty compact">No photo/evidence requirements. Add only what this entity actually requires.</div>'}</div></div><div class="field"><label>Operational instructions</label><textarea id="sop-notes" rows="4" placeholder="Free-form customer/vendor operating instructions…">${esc(sop.notes||'')}</textarea></div></section>
  <section class="record-section" id="rates"><div class="section-heading"><div><h3>Entity Rates</h3><span class="muted">Customer sell rates or vendor/carrier buy rates by service/basis.</span></div><button class="secondary compact-btn" id="add-rate">＋ Rate</button></div><div id="rate-list">${rates.length?rates.map((r,i)=>rateRow(r,i)).join(''):'<div class="empty compact">No saved rates.</div>'}</div><div class="field"><label>Automatic / expected charge types</label><input id="sop-charges" value="${esc((bill.auto_charges||[]).join(', '))}" placeholder="RECEIVING, STORAGE, LABEL"></div></section>
  <div class="record-footer-actions"><button class="danger-btn" id="entity-delete" ${e.id?'':'hidden'}>Delete</button><button class="primary" id="entity-save">Save Entity</button></div>`;
  bind();
 }
 function contactRow(c,i){return `<div class="master-row contact-master-row"><div class="field"><label>Name</label><input data-c-name="${i}" value="${esc(c.name||'')}"></div><div class="field"><label>Title / Role</label><input data-c-title="${i}" value="${esc(c.title||'')}"></div><div class="field"><label>Email</label><input data-c-email="${i}" value="${esc(c.email||'')}"></div><div class="field"><label>Phone</label><input data-c-phone="${i}" value="${esc(c.phone||'')}"></div><button class="subtle danger-text" data-remove-contact="${i}">×</button></div>`}
 function addressRow(a,i){return `<div class="master-row address-master-row"><div class="field"><label>Type</label><select data-a-type="${i}">${['office','billing','warehouse','pickup','delivery','port','cfs','other'].map(x=>`<option ${a.type===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Name / Facility</label><input data-a-name="${i}" value="${esc(a.name||'')}"></div><div class="field span2"><label>Address</label><input data-a-line1="${i}" value="${esc(a.line1||'')}" placeholder="Street, city, state, ZIP, country"></div><button class="subtle danger-text" data-remove-address="${i}">×</button></div>`}
 function evidenceRow(r,i){return `<div class="master-row evidence-master-row"><div class="field"><label>Evidence</label><select data-e-type="${i}">${EVIDENCE_TYPES.map(x=>`<option ${r.type===x?'selected':''}>${x.replaceAll('_',' ')}</option>`).join('')}</select></div><div class="field"><label>Minimum</label><input data-e-min="${i}" type="number" min="1" value="${Number(r.min||1)}"></div><div class="field"><label>Applies to</label><select data-e-scope="${i}">${['receipt','top_level_piece','each_package','each_item','each_serial','damaged_piece'].map(x=>`<option value="${x}" ${r.scope===x?'selected':''}>${x.replaceAll('_',' ')}</option>`).join('')}</select></div><div class="field"><label>When</label><select data-e-when="${i}">${['always','if_present','if_damaged','if_ht_wood','if_serialized','if_dg','if_ftz','if_bonded'].map(x=>`<option value="${x}" ${r.when===x?'selected':''}>${x.replaceAll('_',' ')}</option>`).join('')}</select></div><button class="subtle danger-text" data-remove-evidence="${i}">×</button></div>`}
 function rateRow(r,i){return `<div class="master-row rate-master-row"><div class="field"><label>Service / Charge</label><input data-r-charge="${i}" value="${esc(r.charge||'')}" placeholder="Receiving / Storage / Drayage"></div><div class="field"><label>Side</label><select data-r-side="${i}"><option ${r.side==='sell'?'selected':''}>sell</option><option ${r.side==='buy'?'selected':''}>buy</option></select></div><div class="field"><label>Basis</label><select data-r-basis="${i}">${RATE_BASIS.map(x=>`<option ${r.basis===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Rate</label><input data-r-rate="${i}" type="number" step="0.01" min="0" value="${Number(r.rate||0)}"></div><div class="field"><label>Minimum</label><input data-r-min="${i}" type="number" step="0.01" min="0" value="${Number(r.minimum||0)}"></div><button class="subtle danger-text" data-remove-rate="${i}">×</button></div>`}
 function sync(){
  contacts=contacts.map((c,i)=>({...c,name:document.querySelector(`[data-c-name="${i}"]`)?.value.trim()||'',title:document.querySelector(`[data-c-title="${i}"]`)?.value.trim()||'',email:document.querySelector(`[data-c-email="${i}"]`)?.value.trim()||'',phone:document.querySelector(`[data-c-phone="${i}"]`)?.value.trim()||''}));
  addresses=addresses.map((a,i)=>({...a,type:document.querySelector(`[data-a-type="${i}"]`)?.value||'office',name:document.querySelector(`[data-a-name="${i}"]`)?.value.trim()||'',line1:document.querySelector(`[data-a-line1="${i}"]`)?.value.trim()||''}));
  evidence=evidence.map((r,i)=>({...r,type:document.querySelector(`[data-e-type="${i}"]`)?.value||'GENERAL_PHOTO',min:Math.max(1,Number(document.querySelector(`[data-e-min="${i}"]`)?.value||1)),scope:document.querySelector(`[data-e-scope="${i}"]`)?.value||'top_level_piece',when:document.querySelector(`[data-e-when="${i}"]`)?.value||'always'}));
  rates=rates.map((r,i)=>({...r,charge:document.querySelector(`[data-r-charge="${i}"]`)?.value.trim()||'',side:document.querySelector(`[data-r-side="${i}"]`)?.value||'sell',basis:document.querySelector(`[data-r-basis="${i}"]`)?.value||'FLAT',rate:Number(document.querySelector(`[data-r-rate="${i}"]`)?.value||0),minimum:Number(document.querySelector(`[data-r-min="${i}"]`)?.value||0),currency:'USD'}));
 }
 function bind(){
  document.getElementById('entity-back').onclick=openEntitiesModule;document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.jump)?.scrollIntoView({behavior:'smooth',block:'start'}));
  document.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{roles=roles.includes(b.dataset.role)?roles.filter(x=>x!==b.dataset.role):[...roles,b.dataset.role];b.classList.toggle('selected')});
  document.querySelectorAll('[data-service]').forEach(b=>b.onclick=()=>{services=services.includes(b.dataset.service)?services.filter(x=>x!==b.dataset.service):[...services,b.dataset.service];b.classList.toggle('selected')});
  document.getElementById('add-contact').onclick=()=>{sync();contacts.push({name:'',title:'',email:'',phone:'',roles:[]});render()};document.querySelectorAll('[data-remove-contact]').forEach(b=>b.onclick=()=>{sync();contacts.splice(+b.dataset.removeContact,1);render()});
  document.getElementById('add-address').onclick=()=>{sync();addresses.push({type:'office',name:'',line1:''});render()};document.querySelectorAll('[data-remove-address]').forEach(b=>b.onclick=()=>{sync();addresses.splice(+b.dataset.removeAddress,1);render()});
  document.getElementById('add-evidence').onclick=()=>{sync();evidence.push({type:'GENERAL_PHOTO',min:1,scope:'top_level_piece',when:'always'});render()};document.querySelectorAll('[data-remove-evidence]').forEach(b=>b.onclick=()=>{sync();evidence.splice(+b.dataset.removeEvidence,1);render()});
  document.getElementById('add-rate').onclick=()=>{sync();rates.push({charge:'',side:'sell',basis:'FLAT',rate:0,minimum:0,currency:'USD'});render()};document.querySelectorAll('[data-remove-rate]').forEach(b=>b.onclick=()=>{sync();rates.splice(+b.dataset.removeRate,1);render()});
  document.getElementById('entity-save').onclick=save;document.getElementById('entity-delete')?.addEventListener('click',remove);
 }
 async function save(){sync();const name=document.getElementById('ent-name').value.trim();if(!name)return alert('Name is required');const payload={name,code:document.getElementById('ent-code').value.trim()||null,email:document.getElementById('ent-email').value.trim()||null,phone:document.getElementById('ent-phone').value.trim()||null,roles,sop:{...sop,services,contacts:contacts.filter(x=>x.name||x.email||x.phone),addresses:addresses.filter(x=>x.name||x.line1),receiving:{...rec,receive_by:document.getElementById('receive-by').value,default_service:document.getElementById('default-service').value||null,require_weight:document.getElementById('sop-weight').checked,require_dimensions:document.getElementById('sop-dims').checked,require_serial_capture:document.getElementById('sop-serial').checked,required_documents:document.getElementById('sop-docs').value.split(',').map(x=>x.trim()).filter(Boolean),evidence},shipments:{...ship,require_po:document.getElementById('sop-po').checked},billing:{...bill,auto_charges:document.getElementById('sop-charges').value.split(',').map(x=>x.trim()).filter(Boolean)},rates:rates.filter(x=>x.charge),notes:document.getElementById('sop-notes').value.trim()}};let error;if(e.id)({error}=await supabase.from('entities').update(payload).eq('id',e.id));else{const organization_id=await org();({error}=await supabase.from('entities').insert({...payload,organization_id}))}if(error)return alert(error.message);openEntitiesModule()}
 async function remove(){if(!confirm(`Delete ${e.name}? Existing records will keep historical display data where available.`))return;const{error}=await supabase.from('entities').delete().eq('id',e.id);if(error)return alert(error.message);openEntitiesModule()}
 render();
}
window.nodaraEntities=openEntitiesModule;
