import { supabase } from './supabase-client.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const q=s=>document.querySelector(s);
function publicUrl(token){const u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('instruction',token);return u.toString()}
async function listRequests(shipmentId){const{data,error}=await supabase.from('instruction_requests').select('id,request_number,status,recipient_name,recipient_email,current_version,created_at,submitted_at,secure_token').eq('source_type','SHIPMENT').eq('source_id',shipmentId).order('created_at',{ascending:false});if(error)throw error;return data||[]}

async function ensureInstructionPdfLib(){if(window.jspdf?.jsPDF)return window.jspdf.jsPDF;await new Promise((ok,bad)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/jspdf@2.5.2/dist/jspdf.umd.min.js';s.onload=ok;s.onerror=bad;document.head.appendChild(s)});return window.jspdf.jsPDF}
async function finalizeInstructionDocument(submissionId,shipmentId){
 const{data:snap,error}=await supabase.rpc('nodara_freeze_instruction_snapshot',{p_submission_id:submissionId});if(error)throw error;
 const{data:x,error:xe}=await supabase.from('instruction_document_snapshots').select('*').eq('id',snap.snapshot_id).single();if(xe)throw xe;
 if(x.document_id)return x;
 const z=x.snapshot||{},p=z.payload||{},JS=await ensureInstructionPdfLib(),pdf=new JS({unit:'pt',format:'letter'});
 const left=48,right=564;let y=48;const line=(label,value)=>{pdf.setFont('helvetica','bold');pdf.setFontSize(8);pdf.setTextColor(95);pdf.text(label.toUpperCase(),left,y);pdf.setFont('helvetica','normal');pdf.setFontSize(10);pdf.setTextColor(20);const t=pdf.splitTextToSize(String(value||'—'),350);pdf.text(t,205,y);y+=Math.max(22,t.length*12+8)};
 pdf.setFont('helvetica','bold');pdf.setFontSize(17);pdf.setTextColor(15);pdf.text('NODARA',left,y);pdf.setFontSize(8);pdf.setTextColor(95);pdf.text('APPROVED SHIPPING INSTRUCTIONS',right,y,{align:'right'});y+=34;
 pdf.setFontSize(22);pdf.setTextColor(15);pdf.text(z.request_number||'Shipping Instructions',left,y);y+=17;pdf.setFont('helvetica','normal');pdf.setFontSize(9);pdf.setTextColor(95);pdf.text('Immutable approved instruction snapshot · Version '+z.version,left,y);y+=28;pdf.setDrawColor(210);pdf.line(left,y,right,y);y+=22;
 [['Structure',p.structure],['Shipper',p.shipper_name],['Consignee',p.consignee_name],['Notify',p.notify_name],['House shipper',p.house_shipper],['House consignee',p.house_consignee],['House notify',p.house_notify],['Air freight',p.freight_terms],['Other charges',p.other_charges],['Declared value for carriage',p.declared_carriage],['Declared value for customs',p.declared_customs],['Pieces',p.pieces],['Gross weight',p.weight],['Commodity / nature of goods',p.commodity],['Marks / handling',p.handling]].filter(([,v])=>v!==undefined&&v!=='').forEach(([a,b])=>line(a,b));
 if(y>650){pdf.addPage();y=55}pdf.setDrawColor(210);pdf.line(left,y,right,y);y+=20;line('Certified by',[z.submitted_by_name,z.submitted_by_title].filter(Boolean).join(' · '));line('Signature',z.signature_name);line('Submitted',z.submitted_at?new Date(z.submitted_at).toLocaleString():'');line('Approved',z.approved_at?new Date(z.approved_at).toLocaleString():'');pdf.setFontSize(7);pdf.setTextColor(110);pdf.text('Snapshot '+x.content_hash+' · Source submission '+z.submission_id,left,744);
 const blob=pdf.output('blob'),file=new File([blob],`Shipping_Instructions_${z.request_number}_v${z.version}.pdf`,{type:'application/pdf'});
 const{data:mem}=await supabase.from('organization_members').select('organization_id').limit(1).single(),oid=mem.organization_id,path=`${oid}/canonical/${crypto.randomUUID()}_${file.name}`;
 const{error:up}=await supabase.storage.from('nodara-documents').upload(path,file,{contentType:'application/pdf'});if(up)throw up;
 const{data:doc,error:de}=await supabase.from('documents').insert({organization_id:oid,document_type:'SHIPPING_INSTRUCTIONS',storage_path:path,file_name:file.name,mime_type:'application/pdf',display_name:`Shipping Instructions · ${z.request_number} · v${z.version}`,category:'CUSTOMER',source:'GENERATED',status:'ACTIVE',metadata:{instruction_snapshot_id:x.id,instruction_submission_id:z.submission_id,version:z.version,content_hash:x.content_hash,immutable_source:true},provenance:{surface:'INSTRUCTIONS_ENGINE',shipment_id:shipmentId}}).select().single();if(de){await supabase.storage.from('nodara-documents').remove([path]);throw de}
 const{error:le}=await supabase.rpc('nodara_link_instruction_document',{p_snapshot_id:x.id,p_document_id:doc.id});if(le)throw le;return{...x,document_id:doc.id}
}

async function openReview(root,requestId){
 const panel=root.querySelector('[data-panel]');panel.innerHTML='<div class="ix-loading">Loading submission…</div>';
 try{
  const [{data:req,error:re},{data:ship,error:se}]=await Promise.all([
   supabase.from('instruction_requests').select('*,instruction_submissions(*)').eq('id',requestId).single(),
   supabase.from('shipments').select('*').eq('id',root.dataset.shipmentId).single()
  ]);if(re)throw re;if(se)throw se;
  const sub=(req.instruction_submissions||[]).sort((a,b)=>b.version-a.version)[0];if(!sub){panel.innerHTML='<div class="notice">No submission has been received yet.</div>';return}
  const p=sub.payload||{},meta=ship.metadata||{},structure=meta.document_structure||'UNDECIDED';
  const fields=[
   ['structure','Document structure',structure,p.structure],
   ['shipper_name','Shipper',ship.shipper_name,p.shipper_name],
   ['consignee_name','Consignee',ship.consignee_name,p.consignee_name],
   ['pieces','Pieces',ship.pieces,p.pieces],
   ['weight','Gross weight',ship.weight,p.weight],
   ['freight_terms','Air freight terms',meta.freight_terms,p.freight_terms],
   ['other_charges','Other charges',meta.other_charges_terms,p.other_charges],
   ['declared_carriage','Declared value / carriage',meta.declared_value_carriage,p.declared_carriage],
   ['declared_customs','Declared value / customs',meta.declared_value_customs,p.declared_customs],
   ['commodity','Commodity',meta.commodity_description,p.commodity],
   ['handling','Handling instructions',meta.handling_instructions,p.handling]
  ];
  if(['HOUSE','CONSOLIDATION'].includes(p.structure)){fields.push(['house_shipper','House shipper','—',p.house_shipper],['house_consignee','House consignee','—',p.house_consignee],['house_notify','House notify','—',p.house_notify])}
  panel.innerHTML=`<div class="ix-review-head"><button data-back>‹ Instructions</button><div><small>SUBMISSION REVIEW · VERSION ${sub.version}</small><h2>${esc(req.request_number)}</h2><p>Submitted by ${esc(sub.submitted_by_name||'Customer')} ${sub.submitted_by_title?'· '+esc(sub.submitted_by_title):''}</p></div><span class="ix-review-state">${esc(sub.review_status)}</span></div>
  <div class="ix-review-summary"><div><small>CERTIFICATION</small><b>${sub.certification?'✓ Certified':'Not certified'}</b></div><div><small>SIGNATURE</small><b>${esc(sub.signature_name||'—')}</b></div><div><small>SUBMITTED</small><b>${new Date(sub.submitted_at).toLocaleString()}</b></div></div>
  <section class="ix-compare"><header><div></div><b>Current shipment</b><b>Customer instruction</b><span>Apply</span></header>
  ${fields.map(([key,label,current,incoming])=>{const changed=String(current??'')!==String(incoming??'');return `<article class="${changed?'changed':''}"><div><b>${label}</b>${changed?'<small>Changed</small>':'<small>Same</small>'}</div><p>${esc(current??'—')}</p><p>${esc(incoming??'—')}</p><label><input type="checkbox" data-apply="${key}" ${changed&&incoming!==undefined&&incoming!==''?'checked':''} ${incoming===undefined||incoming===''?'disabled':''}></label></article>`}).join('')}</section>
  <div class="ix-review-actions"><label><span>Review note</span><textarea data-review-note rows="2" placeholder="Optional internal/revision note"></textarea></label><div><button data-revision>Request revision</button><button class="primary" data-approve>Approve selected & apply →</button></div></div>`;
  panel.querySelector('[data-back]').onclick=()=>renderInstructions(root);
  panel.querySelector('[data-approve]').onclick=async()=>{const selected=[...panel.querySelectorAll('[data-apply]:checked')].map(x=>x.dataset.apply);if(!selected.length&&!confirm('Approve this submission without applying any fields?'))return;const b=panel.querySelector('[data-approve]');b.disabled=true;b.textContent='Applying…';const{error}=await supabase.rpc('nodara_apply_instruction_submission',{p_submission_id:sub.id,p_fields:selected,p_review_notes:panel.querySelector('[data-review-note]').value.trim()||null});if(error){b.disabled=false;b.textContent='Approve selected & apply →';return alert(error.message)}try{await finalizeInstructionDocument(sub.id,root.dataset.shipmentId)}catch(e){console.warn('Instruction PDF finalization',e);alert('Instructions were approved, but the PDF snapshot could not be finalized: '+e.message)}await renderInstructions(root)};
  panel.querySelector('[data-revision]').onclick=async()=>{const note=panel.querySelector('[data-review-note]').value.trim();if(!note)return alert('Add a revision note so the customer knows what needs to change.');const{error}=await supabase.rpc('nodara_request_instruction_revision',{p_submission_id:sub.id,p_notes:note});if(error)return alert(error.message);await renderInstructions(root)};
 }catch(e){panel.innerHTML=`<div class="notice warning">${esc(e.message)}</div>`}
}
async function renderInstructions(root){
 const id=root.dataset.shipmentId,panel=root.querySelector('[data-panel]');if(!panel)return;
 panel.innerHTML='<div class="ix-loading">Loading instructions…</div>';
 try{const rows=await listRequests(id);panel.innerHTML=`<div class="ix-head"><div><small>EXTERNAL COLLABORATION</small><h2>Instructions</h2><p>Request structured instructions without giving outside parties access to NODARA.</p></div><button class="primary" data-ix-new>+ Request instructions</button></div>
 <div class="ix-template-strip"><button data-ix-new><i>✈</i><span><b>Air Shipping Instructions</b><small>Structure · parties · cargo · prepaid/collect · certification</small></span><em>Request →</em></button><button disabled><i>▤</i><span><b>SLI</b><small>Reusable engine template</small></span><em>Next</em></button><button disabled><i>◇</i><span><b>FTZ Instructions</b><small>Admission / transfer / transit-to-zone</small></span><em>Next</em></button></div>
 <section class="ix-list"><div class="ix-list-head"><b>Request history</b><span>${rows.length} total</span></div>${rows.length?rows.map(r=>`<article><div class="ix-status ${r.status.toLowerCase()}"></div><div><b>${esc(r.request_number)}</b><span>${esc(r.recipient_name||r.recipient_email||'Recipient not named')}</span><small>${new Date(r.created_at).toLocaleString()}</small></div><div><strong>${esc(r.status.replaceAll('_',' '))}</strong><small>Version ${r.current_version||0}</small></div><button data-copy="${r.secure_token}">Share link</button>${['SUBMITTED','REVISION_REQUESTED','APPROVED'].includes(r.status)?`<button class="primary" data-review="${r.id}">${r.status==='APPROVED'?'View':'Review'}</button>`:''}</article>`).join(''):'<div class="ix-empty">No instruction requests yet.<br><span>Start with Air Shipping Instructions.</span></div>'}</section>`;
 panel.querySelectorAll('[data-ix-new]').forEach(b=>b.onclick=()=>openRequestModal(id,()=>renderInstructions(root)));
 panel.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText(publicUrl(b.dataset.copy));b.textContent='Copied ✓';setTimeout(()=>b.textContent='Share link',1500)});panel.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>openReview(root,b.dataset.review));
 }catch(e){panel.innerHTML=`<div class="notice warning">${esc(e.message)}</div>`}
}
function modalHtml(){return `<div class="ix-modal-backdrop" data-ix-modal><section class="ix-modal"><header><div><small>REQUEST</small><h2>Air Shipping Instructions</h2></div><button data-close>×</button></header><p class="muted">The customer receives a secure form. Shipment facts are prefilled; their submission is reviewed before anything changes the canonical record.</p><label><span>Recipient name</span><input data-name placeholder="Contact name"></label><label><span>Email</span><input data-email type="email" placeholder="name@company.com"></label><label><span>Message</span><textarea data-message rows="3" placeholder="Please complete the final shipping instructions for this shipment."></textarea></label><div class="ix-prefill"><b>Prefill from shipment</b><span>✓ Route</span><span>✓ Shipment number</span><span>✓ Existing cargo summary</span><span>✓ Customer reference</span></div><footer><button data-close>Cancel</button><button class="primary" data-create>Create secure request</button></footer></section></div>`}
async function openRequestModal(id,onDone){document.body.insertAdjacentHTML('beforeend',modalHtml());const m=q('[data-ix-modal]');m.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>m.remove());m.querySelector('[data-create]').onclick=async()=>{const btn=m.querySelector('[data-create]');btn.disabled=true;btn.textContent='Creating…';const{data,error}=await supabase.rpc('nodara_create_instruction_request',{p_source_type:'SHIPMENT',p_source_id:id,p_template_code:'AIR_SHIPPING_INSTRUCTIONS',p_recipient_name:m.querySelector('[data-name]').value.trim()||null,p_recipient_email:m.querySelector('[data-email]').value.trim()||null,p_message:m.querySelector('[data-message]').value.trim()||null});if(error){btn.disabled=false;btn.textContent='Create secure request';return alert(error.message)}const link=publicUrl(data.secure_token);m.querySelector('.ix-modal').innerHTML=`<div class="ix-created"><i>✓</i><small>REQUEST CREATED</small><h2>${esc(data.request_number)}</h2><p>The secure customer form is ready. Email delivery can be connected later; for now the link is ready to share.</p><input value="${esc(link)}" readonly data-link><div><button data-copylink>Copy link</button><button class="primary" data-done>Done</button></div></div>`;m.querySelector('[data-copylink]').onclick=async()=>{await navigator.clipboard.writeText(link);m.querySelector('[data-copylink]').textContent='Copied ✓'};m.querySelector('[data-done]').onclick=()=>{m.remove();onDone?.()}}}
function installShipment(root){if(root.dataset.ixInstalled)return;root.dataset.ixInstalled='1';const tabs=root.querySelector('.shx-tabs');if(tabs&&!tabs.querySelector('[data-tab="instructions"]')){const docs=tabs.querySelector('[data-tab="documents"]'),b=document.createElement('button');b.className='txw-tab';b.dataset.tab='instructions';b.textContent='Instructions';b.onclick=()=>{tabs.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));renderInstructions(root)};tabs.insertBefore(b,docs)}
 const actions=root.querySelector('.shx-top-actions');if(actions&&!actions.querySelector('[data-ix-share]')){const b=document.createElement('button');b.dataset.ixShare='1';b.className='secondary';b.textContent='Share / Request';b.onclick=()=>openRequestModal(root.dataset.shipmentId,()=>{});actions.insertBefore(b,actions.lastElementChild)}
}
async function renderPublic(token){
 document.body.classList.add('ix-public-mode');const main=q('#main');if(!main)return;
 main.innerHTML='<div class="ix-public-loading">Loading secure instructions…</div>';
 const{data,error}=await supabase.rpc('nodara_public_instruction',{p_token:token});if(error||!data){main.innerHTML='<div class="ix-public-error"><h1>Link unavailable</h1><p>This instruction request is invalid, expired, or no longer available.</p></div>';return}
 const p=data.prefill||{};main.innerHTML=`<main class="ix-public"><header><div class="ix-brand">N<span>°</span></div><div><small>AIR SHIPPING INSTRUCTIONS</small><b>${esc(data.request_number)}</b></div></header><section class="ix-public-hero"><small>${esc(p.shipment_number||'SHIPMENT')}</small><h1>${esc(p.origin_code||'Origin')} <i>→</i> ${esc(p.destination_code||'Destination')}</h1><p>Please provide the final instructions for this shipment. You do not need a NODARA account.</p></section><form data-public-form>
 <section><div class="ix-step">01</div><h2>Document structure</h2><p>How should this shipment be documented?</p><div class="ix-choice-grid">
 ${[['UNDECIDED','Not sure','Let the forwarder determine the final structure'],['MASTER_ONLY','Straight / Master only','Carrier document only'],['HOUSE','Master + House','One master and one house document'],['CONSOLIDATION','Consolidation','One master with multiple houses']].map((x,i)=>`<label class="ix-choice"><input type="radio" name="structure" value="${x[0]}" ${i===0?'checked':''}><span><b>${x[1]}</b><small>${x[2]}</small></span></label>`).join('')}</div></section>
 <section><div class="ix-step">02</div><h2>Parties</h2><div class="ix-fields"><label><span>Shipper</span><input name="shipper_name"></label><label><span>Consignee</span><input name="consignee_name"></label><label><span>Notify party</span><input name="notify_name"></label></div><div data-house-fields hidden><h3>House parties</h3><div class="ix-fields"><label><span>House shipper</span><input name="house_shipper"></label><label><span>House consignee</span><input name="house_consignee"></label><label><span>House notify</span><input name="house_notify"></label></div></div></section>
 <section><div class="ix-step">03</div><h2>Freight & document instructions</h2><div class="ix-fields"><label><span>Air freight</span><select name="freight_terms"><option>PREPAID</option><option>COLLECT</option></select></label><label><span>Other charges</span><select name="other_charges"><option>PREPAID</option><option>COLLECT</option></select></label><label><span>Declared value for carriage</span><input name="declared_carriage" placeholder="NVD"></label><label><span>Declared value for customs</span><input name="declared_customs" placeholder="NCV"></label></div></section>
 <section><div class="ix-step">04</div><h2>Cargo</h2><div class="ix-fields"><label class="wide"><span>Commodity / nature and quantity of goods</span><textarea name="commodity" rows="4"></textarea></label><label><span>Pieces</span><input name="pieces" type="number" value="${esc(p.pieces||'')}"></label><label><span>Gross weight</span><input name="weight" value="${esc(p.weight||'')}"></label><label class="wide"><span>Marks, numbers & special handling</span><textarea name="handling" rows="3"></textarea></label></div></section>
 <section><div class="ix-step">05</div><h2>Certification</h2><label class="ix-cert"><input type="checkbox" name="certification" required><span>I certify that the information provided is complete and accurate and authorize preparation of transportation documents based on these instructions.</span></label><div class="ix-fields"><label><span>Name</span><input name="submitted_by" required></label><label><span>Title</span><input name="title"></label><label class="wide"><span>Signature (type full name)</span><input name="signature" required></label></div></section><button class="primary ix-submit" type="submit">Submit Shipping Instructions →</button></form></main>`;
 const f=main.querySelector('[data-public-form]'),house=main.querySelector('[data-house-fields]');f.structure.forEach(r=>r.onchange=()=>house.hidden=!['HOUSE','CONSOLIDATION'].includes(f.structure.value));
 f.onsubmit=async e=>{e.preventDefault();const btn=f.querySelector('.ix-submit');btn.disabled=true;btn.textContent='Submitting…';const fd=new FormData(f),payload=Object.fromEntries(fd.entries());delete payload.certification;delete payload.submitted_by;delete payload.title;delete payload.signature;const{data:out,error:err}=await supabase.rpc('nodara_submit_public_instruction',{p_token:token,p_payload:payload,p_name:fd.get('submitted_by'),p_title:fd.get('title')||null,p_certification:true,p_signature_name:fd.get('signature')});if(err){btn.disabled=false;btn.textContent='Submit Shipping Instructions →';return alert(err.message)}main.innerHTML=`<div class="ix-public-success"><i>✓</i><small>SUBMITTED</small><h1>Instructions received</h1><p>${esc(out.request_number)} · Version ${out.version}</p><span>You may close this page.</span></div>`}
}
const token=new URLSearchParams(location.search).get('instruction');if(token)renderPublic(token);else{const obs=new MutationObserver(()=>document.querySelectorAll('.shipment-canonical').forEach(installShipment));obs.observe(document.documentElement,{childList:true,subtree:true});document.querySelectorAll('.shipment-canonical').forEach(installShipment)}
