import { supabase } from './supabase-client.js';
const main=document.getElementById('main');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let view='item',rows=[];
async function load(){
 const [cargo,items,wrs,locs,allocs]=await Promise.all([
  supabase.from('cargo_units').select('id,parent_id,job_id,inventory_item_id,package_type,quantity,uom,description,status,sku,part_number,serial_number,lot_number,uin,handling_unit_code,warehouse_location_id').order('created_at',{ascending:false}).limit(10000),
  supabase.from('inventory_items').select('id,part_number,sku,description,base_uom,metadata,owner_entity_id').limit(5000),
  supabase.from('warehouse_receipts').select('id,job_id,receipt_number,status').limit(5000),
  supabase.from('warehouse_locations').select('id,code,name,zone').limit(5000),
  supabase.rpc('inventory_allocation_snapshot')
 ]);
 for(const x of[cargo,items,wrs,locs])if(x.error)throw x.error;
 const allocationError=allocs.error;const allocBy=new Map((allocationError?[]:allocs.data||[]).map(x=>[x.cargo_unit_id,Number(x.allocated_quantity||0)]));
 const itemBy=new Map((items.data||[]).map(x=>[x.id,x])),wrByJob=new Map((wrs.data||[]).map(x=>[x.job_id,x])),locBy=new Map((locs.data||[]).map(x=>[x.id,x]));
 const byId=new Map((cargo.data||[]).map(x=>[x.id,x]));
 const rootOf=n=>{let x=n,guard=0;while(x?.parent_id&&byId.has(x.parent_id)&&guard++<12)x=byId.get(x.parent_id);return x||n};
 rows=(cargo.data||[]).filter(x=>x.inventory_item_id||x.sku||x.part_number).filter(x=>!['RELEASED','SHIPPED','DELETED','VOID','CANCELLED','DEPLETED'].includes(String(x.status||'').toUpperCase())&&Number(x.quantity||0)>0).map(x=>{const root=rootOf(x),it=itemBy.get(x.inventory_item_id)||{},wr=wrByJob.get(x.job_id)||{},loc=locBy.get(root.warehouse_location_id||x.warehouse_location_id)||{},onHand=Number(x.quantity||0),allocated=Math.min(onHand,allocBy.get(x.id)||0);return{id:x.id,root_id:root.id,inventory_item_id:x.inventory_item_id,owner_entity_id:it.owner_entity_id||null,part_number:x.part_number||it.part_number||'',sku:x.sku||it.sku||'',description:x.description||it.description||'',quantity:onHand,on_hand:onHand,allocated,available:Math.max(0,onHand-allocated),uom:x.uom||it.base_uom||'EA',status:x.status||'',wr_number:wr.receipt_number||'',location:loc.code||'',location_name:loc.name||'',zone:loc.zone||'',package_type:root.package_type||'',handling_unit:root.uin||root.handling_unit_code||'',lot:x.lot_number||'',serial:x.serial_number||''}});
 return rows;
}
function key(r){if(view==='location')return r.location||'Unassigned';if(view==='wr')return r.wr_number||'No WR';if(view==='handling')return r.handling_unit||r.package_type||'Unidentified HU';return r.part_number||r.sku||r.description||'Unidentified item'}
function aggregate(list){const m=new Map();for(const r of list){const k=key(r);if(!m.has(k))m.set(k,{key:k,on_hand:0,allocated:0,available:0,uoms:new Set(),lines:[],locations:new Set(),wrs:new Set(),items:new Set(),hus:new Set()});const g=m.get(k);g.on_hand+=r.on_hand;g.allocated+=r.allocated;g.available+=r.available;g.uoms.add(r.uom);g.lines.push(r);if(r.location)g.locations.add(r.location);if(r.wr_number)g.wrs.add(r.wr_number);if(r.part_number||r.sku)g.items.add(r.part_number||r.sku);if(r.handling_unit)g.hus.add(r.handling_unit)}return [...m.values()]}
function row(g,i){const sub=view==='item'?`${g.locations.size} location${g.locations.size===1?'':'s'} · ${g.wrs.size} WR${g.wrs.size===1?'':'s'} · ${g.hus.size} handling unit${g.hus.size===1?'':'s'}`:view==='location'?`${g.items.size} item${g.items.size===1?'':'s'} · ${g.wrs.size} WR${g.wrs.size===1?'':'s'}`:view==='wr'?`${g.items.size} item${g.items.size===1?'':'s'} · ${g.locations.size} location${g.locations.size===1?'':'s'}`:`${g.items.size} item${g.items.size===1?'':'s'} · ${g.locations.size} location${g.locations.size===1?'':'s'} · ${g.wrs.size} WR${g.wrs.size===1?'':'s'}`;const uom=g.uoms.size===1?[...g.uoms][0]:'';return `<button class="inventory-stock-row" data-ledger-group="${i}"><div class="inventory-stock-main"><div class="inventory-stock-icon">▦</div><div><b>${esc(g.key)}</b><span>${esc(sub)}</span><small>${[...g.locations].slice(0,3).map(esc).join(' · ')}</small></div></div><div class="inventory-stock-numbers"><div><span>Available</span><strong>${g.available} ${esc(uom)}</strong></div><div><span>On hand</span><b>${g.on_hand}</b></div><div><span>Allocated</span><b>${g.allocated}</b></div><div><span>Records</span><b>${g.lines.length}</b></div></div><i>›</i></button>`}
function renderGroups(data){const groups=aggregate(data),el=document.getElementById('inventory-ledger-list');if(!el)return;el.innerHTML=groups.length?`<div class="inventory-stock-list">${groups.map(row).join('')}</div>`:'<div class="empty compact">No inventory matches this view.</div>';document.querySelectorAll('[data-ledger-group]').forEach(b=>b.onclick=()=>detail(groups[Number(b.dataset.ledgerGroup)]))}
function detail(g){main.innerHTML=`<div class="record-commandbar"><button class="secondary compact-btn" id="ledger-back">‹ Inventory</button>${view==='item'&&g.lines[0]?.inventory_item_id?'<button class="secondary compact-btn" id="ledger-edit-part">Edit Part Attributes</button>':''}</div><div class="eyebrow">Inventory · ${view==='item'?'Item':view==='location'?'Location':view==='wr'?'Warehouse Receipt':'Handling Unit'}</div><h1 class="title">${esc(g.key)}</h1><div class="inventory-item-summary"><div><span>Available</span><strong>${g.available}</strong></div><div><span>On hand</span><strong>${g.on_hand}</strong></div><div><span>Allocated</span><strong>${g.allocated}</strong></div><div><span>Records</span><strong>${g.lines.length}</strong></div></div><section class="record-section"><div class="section-heading"><h3>Inventory detail</h3><span>Tap any row for Move, Adjust, Count, Split, Hold, Release or History</span></div><div class="location-table"><div class="location-row location-head"><span>Part / SKU</span><span>Availability</span><span>Location</span><span>WR</span><span>Handling Unit</span><span>Lot / Serial</span></div>${g.lines.map(r=>`<button class="location-row" data-ledger-node="${r.id}"><span><b>${esc(r.part_number||r.sku||'—')}</b><small>${esc(r.description||'')}</small></span><span><b>${r.available} ${esc(r.uom)} available</b><small>${r.on_hand} on hand · ${r.allocated} allocated · ${esc(r.status)}</small></span><span>${esc(r.location||'—')}</span><span>${esc(r.wr_number||'—')}</span><span><b>${esc(r.handling_unit||r.package_type||'—')}</b></span><span>${esc([r.lot&&'LOT '+r.lot,r.serial&&'SN '+r.serial].filter(Boolean).join(' · ')||'—')}</span></button>`).join('')}</div></section>`;document.getElementById('ledger-back').onclick=open;document.getElementById('ledger-edit-part')?.addEventListener('click',()=>window.nodaraItemMasterEdit?.(g.lines[0].inventory_item_id));}
export async function open(){window.nodaraSetActive?.('inventory');main.innerHTML='<div class="eyebrow">Warehouse · Inventory</div><h1 class="title">Inventory</h1><p class="muted">Loading inventory ledger…</p>';try{await load();const onHand=rows.reduce((a,r)=>a+r.on_hand,0),allocated=rows.reduce((a,r)=>a+r.allocated,0),available=rows.reduce((a,r)=>a+r.available,0),locations=new Set(rows.map(r=>r.location).filter(Boolean)).size,wrs=new Set(rows.map(r=>r.wr_number).filter(Boolean)).size;main.innerHTML=`<div class="inventory-workspace-head"><div><div class="eyebrow">Warehouse</div><h1 class="title">Inventory</h1><p class="muted">One live ledger. Available stock already excludes cargo committed to open releases.</p></div><div class="context-actions"><button class="secondary compact-btn" id="inv-new-part">＋ New Part</button></div></div><div class="inventory-kpi-grid"><div><span>Available</span><strong>${available}</strong><small>free to allocate</small></div><div><span>On Hand</span><strong>${onHand}</strong><small>physically in warehouse</small></div><div><span>Allocated</span><strong>${allocated}</strong><small>committed to CRs</small></div><div><span>Locations</span><strong>${locations}</strong><small>with tracked stock</small></div><div><span>WRs</span><strong>${wrs}</strong><small>source receipts</small></div></div><div class="record-tabs inventory-ledger-tabs"><button data-ledger-view="item" class="${view==='item'?'active':''}">By Item</button><button data-ledger-view="location" class="${view==='location'?'active':''}">By Location</button><button data-ledger-view="wr" class="${view==='wr'?'active':''}">By WR</button><button data-ledger-view="handling" class="${view==='handling'?'active':''}">By Handling Unit</button></div><div class="inventory-actionbar"><div><b>${view==='item'?'Inventory by Item':view==='location'?'Inventory by Location':view==='wr'?'Inventory by Warehouse Receipt':'Inventory by Handling Unit'}</b><small>Search part, SKU, WR, location, UIN, lot or serial.</small></div><div class="inventory-searchbox"><span>⌕</span><input id="inventory-ledger-search" placeholder="Search inventory…"></div></div><div id="inventory-ledger-list"></div>`;renderGroups(rows);document.querySelectorAll('[data-ledger-view]').forEach(b=>b.onclick=()=>{view=b.dataset.ledgerView;open()});document.getElementById('inventory-ledger-search').oninput=e=>{const q=e.target.value.trim().toLowerCase();const f=!q?rows:rows.filter(r=>[r.part_number,r.sku,r.description,r.wr_number,r.location,r.handling_unit,r.lot,r.serial,r.status].some(v=>String(v||'').toLowerCase().includes(q)));renderGroups(f)};document.getElementById('inv-new-part').onclick=()=>window.nodaraItemMasterNew?.()}catch(e){main.innerHTML=`<div class="eyebrow">Warehouse</div><h1 class="title">Inventory</h1><div class="notice warning">${esc(e.message)}</div>`}}
window.nodaraInventoryLedger={open};
