import { supabase } from './supabase-client.js';
export async function getInventorySnapshot(){const{data,error}=await supabase.rpc('inventory_snapshot');if(error)throw error;return data||[]}
export async function findExpectedReceipts(search){const q=String(search||'').trim();if(!q)return[];const{data:refs,error:refError}=await supabase.from('expected_receipt_references').select('expected_receipt_id,reference_type,reference_value').ilike('reference_value',`%${q}%`).limit(20);if(refError)throw refError;const ids=[...new Set((refs||[]).map(r=>r.expected_receipt_id))];if(!ids.length)return[];const{data,error}=await supabase.from('expected_receipts').select('*').in('id',ids).limit(20);if(error)throw error;return data||[]}
export async function findInventory(search){const q=String(search||'').trim().toLowerCase(),rows=await getInventorySnapshot();if(!q)return rows;return rows.filter(r=>[r.item_key,r.part_number,r.sku,r.description].filter(Boolean).some(v=>String(v).toLowerCase().includes(q)))}
export async function createWarehouseReceiptTree(input={}){const{data,error}=await supabase.rpc('create_warehouse_receipt_tree',{p_reference:input.reference||null,p_customer_name:input.customer||null,p_description:input.description||null,p_tree:input.tree||[]});if(error)throw error;return data}
export async function listEntities(search=''){let q=supabase.from('entities').select('id,organization_id,name,code,roles,email,phone').order('name').limit(50);if(String(search).trim())q=q.ilike('name',`%${String(search).trim()}%`);const{data,error}=await q;if(error)throw error;return data||[]}
export async function createEntity(input={}){const org=await getCurrentOrganizationId();const{data,error}=await supabase.from('entities').insert({organization_id:org,name:String(input.name||'').trim(),code:input.code||null,roles:input.roles?.length?input.roles:['customer'],email:input.email||null,phone:input.phone||null}).select().single();if(error)throw error;return data}
export async function listEntityItems(entityId){const{data,error}=await supabase.from('entity_item_profiles').select('id,entity_id,inventory_item_id,customer_part_number,customer_sku,description_override,commodity,hs_code,base_uom_override,default_weight_lb,default_length_in,default_width_in,default_height_in,dg,fragile,stackable,aliases,notes,inventory_items(id,sku,part_number,description,base_uom,serial_tracking,lot_tracking)').eq('entity_id',entityId).order('created_at');if(error)throw error;return data||[]}
export async function saveEntityItemProfile(entityId,input={}){let itemId=input.inventory_item_id||null;const org=input.organization_id||await getCurrentOrganizationId();if(!itemId){const{data:item,error:itemError}=await supabase.from('inventory_items').insert({organization_id:org,sku:input.sku||null,part_number:input.part_number||null,description:input.description||null,base_uom:input.base_uom||'EA',serial_tracking:!!input.serial_tracking,lot_tracking:!!input.lot_tracking}).select('id').single();if(itemError)throw itemError;itemId=item.id}const payload={organization_id:org,entity_id:entityId,inventory_item_id:itemId,customer_part_number:input.customer_part_number||null,customer_sku:input.customer_sku||null,description_override:input.description_override||null,commodity:input.commodity||null,hs_code:input.hs_code||null,base_uom_override:input.base_uom_override||null,default_weight_lb:input.default_weight_lb||null,default_length_in:input.default_length_in||null,default_width_in:input.default_width_in||null,default_height_in:input.default_height_in||null,dg:!!input.dg,fragile:!!input.fragile,stackable:input.stackable??null,aliases:input.aliases||[],notes:input.notes||null};const{data,error}=await supabase.from('entity_item_profiles').upsert(payload,{onConflict:'organization_id,entity_id,inventory_item_id'}).select().single();if(error)throw error;return data}
export async function getCurrentOrganizationId(){const{data,error}=await supabase.rpc('bootstrap_workspace',{p_name:'NODARA Workspace'});if(error)throw error;return data}
