import { supabase } from './supabase-client.js';
export async function getInventorySnapshot(){const{data,error}=await supabase.rpc('inventory_explorer_list');if(error)throw error;return data||[]}
export async function getInventoryItemCargoTree(inventoryItemId){const{data,error}=await supabase.rpc('inventory_item_cargo_tree',{p_inventory_item_id:inventoryItemId});if(error)throw error;return data||[]}
export async function updateCargoNode(id,input={}){const{data,error}=await supabase.rpc('update_cargo_node',{p_id:id,p_package_type:input.package_type||null,p_quantity:input.quantity??null,p_uom:input.uom||null,p_description:input.description??null,p_weight_lb:input.weight_lb??null,p_length_in:input.length_in??null,p_width_in:input.width_in??null,p_height_in:input.height_in??null,p_serial_number:input.serial_number??null,p_lot_number:input.lot_number??null,p_status:input.status||null,p_location_id:input.location_id||null,p_uin:input.uin||null,p_handling_unit_code:input.handling_unit_code||null});if(error)throw error;return data}
export async function createCargoChild(parentId,input={}){const{data,error}=await supabase.rpc('create_cargo_child',{p_parent_id:parentId,p_package_type:input.package_type||'PACKAGE',p_quantity:Number(input.quantity||1),p_uom:input.uom||null,p_description:input.description||null,p_weight_lb:input.weight_lb??null,p_length_in:input.length_in??null,p_width_in:input.width_in??null,p_height_in:input.height_in??null,p_sku:input.sku||null,p_part_number:input.part_number||null,p_serial_number:input.serial_number||null,p_lot_number:input.lot_number||null});if(error)throw error;return data}
export async function deleteCargoSubtree(id){const{data,error}=await supabase.rpc('delete_cargo_subtree',{p_id:id});if(error)throw error;return data}
export async function listCargo(search=''){const q=String(search||'').trim().toLowerCase();let query=supabase.from('cargo_units').select('id,parent_id,job_id,handling_unit_code,uin,description,package_type,quantity,uom,weight_lb,length_in,width_in,height_in,status,current_location_id,sku,part_number,serial_number,lot_number,inventory_item_id,locations(code),jobs(job_number,reference)').order('created_at',{ascending:false}).limit(250);if(!q)query=query.is('parent_id',null);const{data,error}=await query;if(error)throw error;const rows=(data||[]).map(r=>({...r,location_code:r.locations?.code||null,job_number:r.jobs?.job_number||null,job_reference:r.jobs?.reference||null}));if(!q)return rows;return rows.filter(r=>[r.uin,r.handling_unit_code,r.description,r.package_type,r.sku,r.part_number,r.serial_number,r.lot_number,r.location_code,r.job_number,r.job_reference].filter(Boolean).some(v=>String(v).toLowerCase().includes(q)))}
export async function getCargoNode(id){const{data,error}=await supabase.from('cargo_units').select('id,parent_id,job_id,handling_unit_code,uin,description,package_type,quantity,uom,weight_lb,length_in,width_in,height_in,status,current_location_id,sku,part_number,serial_number,lot_number,inventory_item_id,locations(code),jobs(job_number,reference)').eq('id',id).single();if(error)throw error;return{...data,location_code:data.locations?.code||null,job_number:data.jobs?.job_number||null,job_reference:data.jobs?.reference||null}}
export async function listCargoChildren(parentId){const{data,error}=await supabase.from('cargo_units').select('id,parent_id,job_id,handling_unit_code,uin,description,package_type,quantity,uom,weight_lb,length_in,width_in,height_in,status,current_location_id,sku,part_number,serial_number,lot_number,inventory_item_id,locations(code),jobs(job_number,reference)').eq('parent_id',parentId).order('created_at');if(error)throw error;return(data||[]).map(r=>({...r,location_code:r.locations?.code||null,job_number:r.jobs?.job_number||null,job_reference:r.jobs?.reference||null}))}
export async function findExpectedReceipts(search){const q=String(search||'').trim();if(!q)return[];const{data:refs,error:refError}=await supabase.from('expected_receipt_references').select('expected_receipt_id,reference_type,reference_value').ilike('reference_value',`%${q}%`).limit(20);if(refError)throw refError;const ids=[...new Set((refs||[]).map(r=>r.expected_receipt_id))];if(!ids.length)return[];const{data,error}=await supabase.from('expected_receipts').select('*').in('id',ids).limit(20);if(error)throw error;return data||[]}
export async function findInventory(search){const q=String(search||'').trim().toLowerCase(),rows=await getInventorySnapshot();if(!q)return rows;return rows.filter(r=>[r.item_key,r.part_number,r.sku,r.description].filter(Boolean).some(v=>String(v).toLowerCase().includes(q)))}
export async function createWarehouseReceiptTree(input={}){const{data,error}=await supabase.rpc('create_warehouse_receipt_tree',{p_reference:input.reference||null,p_customer_name:input.customer||null,p_description:input.description||null,p_tree:input.tree||[]});if(error)throw error;return data}
export async function listEntities(search=''){let q=supabase.from('entities').select('id,organization_id,name,code,roles,email,phone').order('name').limit(50);if(String(search).trim())q=q.ilike('name',`%${String(search).trim()}%`);const{data,error}=await q;if(error)throw error;return data||[]}
export async function createEntity(input={}){const org=await getCurrentOrganizationId();const{data,error}=await supabase.from('entities').insert({organization_id:org,name:String(input.name||'').trim(),code:input.code||null,roles:input.roles?.length?input.roles:['customer'],email:input.email||null,phone:input.phone||null}).select().single();if(error)throw error;return data}
export async function listEntityItems(entityId){const{data,error}=await supabase.from('entity_item_profiles').select('id,entity_id,inventory_item_id,customer_part_number,customer_sku,description_override,commodity,hs_code,base_uom_override,default_weight_lb,default_length_in,default_width_in,default_height_in,dg,fragile,stackable,aliases,notes,inventory_items(id,sku,part_number,description,base_uom,serial_tracking,lot_tracking)').eq('entity_id',entityId).order('created_at');if(error)throw error;return data||[]}
export async function saveEntityItemProfile(entityId,input={}){let itemId=input.inventory_item_id||null;const org=input.organization_id||await getCurrentOrganizationId();if(!itemId){const{data:item,error:itemError}=await supabase.from('inventory_items').insert({organization_id:org,sku:input.sku||null,part_number:input.part_number||null,description:input.description||null,base_uom:input.base_uom||'EA',serial_tracking:!!input.serial_tracking,lot_tracking:!!input.lot_tracking}).select('id').single();if(itemError)throw itemError;itemId=item.id}const payload={organization_id:org,entity_id:entityId,inventory_item_id:itemId,customer_part_number:input.customer_part_number||null,customer_sku:input.customer_sku||null,description_override:input.description_override||null,commodity:input.commodity||null,hs_code:input.hs_code||null,base_uom_override:input.base_uom_override||null,default_weight_lb:input.default_weight_lb||null,default_length_in:input.default_length_in||null,default_width_in:input.default_width_in||null,default_height_in:input.default_height_in||null,dg:!!input.dg,fragile:!!input.fragile,stackable:input.stackable??null,aliases:input.aliases||[],notes:input.notes||null};const{data,error}=await supabase.from('entity_item_profiles').upsert(payload,{onConflict:'organization_id,entity_id,inventory_item_id'}).select().single();if(error)throw error;return data}
export async function getCurrentOrganizationId(){const{data,error}=await supabase.rpc('bootstrap_workspace',{p_name:'NODARA Workspace'});if(error)throw error;return data}
