import { supabase } from './supabase-client.js';
import { mountDataView } from './data-view.js?v=20260902-0035';
import { openLocationPlanner } from './warehouse-location-planner.js?v=20260906-core1';
const main=document.getElementById('main');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const TYPES=['POSITION','FLOOR','STAGING','RECEIVING','SHIPPING','HOLD','QUARANTINE','DOCK','OTHER'];
let current=[];
async function org(){const{data,error}=await supabase.rpc('bootstrap_workspace',{p_name:'NODARA Workspace'});if(error)throw error;return data}
async function load(){const{data,error}=await supabase.from('warehouse_locations').select('id,organization_id,code,name,type,zone,facility,active,capacity,capacity_uom,ftz,bonded,restricted,notes,length_in,width_in,height_in,rack_code,bay_code,level_code,position_code,created_at').order('code').limit(5000);if(error)throw error;current=data||[];return current}
async function occupancy(ids){if(!ids.length)return new Map();const{data,error}=await supabase.from('cargo_units').select('warehouse_location_id,id,parent_id,quantity,status').in('warehouse_location_id',ids).limit(10000);if(error)throw error;const m=new Map();for(const c of data||[]){if(c.parent_id)continue;if(['RELEASED','DELETED','CANCELLED','VOID','SHIPPED'].includes(String(c.status||'').toUpperCase()))continue;m.set(c.warehouse_location_id,(m.get(c.warehouse_location_id)||0)+Math.max(1,Number(c.quantity||1)))}return m}
function edit(r=null){main.innerHTML=`<div class="eyebrow">Warehouse · Locations</div><div class="record-commandbar"><button class="secondary compact-btn" id="lc-back">‹ Locations</button></div><h1 class="title">${r?'Edit':'New'} Location</h1><section class="record-section"><div class="detail-grid"><div class="field"><label>Code *</label><input id="lc-code" value="${esc(r?.code||'')}"></div><div class="field"><label>Name</label><input id="lc-name" value="${esc(r?.name||'')}"></div><div class="field"><label>Type</label><select id="lc-type">${TYPES.map(t=>`<option ${r?.type===t?'selected':''}>${t}</option>`).join('')}</select></div><div class="field"><label>Facility</label><input id="lc-facility" value="${esc(r?.facility||'')}"></div><div class="field"><label>Zone / Area</label><input id="lc-zone" value="${esc(r?.zone||'')}"></div><div class="field"><label>Capacity</label><input id="lc-cap" type="number" min="0" step="1" value="${r?.capacity??1}"></div></div><div class="field"><label>Notes</label><textarea id="lc-notes" rows="4">${esc(r?.notes||'')}</textarea></div><div class="record-footer-actions"><button class="primary" id="lc-save">Save</button></div></section>`;document.getElementById('lc-back').onclick=openLocations;document.getElementById('lc-save').onclick=async()=>{const code=document.getElementById('lc-code').value.trim().toUpperCase();if(!code)return alert('Location code is required.');const payload={organization_id:await org(),code,name:document.getElementById('lc-name').value.trim()||code,type:document.getElementById('lc-type').value,facility:document.getElementById('lc-facility').value.trim()||null,zone:document.getElementById('lc-zone').value.trim()||null,capacity:Number(document.getElementById('lc-cap').value||0),capacity_uom:'POS',active:true,notes:document.getElementById('lc-notes').value.trim()||null};const q=r?supabase.from('warehouse_locations').update(payload).eq('id',r.id):supabase.from('warehouse_locations').insert(payload);const{error}=await q;if(error)return alert(error.message);await openLocations()}}
async function deleteSelected(rows){if(!rows.length)return;const ids=rows.map(r=>r.id),occ=await occupancy(ids),blocked=rows.filter(r=>(occ.get(r.id)||0)>0),allowed=rows.filter(r=>!blocked.includes(r));if(!allowed.length)return alert('Selected locations currently contain cargo and cannot be deleted.');if(!confirm(`Delete ${allowed.length} location${allowed.length===1?'':'s'}${blocked.length?`? ${blocked.length} occupied location${blocked.length===1?' is':'s are'} protected.`:'?'}`))return;const{error}=await supabase.from('warehouse_locations').delete().in('id',allowed.map(r=>r.id));if(error)alert(error.message);if(blocked.length)alert(`${blocked.length} occupied location${blocked.length===1?' was':'s were'} not deleted.`);await openLocations()}
export async function openLocations(){window.nodaraSetActive?.('warehouse_locations');main.innerHTML=`<div class="eyebrow">Warehouse</div><div class="location-titlebar"><div><h1 class="title">Locations</h1><p class="muted">Only assignable warehouse locations belong in this operational table.</p></div><div class="context-actions"><button class="secondary" id="lc-plan">▦ Plan / Generate</button><button class="primary" id="lc-new">＋ New Location</button></div></div><div id="lc-table"><p class="muted">Loading…</p></div>`;document.getElementById('lc-plan').onclick=openLocationPlanner;document.getElementById('lc-new').onclick=()=>edit();try{const rows=await load(),occ=await occupancy(rows.map(r=>r.id));const cols=[{key:'code',label:'Code',width:'180px',value:r=>r.code,render:r=>`<b>${esc(r.code)}</b><small>${esc(r.facility||'')}</small>`},{key:'type',label:'Type',width:'120px',value:r=>r.type},{key:'zone',label:'Zone',width:'120px',value:r=>r.zone||''},{key:'structure',label:'Structure',width:'190px',value:r=>[r.rack_code,r.bay_code,r.level_code,r.position_code].filter(Boolean).join(' / ')},{key:'capacity',label:'Capacity',width:'110px',value:r=>Number(r.capacity||0)},{key:'used',label:'Used',width:'100px',value:r=>Number(occ.get(r.id)||0)},{key:'available',label:'Available',width:'110px',value:r=>Math.max(0,Number(r.capacity||0)-Number(occ.get(r.id)||0))}];mountDataView({container:document.getElementById('lc-table'),key:'warehouse_locations_core',rows,columns:cols,defaultColumns:['code','type','zone','structure','capacity','used','available'],onOpen:id=>edit(rows.find(r=>r.id===id)),searchText:r=>[r.code,r.name,r.type,r.zone,r.facility,r.rack_code,r.bay_code,r.level_code,r.position_code].filter(Boolean).join(' '),selectionActions:[{label:'Open',single:true,handler:s=>edit(s[0])},{label:'Delete selected',danger:true,handler:deleteSelected}]})}catch(e){document.getElementById('lc-table').innerHTML=`<div class="notice warning">${esc(e.message)}</div>`}}
window.nodaraLocations=openLocations;
