import { supabase } from './supabase-client.js';
import { getCurrentOrganizationId } from './live-data.js';
import { requestTypes as types } from './operations-inbox-types.js?v=20261009-fast1';
import { quickCreate, quickTask, undoToast, bindSwipe } from './operations-inbox-fast.js?v=20261009-fast1';

const main=document.getElementById('main');
const stages={NEW:'New requests',WORKING:'Working',WAITING:'Waiting',READY_TO_BILL:'Ready to bill',COMPLETED:'Completed',CANCELLED:'Cancelled'};
const bills={REQUIRED:'Required',NOT_REQUIRED:'Not required',UNDECIDED:'To be determined'};
const groupKey=m=>m.mailbox_connection_id&&m.source_thread_id?`${m.mailbox_connection_id}:${m.source_thread_id}`:m.id;
const threadMessages=m=>messages.filter(x=>groupKey(x)===groupKey(m)).sort((a,b)=>new Date(a.received_at)-new Date(b.received_at));
const unreviewedCount=()=>new Set(messages.filter(m=>!m.deleted_at&&!m.reviewed_at).map(groupKey)).size;
let org,rows=[],messages=[],links=[],entities=[],view='queue',query='',typeFilter='',focusFilter='active',ownerFilter='',sortOrder='attention',loadVersion=0,loadedAt=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const opts=(items,value)=>Object.entries(items).map(([k,v])=>`<option value="${esc(k)}" ${k===value?'selected':''}>${esc(v)}</option>`).join('');
const when=v=>v?new Date(v).toLocaleString():'';
const localDate=v=>{if(!v)return '';const d=new Date(v);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
const late=r=>!['COMPLETED','CANCELLED'].includes(r.status)&&[r.due_at,r.follow_up_at].some(v=>v&&new Date(v)<=new Date());
const active=r=>!['COMPLETED','CANCELLED'].includes(r.status);
const billPending=r=>r.status!=='CANCELLED'&&r.billing_requirement==='REQUIRED'&&r.billing_status!=='BILLED';
const nextDate=r=>Math.min(...[r.due_at,r.follow_up_at].filter(Boolean).map(v=>new Date(v).getTime()),Infinity);
const today=r=>active(r)&&[r.due_at,r.follow_up_at].some(v=>v&&new Date(v).toDateString()===new Date().toDateString());
const focusTests={active,overdue:late,today,waiting:r=>r.status==='WAITING',billing:billPending,unassigned:r=>active(r)&&!r.owner_name?.trim(),all:()=>true};
const focusLabels={active:'Active work',overdue:'Due / follow-up',today:'Today',waiting:'Waiting',billing:'Billing pending',unassigned:'Unassigned',all:'All requests'};
function sortedRequests(list){return [...list].sort((a,b)=>sortOrder==='newest'?new Date(b.created_at||0)-new Date(a.created_at||0):sortOrder==='oldest'?new Date(a.created_at||0)-new Date(b.created_at||0):sortOrder==='due'?(nextDate(a)-nextDate(b)||a.request_number.localeCompare(b.request_number)):(Number(late(b))-Number(late(a))||nextDate(a)-nextDate(b)||new Date(b.created_at||0)-new Date(a.created_at||0)))}
function unreviewedQueue(){const seen=new Set();return [...messages].sort((a,b)=>new Date(b.received_at)-new Date(a.received_at)).filter(m=>!m.deleted_at&&!m.reviewed_at&&[m.subject,m.sender,m.body].join(' ').toLowerCase().includes(query.toLowerCase())).filter(m=>{const key=groupKey(m);if(seen.has(key))return false;seen.add(key);return true})}
const safeUrl=v=>{try{const u=new URL(v);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}};
const input=(label,id,value='',type='text')=>`<label class="oi-field">${label}<input id="${id}" type="${type}" value="${esc(value)}"></label>`;
const pick=(label,id,items,value)=>`<label class="oi-field">${label}<select id="${id}">${opts(items,value)}</select></label>`;
const textArea=(label,id,value='')=>`<label class="oi-field oi-wide">${label}<textarea id="${id}" rows="5">${esc(value)}</textarea></label>`;
const value=id=>document.getElementById(id)?.value.trim()||'';
const dateValue=id=>value(id)?new Date(value(id)).toISOString():null;
const notice=(msg)=>{const el=document.getElementById('oi-error');if(el){el.textContent=msg;el.hidden=false}else alert(msg)};
async function run(button,fn){if(button.disabled)return;button.disabled=true;try{await fn()}catch(e){notice(e.message||String(e));button.disabled=false}}
async function checked(q){const {data,error}=await q;if(error)throw error;return data}
async function allRows(table,sort='created_at',keys=['id']) {const result=[];for(let start=0;;start+=500){let q=supabase.from(table).select('*').eq('organization_id',org).order(sort,{ascending:false});for(const key of keys)q=q.order(key,{ascending:true});const batch=await checked(q.range(start,start+499));result.push(...batch);if(batch.length<500)return result}}
function customerOptions(id){return {'':'Select customer',...Object.fromEntries(entities.map(e=>[e.id,e.name]))}}
function header(title,actions=''){return `<div class="oi-head"><div><div class="eyebrow">Operations · Inbox</div><h1 class="title">${esc(title)}</h1></div><div class="oi-actions">${actions}</div></div><div id="oi-error" class="notice warning" role="alert" hidden></div>`}
async function reload(){org=await getCurrentOrganizationId();[rows,messages,links,entities]=await Promise.all([
 allRows('operations_requests'),allRows('operations_messages','received_at'),
 allRows('operations_request_messages','created_at',['request_id','message_id']),allRows('entities','name')]);loadedAt=new Date();}
export async function open(){window.nodaraSetActive?.('ops_inbox');const version=++loadVersion;main.innerHTML=header('Operations Inbox')+'<div class="card">Loading requests…</div>';try{await reload();if(version===loadVersion&&window.__nodaraRoute==='ops_inbox')render()}catch(e){if(version===loadVersion)notice(e.message)}}
function render(){
 const filtered=sortedRequests(rows.filter(r=>(!typeFilter||r.request_type===typeFilter)&&focusTests[focusFilter](r)&&(!ownerFilter||(ownerFilter==='__unassigned__'?!r.owner_name?.trim():r.owner_name===ownerFilter))&&[r.request_number,r.title,r.customer_name,r.owner_name,r.next_action,r.waiting_on,types[r.request_type]].join(' ').toLowerCase().includes(query.toLowerCase())));
 main.innerHTML=`<section class="oi-workspace">${header('Operations Inbox','<button class="secondary" id="oi-gmail">Gmail connection</button><button class="secondary" id="oi-capture">Capture email</button><button class="primary" id="oi-new">New request</button>')}
 <div class="oi-intro"><div><h2>Your operations, under control.</h2><p>Review incoming conversations. Give every request a next action, an owner and a follow-up.</p></div><button class="secondary" id="oi-refresh">Refresh inbox</button></div>
 <div class="oi-metrics">${['active','overdue','today','waiting','billing','unassigned'].map(k=>`<button data-focus="${k}" ${k==='overdue'?'id="oi-attention"':''} aria-pressed="${focusFilter===k}" class="${focusFilter===k?'selected':''}"><b>${rows.filter(focusTests[k]).length}</b><span>${focusLabels[k]}</span></button>`).join('')}</div>
 <div class="oi-toolbar"><div class="oi-view">${[['queue','Task queue'],['board','Board'],['list','List'],['unreviewed',`Unreviewed (${unreviewedCount()})`],['trash','Trash']].map(([k,l])=>`<button data-view="${k}" class="${view===k?'selected':''}">${l}</button>`).join('')}</div><input id="oi-search" aria-label="Search requests" placeholder="Search number, customer, request…" value="${esc(query)}"><select id="oi-filter" aria-label="Request type">${opts({'':'All request types',...types},typeFilter)}</select></div>
 <div class="oi-filterbar" ${view==='unreviewed'?'hidden':''}><select id="oi-focus" aria-label="Focus view">${opts(focusLabels,focusFilter)}</select><select id="oi-owner-filter" aria-label="Assigned owner">${opts({'':'All owners','__unassigned__':'Unassigned',...Object.fromEntries([...new Set(rows.map(r=>r.owner_name).filter(Boolean))].sort().map(n=>[n,n]))},ownerFilter)}</select><select id="oi-sort" aria-label="Sort requests">${opts({attention:'Needs attention first',due:'Next date first',newest:'Newest first',oldest:'Oldest first'},sortOrder)}</select><span>${filtered.length} request${filtered.length===1?'':'s'} · Refreshed ${esc(loadedAt?.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})||'now')}</span><button class="secondary" id="oi-clear">Clear filters</button></div>
 ${view==='unreviewed'?renderUnreviewed():view==='trash'?renderTrash():view==='queue'?renderQueue(filtered):view==='list'?renderList(filtered):renderBoard(filtered)}
 </section>`;
 document.getElementById('oi-gmail').onclick=async()=>{try{const mod=await import('./operations-inbox-review.js?v=20261009-fast1');await mod.openMailboxes({org,onBack:()=>open()})}catch(e){notice(e.message)}};document.getElementById('oi-new').onclick=()=>quickCreate({org,entities,onSaved:async()=>{await reload();render()}});document.getElementById('oi-capture').onclick=()=>capture();
 document.getElementById('oi-refresh').onclick=e=>run(e.target,async()=>{await reload();render()});
 main.querySelectorAll('[data-focus]').forEach(b=>b.onclick=()=>{focusFilter=b.dataset.focus;if(view==='unreviewed')view='board';render()});
 document.getElementById('oi-focus').onchange=e=>{focusFilter=e.target.value;render()};
 document.getElementById('oi-owner-filter').onchange=e=>{ownerFilter=e.target.value;render()};
 document.getElementById('oi-sort').onchange=e=>{sortOrder=e.target.value;render()};
 document.getElementById('oi-clear').onclick=()=>{query='';typeFilter='';ownerFilter='';focusFilter='active';sortOrder='attention';render()};
 main.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});
 document.getElementById('oi-filter').hidden=view==='unreviewed';document.getElementById('oi-filter').onchange=e=>{typeFilter=e.target.value;render()};
 document.getElementById('oi-search').oninput=e=>{query=e.target.value;const position=e.target.selectionStart;render();const input=document.getElementById('oi-search');input.focus();input.setSelectionRange(position,position)};
 main.querySelectorAll('[data-request]').forEach(b=>b.onclick=()=>detail(b.dataset.request));
 main.querySelectorAll('[data-quick-task]').forEach(b=>b.onclick=()=>fastTask(b.dataset.quickTask));
 main.querySelectorAll('[data-inline-status]').forEach(b=>b.onclick=()=>run(b,async()=>{const saved=await checked(supabase.from('operations_requests').update({status:b.dataset.inlineStatus}).eq('organization_id',org).eq('id',b.dataset.taskId).select().single());rows=rows.map(x=>x.id===saved.id?saved:x);render()}));
 main.querySelectorAll('[data-trash-message]').forEach(b=>b.onclick=()=>run(b,()=>trashMessage(b.dataset.trashMessage)));
 main.querySelectorAll('[data-restore-message]').forEach(b=>b.onclick=()=>run(b,()=>restoreMessage(b.dataset.restoreMessage)));
 bindSwipe(main,trashMessage);
 main.querySelectorAll('[data-message]').forEach(b=>b.onclick=()=>messageDetail(b.dataset.message));
 main.querySelectorAll('[data-stage]').forEach(column=>{column.ondragover=e=>e.preventDefault();column.ondrop=async e=>{e.preventDefault();const id=e.dataTransfer.getData('text/nodara-request');const r=rows.find(x=>x.id===id);if(!r||r.status===column.dataset.stage)return;try{await checked(supabase.from('operations_requests').update({status:column.dataset.stage}).eq('id',id).select().single());await open()}catch(e){notice(e.message)}}});
 main.querySelectorAll('[draggable]').forEach(card=>card.ondragstart=e=>e.dataTransfer.setData('text/nodara-request',card.dataset.request));
}
function card(r){const relatedIds=links.filter(l=>l.request_id===r.id).map(l=>l.message_id);const count=new Set(relatedIds.map(id=>groupKey(messages.find(m=>m.id===id)||{id}))).size;const unread=messages.filter(m=>relatedIds.includes(m.id)&&!m.reviewed_at).length;return `<button class="oi-card ${late(r)?'oi-overdue':''}" data-request="${r.id}" draggable="true"><div class="oi-card-top"><b>${esc(r.request_number)}</b><span>${esc(types[r.request_type])}</span></div><h3>${esc(r.title)}</h3><p>${esc(r.customer_name||'Customer not assigned')}</p><div class="oi-card-flags">${late(r)?'<span class="oi-flag oi-flag-warn">Due / follow-up overdue</span>':today(r)?'<span class="oi-flag">Due today</span>':''}${unread?`<span class="oi-flag">${unread} unreviewed email${unread===1?'':'s'}</span>`:''}${active(r)&&!r.next_action?.trim()?'<span class="oi-flag oi-flag-warn">Next action missing</span>':''}</div><div class="oi-next"><small>NEXT ACTION</small>${esc(r.next_action||'Set the next action')}</div>${r.status==='WAITING'?`<div class="oi-waiting">Waiting on ${esc(r.waiting_on||'— set who you need')}${!r.follow_up_at?' · Follow-up not scheduled':''}</div>`:''}<div class="oi-card-meta"><span>${esc(r.owner_name||'Unassigned')}</span><span>${count} conversation${count===1?'':'s'}</span></div>${r.due_at?`<div class="oi-time">Due ${esc(when(r.due_at))}</div>`:''}${r.follow_up_at?`<div class="oi-time">Follow up ${esc(when(r.follow_up_at))}</div>`:''}<div class="oi-billing">${r.billing_requirement==='NOT_REQUIRED'?'No billing':r.billing_requirement==='UNDECIDED'?'Billing undecided':r.billing_status==='BILLED'?'Billed':'Billing pending'}</div></button>`}
function renderBoard(list){return `<div class="oi-board">${Object.entries(stages).filter(([k])=>k!=='CANCELLED').map(([k,l])=>{const group=list.filter(r=>r.status===k);return `<section class="oi-column" data-stage="${k}"><h2>${l}<span>${group.length}</span></h2><div class="oi-stack">${group.map(card).join('')||'<div class="oi-empty">No requests</div>'}</div></section>`}).join('')}</div>`}
function renderList(list){return `<div class="oi-table-wrap"><table class="oi-table"><thead><tr><th>Request</th><th>Customer</th><th>Owner</th><th>Status</th><th>Next action</th><th>Due</th><th>Billing</th></tr></thead><tbody>${list.map(r=>`<tr><td><button data-request="${r.id}"><b>${esc(r.request_number)}</b><span>${esc(r.title)}</span></button></td><td>${esc(r.customer_name)}</td><td>${esc(r.owner_name||'Unassigned')}</td><td>${esc(stages[r.status])}</td><td>${esc(r.next_action)}</td><td>${esc(when(r.due_at))}</td><td>${esc(bills[r.billing_requirement])}</td></tr>`).join('')||'<tr><td colspan="7">No requests yet. Create a request or capture an email.</td></tr>'}</tbody></table></div>`}
function renderUnreviewed(){const list=unreviewedQueue();return `<div class="oi-message-list"><div class="oi-triage-intro"><h2>${list.length?'Start with one conversation.':'Your review queue is clear.'}</h2><p class="muted">${list.length?'Open an email, review its requests, then continue to the next conversation. New replies always return here.':'New captured emails will appear here after you refresh.'}</p></div>${list.map(m=>{const thread=threadMessages(m);const related=new Set(links.filter(l=>thread.some(x=>x.id===l.message_id)).map(l=>l.request_id));const unread=thread.filter(x=>!x.deleted_at&&!x.reviewed_at).length;return `<div class="oi-swipe-row" data-swipe-message="${m.id}"><button class="oi-message" data-message="${m.id}"><div class="oi-message-top"><b>${esc(m.subject||'No subject')}</b><span class="oi-flag">${related.size?'Linked conversation':'Needs review'}</span></div><span>${esc(m.sender)} · ${esc(when(m.received_at))}</span><p>${esc(m.body.slice(0,180))}</p><small>${thread.length} email${thread.length===1?'':'s'} · ${unread} unreviewed · ${related.size} linked requests</small></button><button class="oi-trash-button secondary" data-trash-message="${m.id}" aria-label="Move conversation to NODARA Trash">Trash</button></div>`}).join('')||'<div class="card oi-empty">No unreviewed messages match this search. Clear the search or refresh the Inbox.</div>'}</div>`}
async function editor(r=null,message=null){
 const draftId=r?.id||crypto.randomUUID();let recordChoices=[];
 const d=r||{request_type:'PICKUP',billing_requirement:'REQUIRED',title:message?.subject||'',description:message?.body||''};
 main.innerHTML=header(r?`Edit ${r.request_number}`:'New request','<button class="secondary" id="oi-back">Back</button>')+`<form id="oi-form" class="oi-form"><div class="oi-form-grid">
 ${r?`<div class="oi-field">Request type<b>${esc(types[r.request_type])}</b></div>`:pick('Request type','oi-type',types,d.request_type)}
 ${input('Request title','oi-title',d.title)}${pick('Saved customer','oi-customer',customerOptions(),d.customer_id||'')}${input('Customer / transaction-only name','oi-customer-name',d.customer_name)}
 ${input('Assigned to','oi-owner',d.owner_name)}${input('Next action','oi-next',d.next_action)}${input('Due','oi-due',localDate(d.due_at),'datetime-local')}${input('Follow up','oi-follow',localDate(d.follow_up_at),'datetime-local')}
 ${pick('Billing','oi-bill',bills,d.billing_requirement)}${r?pick('Status','oi-status',stages,d.status):'<label class="oi-field" id="oi-record-field">Transaction<select id="oi-record"><option value="">Create a draft and assign the next number</option></select></label>'}
 ${r?input('Waiting on','oi-wait',d.waiting_on)+pick('Billing status','oi-bill-status',{PENDING:'Pending',BILLED:'Billed'},d.billing_status)+input('Invoice reference','oi-invoice',d.invoice_reference):''}
 ${textArea('Request details','oi-description',d.description)}</div><p class="muted" id="oi-number-note">The number is assigned when you save. Pickup requests create a linked draft transport order.</p><div class="oi-actions"><button class="primary" type="submit" id="oi-save">${r?'Save changes':'Create request'}</button></div></form>`;
 document.getElementById('oi-title').required=true;
 document.getElementById('oi-back').onclick=()=>r?detail(r.id):message?messageDetail(message.id):render();
 document.getElementById('oi-customer').onchange=e=>{document.getElementById('oi-customer-name').value=entities.find(x=>x.id===e.target.value)?.name||''};
 async function loadChoices(){const kind=value('oi-type');const transport=['PICKUP','DELIVERY','TRANSFER','DRAYAGE'].includes(kind),shipment=kind.startsWith('SHIPMENT_');const field=document.getElementById('oi-record-field');field.hidden=!(transport||shipment);document.getElementById('oi-number-note').textContent=transport?'Saving creates a draft transport order with the next TO number, or uses the existing order you select.':shipment?'Saving creates a draft shipment with its transaction number, or uses the existing shipment you select.':'Saving assigns the next request reference. Billing follows your selection.';if(!transport&&!shipment)return;const expectedKind=kind;recordChoices=await checked(supabase.from(transport?'transport_orders':'shipments').select('*').eq('organization_id',org).eq(transport?'order_type':'mode',transport?kind:kind.slice(9)).order('created_at',{ascending:false}).limit(500));if(value('oi-type')!==expectedKind)return;document.getElementById('oi-record').innerHTML=opts({'':'Create a draft and assign the next number',...Object.fromEntries(recordChoices.filter(x=>!rows.some(r=>r.transport_order_id===x.id||r.shipment_id===x.id)).map(x=>[x.id,x.order_number||x.shipment_number]))},'')}
 if(!r){document.getElementById('oi-type').onchange=async()=>{const kind=value('oi-type');document.getElementById('oi-bill').value=['PICKUP','DELIVERY','TRANSFER','DRAYAGE'].includes(kind)||kind.startsWith('SHIPMENT_')?'REQUIRED':kind==='COMPLAINT'?'NOT_REQUIRED':'UNDECIDED';try{await loadChoices()}catch(e){notice(e.message)}};try{await loadChoices()}catch(e){notice(e.message)}}
 document.getElementById('oi-form').onsubmit=e=>{e.preventDefault();run(document.getElementById('oi-save'),async()=>{const payload={title:value('oi-title'),description:value('oi-description'),customer_id:value('oi-customer')||null,customer_name:value('oi-customer-name'),owner_name:value('oi-owner'),next_action:value('oi-next'),due_at:dateValue('oi-due'),follow_up_at:dateValue('oi-follow'),billing_requirement:value('oi-bill')};let saved;
 if(r)saved=await checked(supabase.from('operations_requests').update({...payload,status:value('oi-status'),waiting_on:value('oi-wait'),billing_status:value('oi-bill-status'),invoice_reference:value('oi-invoice')}).eq('id',r.id).select().single());
 else saved=await checked(supabase.rpc('nodara_create_operations_request',{p_org:org,p_input:{...payload,request_type:value('oi-type'),existing_record_id:value('oi-record')},p_id:draftId,p_message_id:message?.id||null}));
 await reload();await detail(saved.id);})};
}
async function detail(id,tab='request'){
 const r=await checked(supabase.from('operations_requests').select('*').eq('id',id).single());
 const conversationIds=links.filter(l=>l.request_id===id).map(l=>l.message_id),conversation=messages.filter(m=>conversationIds.includes(m.id)).filter((m,i,all)=>all.findIndex(x=>groupKey(x)===groupKey(m))===i);
 main.innerHTML=`<section class="oi-workspace">${header(r.request_number,'<button class="secondary" id="oi-back">Inbox</button><button class="secondary" id="oi-quick">Quick actions & notes</button><button class="primary" id="oi-edit">Edit request</button>')}<div class="oi-detail-title"><span>${esc(types[r.request_type])} · ${esc(stages[r.status])}</span><h2>${esc(r.title)}</h2><p>${esc(r.customer_name||'Customer not assigned')} · ${esc(r.owner_name||'Unassigned')}</p></div><div class="oi-view oi-tabs">${[['request','Request'],['conversations',`Conversations (${conversation.length})`],['activity','Activity']].map(([k,l])=>`<button data-tab="${k}" class="${tab===k?'selected':''}">${l}</button>`).join('')}</div><div id="oi-tab-body"></div></section>`;
 document.getElementById('oi-back').onclick=()=>open();document.getElementById('oi-edit').onclick=()=>editor(r);document.getElementById('oi-quick').onclick=()=>fastTask(id,()=>detail(id,tab));main.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>detail(id,b.dataset.tab));
 const body=document.getElementById('oi-tab-body');
 if(tab==='request'){
 body.innerHTML=`<div class="oi-detail-grid"><section class="card"><h3>Next action</h3><p>${esc(r.next_action||'No next action set')}</p>${r.waiting_on?`<p>Waiting on ${esc(r.waiting_on)}</p>`:''}<div class="oi-actions">${pick('Move to','oi-move',stages,r.status)}<button class="secondary" id="oi-move-save">Update</button></div><dl><dt>Due</dt><dd>${esc(when(r.due_at)||'Not set')}</dd><dt>Follow up</dt><dd>${esc(when(r.follow_up_at)||'Not set')}</dd><dt>Billing</dt><dd>${esc(bills[r.billing_requirement])} · ${r.billing_status==='BILLED'?`Billed: ${esc(r.invoice_reference)}`:'Pending'}</dd></dl></section><section class="card"><h3>Details</h3><div class="oi-body">${esc(r.description||'No additional details')}</div>${r.transport_order_id||r.shipment_id?'<button class="primary" id="oi-open-record">Open linked transaction</button>':''}</section></div>`;
 document.getElementById('oi-move-save').onclick=e=>run(e.target,async()=>{await checked(supabase.from('operations_requests').update({status:value('oi-move')}).eq('id',id).select().single());await reload();await detail(id)});
 const b=document.getElementById('oi-open-record');if(b)b.onclick=async()=>{try{if(r.transport_order_id){window.nodaraSetActive?.('ops_pickups');await window.nodaraOperations.openTransportOrder(r.transport_order_id)}else {const mod=await import('./shipment-canonical-v52.js?v=20260927-awbcal1');await mod.openShipmentCanonical(r.shipment_id)}const back=document.createElement('button');back.className='secondary oi-context-back';back.textContent=`Back to request ${r.request_number}`;back.onclick=()=>{window.nodaraSetActive?.('ops_inbox');detail(id)};main.prepend(back)}catch(e){notice(e.message)}};
 }else if(tab==='conversations'){
 body.innerHTML=`<div class="oi-actions"><button class="primary" id="oi-add-email">Capture conversation</button><button class="secondary" id="oi-link-email">Link captured email</button></div>${conversation.map(m=>`<button class="oi-message" data-message="${m.id}"><b>${esc(m.subject||'No subject')}</b><span>${esc(m.sender)} · ${esc(when(m.received_at))}</span><p>${esc(m.body.slice(0,200))}</p></button>`).join('')||'<div class="oi-empty">No linked conversations yet.</div>'}`;
 document.getElementById('oi-add-email').onclick=()=>capture(r);document.getElementById('oi-link-email').onclick=()=>linkMessage(r);body.querySelectorAll('[data-message]').forEach(b=>b.onclick=()=>messageDetail(b.dataset.message,id));
 }else {const activity=await checked(supabase.from('operations_request_activity').select('*').eq('request_id',id).order('created_at',{ascending:false}));body.innerHTML=activity.map(a=>{const before=a.changes.before||{},after=a.changes.after||{};const changed=Object.keys(after).filter(k=>!['updated_at','created_at','created_by','id','organization_id'].includes(k)&&JSON.stringify(before[k])!==JSON.stringify(after[k]));return `<div class="oi-activity"><b>${a.event==='INSERT'?'Request created':'Request updated'}</b><span>${esc(when(a.created_at))}</span>${a.event==='UPDATE'?changed.map(k=>`<p>${esc(k.replaceAll('_',' '))}: ${esc(before[k]??'—')} → ${esc(after[k]??'—')}</p>`).join(''):''}</div>`}).join('')}
}
function capture(request=null){const id=crypto.randomUUID();main.innerHTML=header('Capture conversation','<button class="secondary" id="oi-back">Back</button>')+`<form id="oi-form" class="oi-form"><p class="muted">Paste the email or full thread. You can create several requests from the same conversation. Use Gmail connection for automatic capture, or paste another conversation here.</p><div class="oi-form-grid">${pick('Source','oi-source',{PASTED_EMAIL:'Email',PHONE:'Phone call',WHATSAPP:'WhatsApp',NOTE:'Note'},'PASTED_EMAIL')}${input('Subject','oi-subject')}${input('From / contact','oi-sender')}${input('Original email or conversation link (optional)','oi-url','', 'url')}${textArea('Full conversation','oi-body')}</div><button class="primary" id="oi-save">Save conversation</button></form>`;document.getElementById('oi-body').required=true;document.getElementById('oi-back').onclick=()=>request?detail(request.id,'conversations'):render();document.getElementById('oi-form').onsubmit=e=>{e.preventDefault();run(document.getElementById('oi-save'),async()=>{await checked(supabase.from('operations_messages').upsert({id,organization_id:org,subject:value('oi-subject'),sender:value('oi-sender'),body:value('oi-body'),source_url:safeUrl(value('oi-url')),source:value('oi-source')},{onConflict:'id'}).select().single());if(request)await checked(supabase.from('operations_request_messages').upsert({organization_id:org,request_id:request.id,message_id:id},{onConflict:'request_id,message_id',ignoreDuplicates:true}));await reload();messageDetail(id,request?.id)})}}
function messageDetail(id,backId=null){const m=messages.find(x=>x.id===id);if(!m)return open();const thread=threadMessages(m),threadIds=thread.map(x=>x.id);const related=rows.filter(r=>links.some(l=>threadIds.includes(l.message_id)&&l.request_id===r.id));main.innerHTML=header(m.subject||'Conversation','<button class="secondary" id="oi-back">Back</button>')+`<div class="oi-detail-grid"><section class="card"><div class="oi-message-heading"><b>${esc(m.sender||'Contact not entered')}</b><span>${thread.length} email${thread.length===1?'':'s'} · ${esc(m.source.replaceAll('_',' '))}</span></div>${thread.map(x=>`<details class="oi-thread-email" ${x.id===m.id?'open':''}><summary>${esc(x.sender||'Contact')} · ${esc(when(x.received_at))}${x.reviewed_at?' · Reviewed':' · Unreviewed'}</summary><div class="oi-body oi-email-body">${esc(x.body)}</div>${x.source_metadata?.body_truncated?'<p class="muted">Long email shortened. Open Gmail for the complete text.</p>':''}${x.source_metadata?.attachments?.length?`<p class="muted">Attachments in Gmail: ${x.source_metadata.attachments.map(a=>esc(a.name)).join(', ')}</p>`:''}${thread.length>1?`<button class="secondary" data-review-email="${x.id}">Review requests in this email</button>`:''}</details>`).join('')}${safeUrl(m.source_url)?`<a class="secondary" href="${esc(safeUrl(m.source_url))}" target="_blank" rel="noopener noreferrer">Open original conversation</a>`:''}</section><section class="card"><h3>Requests in this conversation</h3>${related.map(r=>`<button class="oi-related" data-request="${r.id}"><b>${esc(r.request_number)}</b> ${esc(r.title)}</button>`).join('')||'<p class="muted">No requests linked yet.</p>'}<div class="oi-actions oi-vertical"><button class="primary" id="oi-suggest">${m.extraction?'Review suggestions':'Suggest requests from this email'}</button><button class="primary" id="oi-quick-extract">Quick task from email</button><button class="secondary" id="oi-extract">Create a request manually</button><button class="secondary" id="oi-attach">Attach to existing request</button><button class="secondary" id="oi-reviewed">${m.reviewed_at?'Return email to unreviewed':'This email is fully reviewed / no action'}</button></div><p class="muted">A changed subject can still link to an existing request. Every new reply remains unreviewed until you handle it.</p></section></div>`;
 document.getElementById('oi-back').onclick=()=>backId?detail(backId,'conversations'):render();
 if(!backId){const queue=unreviewedQueue(),index=queue.findIndex(x=>groupKey(x)===groupKey(m));const nav=document.createElement('div');nav.className='oi-triage-nav';nav.innerHTML=`<div><b>Conversation review</b><span>${index>=0?`${index+1} of ${queue.length} in your filtered queue`:'Captured conversation'} · Nothing is created until you approve</span></div><div class="oi-actions"><button class="secondary" id="oi-prev-email" ${index<=0?'disabled':''}>Previous</button><button class="secondary" id="oi-next-email" ${index<0||index>=queue.length-1?'disabled':''}>Next conversation</button></div>`;main.querySelector('.oi-detail-grid').before(nav);document.getElementById('oi-prev-email').onclick=()=>messageDetail(queue[index-1].id);document.getElementById('oi-next-email').onclick=()=>messageDetail(queue[index+1].id);
 if(!m.reviewed_at){const button=document.createElement('button');button.className='secondary';button.id='oi-reviewed-next';button.textContent='Mark this email reviewed & continue';document.getElementById('oi-reviewed').after(button);button.onclick=()=>run(button,async()=>{await checked(supabase.from('operations_messages').update({reviewed_at:new Date().toISOString()}).eq('id',id).select().single());await reload();const remaining=threadMessages(m).find(x=>!x.deleted_at&&!x.reviewed_at);const next=remaining||queue[index+1]||queue[index-1];if(next&&messages.some(x=>groupKey(x)===groupKey(next)&&!x.deleted_at&&!x.reviewed_at))messageDetail(next.id);else{view='unreviewed';render()}})} }
 const review=async email=>{try{const mod=await import('./operations-inbox-review.js?v=20261009-fast1');await mod.reviewEmail(email,{rows,entities,onBack:()=>messageDetail(id,backId),onSaved:async()=>{await reload();messageDetail(id,backId)}})}catch(e){notice(e.message)}};
 document.getElementById('oi-suggest').onclick=()=>review(m);main.querySelectorAll('[data-review-email]').forEach(b=>b.onclick=()=>review(messages.find(x=>x.id===b.dataset.reviewEmail)));
 document.getElementById('oi-quick-extract').onclick=()=>quickCreate({org,entities,message:m,onSaved:async()=>{await reload();messageDetail(id,backId)}});
 document.getElementById('oi-extract').onclick=()=>{const selection=window.getSelection()?.toString().trim();editor(null,selection?{...m,body:selection}:m)};document.getElementById('oi-attach').onclick=()=>linkRequest(m,backId);document.getElementById('oi-reviewed').onclick=e=>run(e.target,async()=>{await checked(supabase.from('operations_messages').update({reviewed_at:m.reviewed_at?null:new Date().toISOString()}).eq('id',id).select().single());await reload();view='unreviewed';render()});main.querySelectorAll('[data-request]').forEach(b=>b.onclick=()=>detail(b.dataset.request))}
function linkRequest(message,backId){linkPicker('Attach to request',rows.filter(r=>!links.some(l=>l.message_id===message.id&&l.request_id===r.id)).map(r=>({id:r.id,label:`${r.request_number} · ${r.title}`})),async id=>{await checked(supabase.from('operations_request_messages').insert({organization_id:org,request_id:id,message_id:message.id}));await reload();messageDetail(message.id,backId)},()=>messageDetail(message.id,backId))}
function linkMessage(request){linkPicker('Link captured conversation',messages.filter(m=>!links.some(l=>l.message_id===m.id&&l.request_id===request.id)).map(m=>({id:m.id,label:`${m.subject||'No subject'} · ${m.sender}`})),async id=>{await checked(supabase.from('operations_request_messages').insert({organization_id:org,request_id:request.id,message_id:id}));await reload();detail(request.id,'conversations')},()=>detail(request.id,'conversations'))}
function linkPicker(title,items,save,back){main.innerHTML=header(title,'<button class="secondary" id="oi-back">Back</button>')+`<div class="oi-form">${input('Search','oi-link-search')}<div id="oi-link-list"></div></div>`;document.getElementById('oi-back').onclick=back;const draw=q=>{const host=document.getElementById('oi-link-list');host.innerHTML=items.filter(x=>x.label.toLowerCase().includes(q.toLowerCase())).map(x=>`<button class="oi-related" data-id="${x.id}">${esc(x.label)}</button>`).join('')||'<div class="oi-empty">No matches</div>';host.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>run(b,()=>save(b.dataset.id)))};draw('');document.getElementById('oi-link-search').oninput=e=>draw(e.target.value)}
window.nodaraOperationsInbox={open};

function renderQueue(list){return '<div class="oi-task-queue">'+(list.map(r=>`<article class="oi-task-row ${late(r)?'oi-overdue':''}"><button class="oi-task-main" data-quick-task="${r.id}"><div class="oi-card-top"><b>${esc(r.request_number)}</b><span>${esc(types[r.request_type])}</span></div><h3>${esc(r.title)}</h3><p>${esc(r.customer_name||'Customer not assigned')} · ${esc(r.owner_name||'Unassigned')}</p><div class="oi-next">${esc(r.next_action||'Set the next action')}</div>${r.waiting_on?`<small>Waiting on ${esc(r.waiting_on)}</small>`:''}${r.follow_up_at?`<small>Reminder ${esc(when(r.follow_up_at))}</small>`:''}${r.due_at?`<small>Due ${esc(when(r.due_at))}</small>`:''}</button><div class="oi-task-actions"><span class="oi-flag">${esc(stages[r.status])}</span><button class="secondary" data-inline-status="${r.status==='NEW'?'WORKING':r.status==='WORKING'?'WAITING':'WORKING'}" data-task-id="${r.id}">${r.status==='NEW'?'Start':r.status==='WORKING'?'Wait':'Resume'}</button><button class="secondary" data-quick-task="${r.id}">Actions · Notes</button><button class="secondary" data-request="${r.id}">Open</button></div></article>`).join('')||'<div class="card oi-empty">Your queue is clear. Add a task or review an incoming conversation.</div>')+'</div>';}
async function fastTask(id,onSaved=render){const r=rows.find(x=>x.id===id);if(!r)return;await quickTask(r,{org,onSaved:async saved=>{rows=rows.map(x=>x.id===saved.id?{...saved}:x);await onSaved()},onFull:detail,onConversation:id=>detail(id,'conversations'),onRecord:openFastRecord});}
async function openFastRecord(link,requestId){try{if(link.kind==='transport_orders'){window.nodaraSetActive?.('ops_pickups');await window.nodaraOperations.openTransportOrder(link.id)}else if(link.kind==='shipments'){const mod=await import('./shipment-canonical-v52.js?v=20260927-awbcal1');await mod.openShipmentCanonical(link.id)}else if(link.kind==='warehouse_receipts'){await window.nodaraOpenCanonicalWR(link.id,'record')}else{await window.nodaraCROpen(link.id)}const back=document.createElement('button');back.className='secondary oi-context-back';back.textContent='Back to request';back.onclick=()=>{window.nodaraSetActive?.('ops_inbox');detail(requestId)};main.prepend(back)}catch(e){notice(e.message)}}
async function trashMessage(id){try{const m=messages.find(x=>x.id===id);if(!m)return;const ids=threadMessages(m).filter(x=>!x.deleted_at).map(x=>x.id);if(!ids.length)return;await checked(supabase.from('operations_messages').update({deleted_at:new Date().toISOString()}).eq('organization_id',org).in('id',ids));await reload();render();undoToast('Conversation moved to NODARA Trash',async()=>{await checked(supabase.from('operations_messages').update({deleted_at:null}).eq('organization_id',org).in('id',ids));await reload();render()})}catch(e){notice(e.message)}}
async function restoreMessage(id){const m=messages.find(x=>x.id===id);if(!m)return;const ids=threadMessages(m).filter(x=>x.deleted_at).map(x=>x.id);await checked(supabase.from('operations_messages').update({deleted_at:null}).eq('organization_id',org).in('id',ids));await reload();render();}
function renderTrash(){const seen=new Set();const list=messages.filter(m=>m.deleted_at&&[m.subject,m.sender,m.body].join(' ').toLowerCase().includes(query.toLowerCase())).filter(m=>{if(seen.has(groupKey(m)))return false;seen.add(groupKey(m));return true});return `<div class="oi-message-list"><div class="oi-triage-intro"><h2>NODARA Trash</h2><p class="muted">Removed from your captured inbox. Gmail messages, requests and linked transactions are preserved. Restore a conversation at any time.</p></div>${list.map(m=>`<div class="oi-swipe-row"><button class="oi-message" data-message="${m.id}"><b>${esc(m.subject||'No subject')}</b><span>${esc(m.sender)}</span></button><button class="secondary" data-restore-message="${m.id}">Restore</button></div>`).join('')||'<div class="card oi-empty">Trash is empty.</div>'}</div>`;}
