import { icon } from './operations-inbox-ui.js?v=20261010-editor11';
import { bindBoardDrag } from './operations-inbox-drag.js?v=20261010-editor11';
import { supabase } from './supabase-client.js';
import { getCurrentOrganizationId } from './live-data.js';
import { requestTypes as types, requestCategories, requestCategory, requestTypeOptions } from './operations-inbox-types.js?v=20261010-editor11';
import { drawer, chooseTaskSource, pickTaskEmail, quickCreate, quickTask, quickReminder, undoToast, bindSwipe } from './operations-inbox-fast.js?v=20261010-editor11';

const main=document.getElementById('main');
const stages={NEW:'Up next',WORKING:'In progress',WAITING:'Waiting',READY_TO_BILL:'Ready to bill',COMPLETED:'Completed',CANCELLED:'Cancelled'};
const bills={REQUIRED:'Required',NOT_REQUIRED:'Not required',UNDECIDED:'To be determined'};
const groupKey=m=>m.mailbox_connection_id&&m.source_thread_id?`${m.mailbox_connection_id}:${m.source_thread_id}`:m.id;
const threadMessages=m=>messages.filter(x=>groupKey(x)===groupKey(m)).sort((a,b)=>new Date(a.received_at)-new Date(b.received_at));
const unreviewedCount=()=>new Set(messages.filter(m=>!m.deleted_at&&!m.reviewed_at).map(groupKey)).size;
let deletedTasks=[],team=[],checklistRows=[],selectedMail=new Set(),filterEvents=null,boardDragCleanup=null;const movingTasks=new Set();
let noteRows=[],calendarMonth=new Date(new Date().getFullYear(),new Date().getMonth(),1),calendarDay=new Date(),reminderTimer=null;
let org,rows=[],messages=[],links=[],entities=[],view='board',query='',typeFilter='',categoryFilter='',focusFilter='active',ownerFilter='',sortOrder='attention',loadVersion=0,loadedAt=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const opts=(items,value)=>Object.entries(items).map(([k,v])=>`<option value="${esc(k)}" ${k===value?'selected':''}>${esc(v)}</option>`).join('');
const when=v=>v?new Date(v).toLocaleString():'';
const localDate=v=>{if(!v)return '';const d=new Date(v);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
const late=r=>!['COMPLETED','CANCELLED'].includes(r.status)&&[r.due_at,r.follow_up_at].some(v=>v&&new Date(v)<=new Date());
const active=r=>!['COMPLETED','CANCELLED'].includes(r.status);
const billPending=r=>r.status!=='CANCELLED'&&r.billing_requirement==='REQUIRED'&&r.billing_status!=='BILLED';
const nextDate=r=>Math.min(...[r.due_at,r.follow_up_at].filter(Boolean).map(v=>new Date(v).getTime()),Infinity);
const today=r=>active(r)&&[r.due_at,r.follow_up_at].some(v=>v&&new Date(v).toDateString()===new Date().toDateString());
const focusTests={active,overdue:late,today,waiting:r=>r.status==='WAITING',billing:billPending,unassigned:r=>active(r)&&!r.owner_name?.trim(),all:()=>true};
const focusLabels={active:'All active',overdue:'Needs attention',today:'Today',waiting:'Waiting',billing:'Billing pending',unassigned:'Unassigned',all:'All requests'};
function sortedRequests(list){return [...list].sort((a,b)=>sortOrder==='newest'?new Date(b.created_at||0)-new Date(a.created_at||0):sortOrder==='oldest'?new Date(a.created_at||0)-new Date(b.created_at||0):sortOrder==='due'?(nextDate(a)-nextDate(b)||a.request_number.localeCompare(b.request_number)):(Number(late(b))-Number(late(a))||nextDate(a)-nextDate(b)||new Date(b.created_at||0)-new Date(a.created_at||0)))}
function unreviewedQueue(){const seen=new Set();return [...messages].sort((a,b)=>new Date(b.received_at)-new Date(a.received_at)).filter(m=>!m.deleted_at&&!m.reviewed_at&&[m.subject,m.sender,m.body].join(' ').toLowerCase().includes(query.toLowerCase())).filter(m=>{const key=groupKey(m);if(seen.has(key))return false;seen.add(key);return true})}
const safeUrl=v=>{try{const u=new URL(v);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}};
const input=(label,id,value='',type='text')=>`<label class="oi-field">${label}<input id="${id}" type="${type}" value="${esc(value)}"></label>`;
const pick=(label,id,items,value)=>`<label class="oi-field">${label}<select id="${id}">${opts(items,value)}</select></label>`;
const textArea=(label,id,value='')=>`<label class="oi-field oi-wide">${label}<textarea id="${id}" rows="5">${esc(value)}</textarea></label>`;
const value=id=>document.getElementById(id)?.value.trim()||'';
const dateValue=id=>value(id)?new Date(value(id)).toISOString():null;
const notice=(msg)=>{const el=document.getElementById('oi-error');if(el){el.textContent=msg;el.hidden=false}else alert(msg)};
async function run(button,fn){if(button.disabled)return;button.disabled=true;try{await fn()}catch(e){notice(e.message||String(e));button.disabled=false}}
async function checked(q){const {data,error}=await q;if(error)throw error;return data}
async function allRows(table,sort='created_at',keys=['id']) {const result=[];for(let start=0;;start+=500){let q=supabase.from(table).select('*').eq('organization_id',org).order(sort,{ascending:false});for(const key of keys)q=q.order(key,{ascending:true});const batch=await checked(q.range(start,start+499));result.push(...batch);if(batch.length<500)return result}}
function customerOptions(id){return {'':'Select customer',...Object.fromEntries(entities.map(e=>[e.id,e.name]))}}
function header(title,actions=''){return `<div class="oi-head"><div><div class="eyebrow">Inbox · Tasks & emails</div><h1 class="title">${esc(title)}</h1></div><div class="oi-actions">${actions}</div></div><div id="oi-error" class="notice warning" role="alert" hidden></div>`}
async function reload(){org=await getCurrentOrganizationId();[rows,messages,links,entities,noteRows,checklistRows,team]=await Promise.all([
 allRows('operations_requests'),allRows('operations_messages','received_at'),
 allRows('operations_request_messages','created_at',['request_id','message_id']),allRows('entities','name'),allRows('operations_request_notes'),allRows('operations_request_checklist'),checked(supabase.rpc('nodara_inbox_team',{p_org:org}))]);deletedTasks=rows.filter(r=>r.deleted_at);rows=rows.filter(r=>!r.deleted_at);loadedAt=new Date();}
export async function open(){window.nodaraSetActive?.('ops_inbox');const version=++loadVersion;main.innerHTML=header('Inbox')+'<div class="card">Loading requests…</div>';try{await reload();if(version===loadVersion&&window.__nodaraRoute==='ops_inbox'){render();startReminders()}}catch(e){if(version===loadVersion)notice(e.message)}}
function render(){
 boardDragCleanup?.();boardDragCleanup=null;
 const keepFilterOpen=document.getElementById('oi-filter-popover')?.hidden===false;filterEvents?.abort();
 const filtered=sortedRequests(rows.filter(r=>(!typeFilter||r.request_type===typeFilter)&&(!categoryFilter||requestCategory(r.request_type)===categoryFilter)&&focusTests[focusFilter](r)&&(!ownerFilter||(ownerFilter==='__unassigned__'?!r.owner_name?.trim():r.owner_name===ownerFilter))&&[r.request_number,r.title,r.customer_name,r.owner_name,r.next_action,r.waiting_on,types[r.request_type]].join(' ').toLowerCase().includes(query.toLowerCase())));
 main.innerHTML=`<section class="oi-workspace">${header('Inbox',`<details class="oi-inbox-menu"><summary class="oi-icon-button" aria-label="Inbox tools" title="Inbox tools">${icon('more')}</summary><div><button class="secondary" id="oi-gmail">Gmail connection</button><button class="secondary" id="oi-capture">Capture email</button><button class="secondary" id="oi-push">Push notifications</button></div></details><button class="oi-icon-button" id="oi-refresh" aria-label="Refresh inbox" title="Refresh inbox">${icon('refresh')}</button><button class="primary" id="oi-new">${icon('plus')}<span>New task</span></button>`)}
 <p class="oi-workspace-subtitle">A clear next step for every request.</p>
 <div class="oi-metrics">${['active','overdue','today','waiting'].map(k=>`<button data-focus="${k}" ${k==='overdue'?'id="oi-attention"':''} aria-pressed="${focusFilter===k}" class="${focusFilter===k?'selected':''}"><b>${rows.filter(focusTests[k]).length}</b><span>${focusLabels[k]}</span></button>`).join('')}</div>
 <div class="oi-toolbar"><div class="oi-view">${[['board','Board'],['calendar','Calendar'],['unreviewed','Emails'],['list','List'],['trash','Trash']].map(([k,l])=>`<button data-view="${k}" aria-pressed="${view===k}" class="${view===k?'selected':''}">${icon({unreviewed:'mail',queue:'queue',list:'list',trash:'trash',board:'board',calendar:'calendar'}[k])}<span>${l}</span>${k==='unreviewed'&&unreviewedCount()?`<small class="oi-view-count">${unreviewedCount()}</small>`:''}</button>`).join('')}</div><div class="oi-search-wrap">${icon('search')}<input id="oi-search" aria-label="Search requests" placeholder="Search tasks, customers or references…" value="${esc(query)}"></div>
 <div class="oi-filter-anchor"><button id="oi-filter-toggle" class="oi-icon-button" aria-label="Filters & sorting" title="Filters & sorting" aria-expanded="false" aria-controls="oi-filter-popover">${icon('filter')}${typeFilter||categoryFilter||ownerFilter||focusFilter!=='active'||sortOrder!=='attention'?'<i></i>':''}</button><div id="oi-filter-popover" class="oi-filter-popover" role="dialog" aria-label="Filters & sorting" hidden><div class="oi-popover-head"><b>Filters & sorting</b><button id="oi-filter-close" aria-label="Close filters">×</button></div><label class="oi-popover-label">Category<select id="oi-category" aria-label="Task category">${opts({'':'All categories',...requestCategories},categoryFilter)}</select></label><label class="oi-popover-label" id="oi-service-field">Service<select id="oi-filter" aria-label="Task service"><option value="">All services</option>${requestTypeOptions(typeFilter,categoryFilter)}</select></label><div class="oi-filterbar" ${view==='unreviewed'?'hidden':''}><select id="oi-focus" aria-label="Focus view">${opts(focusLabels,focusFilter)}</select><select id="oi-owner-filter" aria-label="Assigned owner">${opts({'':'All owners','__unassigned__':'Unassigned',...Object.fromEntries([...new Set(rows.map(r=>r.owner_name).filter(Boolean))].sort().map(n=>[n,n]))},ownerFilter)}</select><select id="oi-sort" aria-label="Sort requests">${opts({attention:'Needs attention first',due:'Next date first',newest:'Newest first',oldest:'Oldest first'},sortOrder)}</select><span>${filtered.length} request${filtered.length===1?'':'s'} · Refreshed ${esc(loadedAt?.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})||'now')}</span><button class="secondary" id="oi-clear">Clear filters</button></div></div></div></div>
 ${view==='unreviewed'?renderUnreviewed():view==='trash'?renderTrash():view==='calendar'?renderCalendar(filtered):view==='queue'?renderQueue(filtered):view==='list'?renderList(filtered):renderBoard(filtered)}
 </section>`;
 bindFloatingFilters(keepFilterOpen);bindMailSelection();
 document.getElementById('oi-gmail').onclick=async()=>{try{const mod=await import('./operations-inbox-review.js?v=20261010-editor11');await mod.openMailboxes({org,onBack:()=>open()})}catch(e){notice(e.message)}};document.getElementById('oi-new').onclick=()=>chooseTaskSource({org,entities,messages,onSaved:async()=>{await reload();render()}});document.getElementById('oi-capture').onclick=()=>capture();
 document.getElementById('oi-refresh').onclick=e=>run(e.currentTarget,async()=>{await reload();render()});
 main.querySelectorAll('[data-focus]').forEach(b=>b.onclick=()=>{focusFilter=b.dataset.focus;if(view==='unreviewed')view='board';render()});
 document.getElementById('oi-focus').onchange=e=>{focusFilter=e.target.value;render()};
 document.getElementById('oi-category').onchange=e=>{categoryFilter=e.target.value;typeFilter='';render()};document.getElementById('oi-category').parentElement.hidden=view==='unreviewed'||view==='trash';document.getElementById('oi-service-field').hidden=view==='unreviewed'||view==='trash';
 document.getElementById('oi-owner-filter').onchange=e=>{ownerFilter=e.target.value;render()};
 document.getElementById('oi-sort').onchange=e=>{sortOrder=e.target.value;render()};
 document.getElementById('oi-clear').onclick=()=>{query='';typeFilter='';categoryFilter='';ownerFilter='';focusFilter='active';sortOrder='attention';render()};
 main.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});
 document.getElementById('oi-filter').hidden=view==='unreviewed';document.getElementById('oi-filter').onchange=e=>{typeFilter=e.target.value;render()};
 document.getElementById('oi-search').oninput=e=>{query=e.target.value;const position=e.target.selectionStart;render();const input=document.getElementById('oi-search');input.focus();input.setSelectionRange(position,position)};
 main.querySelectorAll('[data-request]').forEach(b=>b.onclick=()=>fastTask(b.dataset.request));
 main.querySelectorAll('[data-card-action]').forEach(b=>b.onclick=e=>{e.stopPropagation();const r=rows.find(x=>x.id===b.dataset.taskId);if(!r)return;if(b.dataset.cardAction==='conversation')return openTaskConversation(r.id);if(b.dataset.cardAction==='reply')return replyTask(r.id);if(b.dataset.cardAction==='remind')return quickReminder(r,{org,anchor:b,onSaved:async saved=>{rows=rows.map(x=>x.id===saved.id?saved:x);render()}});run(b,async()=>{const before=r.status;const status=b.dataset.cardAction==='wait'?(r.status==='WAITING'?'WORKING':'WAITING'):(billPending(r)?'READY_TO_BILL':'COMPLETED');const saved=await checked(supabase.from('operations_requests').update({status}).eq('organization_id',org).eq('id',r.id).select().single());rows=rows.map(x=>x.id===saved.id?saved:x);render();undoToast(status==='READY_TO_BILL'?'Work finished · billing still pending':status==='COMPLETED'?'Task completed':status==='WAITING'?'Moved to Waiting':'Task resumed',async()=>{await checked(supabase.from('operations_requests').update({status:before}).eq('organization_id',org).eq('id',r.id).eq('status',status).select().single());await reload();render()});});});
 main.querySelectorAll('[data-quick-task]').forEach(b=>b.onclick=()=>fastTask(b.dataset.quickTask));
 main.querySelectorAll('[data-inline-status]').forEach(b=>b.onclick=()=>run(b,async()=>{const saved=await checked(supabase.from('operations_requests').update({status:b.dataset.inlineStatus}).eq('organization_id',org).eq('id',b.dataset.taskId).select().single());rows=rows.map(x=>x.id===saved.id?saved:x);render()}));
 main.querySelectorAll('[data-trash-message]').forEach(b=>b.onclick=()=>run(b,()=>trashMessage(b.dataset.trashMessage)));
 document.getElementById('oi-empty-trash')?.addEventListener('click',()=>purgeTrash({empty:true}));main.querySelectorAll('[data-purge-task]').forEach(b=>b.onclick=()=>purgeTrash({taskId:b.dataset.purgeTask}));main.querySelectorAll('[data-purge-message]').forEach(b=>b.onclick=()=>purgeTrash({messageId:b.dataset.purgeMessage}));
 main.querySelectorAll('[data-restore-task]').forEach(b=>b.onclick=()=>run(b,async()=>{const r=deletedTasks.find(x=>x.id===b.dataset.restoreTask);if(!r)return;await checked(supabase.from('operations_requests').update({deleted_at:null,deleted_status:null,status:r.deleted_status||'NEW'}).eq('organization_id',org).eq('id',r.id).eq('deleted_at',r.deleted_at).select().single());await reload();render();}));
 main.querySelectorAll('[data-restore-message]').forEach(b=>b.onclick=()=>run(b,()=>restoreMessage(b.dataset.restoreMessage)));
 bindSwipe(main,trashMessage);
 bindCalendar();drawReminders();
 document.getElementById('oi-push').onclick=async()=>{try{const m=await import('./operations-inbox-push.js?v=20261010-editor11');await m.openPush(org)}catch(e){notice(e.message)}};
 main.querySelectorAll('[data-message]').forEach(b=>b.onclick=()=>messageDetail(b.dataset.message));
 main.querySelectorAll('[data-stage]').forEach(column=>{column.ondragover=e=>{e.preventDefault();column.classList.add('oi-drop-target');};column.ondragleave=e=>{if(!column.contains(e.relatedTarget))column.classList.remove('oi-drop-target');};column.ondrop=e=>{e.preventDefault();column.classList.remove('oi-drop-target');moveBoardTask(e.dataTransfer.getData('text/nodara-request'),column.dataset.stage);};});
 main.querySelectorAll('[draggable]').forEach(card=>{card.ondragstart=e=>{if(e.target.closest?.('[data-drag-handle]'))return e.preventDefault();e.dataTransfer.setData('text/nodara-request',card.dataset.dragRequest);e.dataTransfer.effectAllowed='move';};card.ondragend=()=>main.querySelectorAll('.oi-drop-target').forEach(x=>x.classList.remove('oi-drop-target'));});
 boardDragCleanup=bindBoardDrag(main,{onMove:moveBoardTask,onOpen:fastTask});
}
async function moveBoardTask(id,target){
 const r=rows.find(x=>x.id===id);if(!r||movingTasks.has(id)||!stages[target])return;
 const status=target==='COMPLETED'&&billPending(r)?'READY_TO_BILL':target;if(status===r.status)return;
 const repaint=()=>{if(window.__nodaraRoute==='ops_inbox'&&main.querySelector('.oi-workspace'))render();};
 const before=r.status;movingTasks.add(id);rows=rows.map(x=>x.id===id?{...x,status}:x);repaint();
 try{
  const saved=await checked(supabase.from('operations_requests').update({status}).eq('organization_id',org).eq('id',id).select().single());rows=rows.map(x=>x.id===id?saved:x);movingTasks.delete(id);repaint();
  undoToast(status==='READY_TO_BILL'?'Moved to Ready to bill':'Moved to '+stages[status],async()=>{const restored=await checked(supabase.from('operations_requests').update({status:before}).eq('organization_id',org).eq('id',id).eq('status',status).select().single());rows=rows.map(x=>x.id===id?restored:x);repaint();});
 }catch(error){rows=rows.map(x=>x.id===id?{...x,status:before}:x);movingTasks.delete(id);repaint();notice('Move not saved. '+(error.message||String(error)));}
}
function cardSchedule(r){
 const events=[['Reminder',r.follow_up_at],['Due',r.due_at]].filter(([,v])=>v&&Number.isFinite(new Date(v).getTime())).sort((a,b)=>new Date(a[1])-new Date(b[1]));
 if(!active(r)||!events.length)return '';const [kind,value]=events[0],d=new Date(value),now=new Date(),tomorrow=new Date(now);tomorrow.setDate(now.getDate()+1);
 const day=d.toDateString()===now.toDateString()?'Today':d.toDateString()===tomorrow.toDateString()?'Tomorrow':d.toLocaleDateString([],{month:'short',day:'numeric'});
 const label=day+' · '+d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});
 return `<span class="oi-card-schedule ${d<=now?'is-due':''}" title="${esc(kind+' · '+when(value))}">${icon('clock')}<span>${esc(kind)} · ${esc(label)}</span></span>`;
}
function currentStep(r){const steps=checklistRows.filter(x=>x.request_id===r.id).sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));return steps.length?(steps.find(x=>!x.done)?.title||''):(r.next_action||'');}
function card(r){const relatedIds=links.filter(l=>l.request_id===r.id).map(l=>l.message_id);const source=messages.filter(m=>relatedIds.includes(m.id)&&!m.deleted_at);const unread=source.filter(m=>!m.reviewed_at).length;const gmail=source.some(m=>m.source==='GMAIL');return `<article class="oi-card oi-simple-card ${movingTasks.has(r.id)?'oi-move-saving':''} ${late(r)?'oi-overdue':''}" data-drag-request="${r.id}" draggable="true"><button class="oi-card-open" data-request="${r.id}"><div class="oi-card-top"><span class="oi-card-type" title="Category · ${esc(requestCategories[requestCategory(r.request_type)])}">${esc(types[r.request_type])}</span>${r.priority&&['HIGH','URGENT'].includes(r.priority)?`<span class="oi-flag oi-priority">${esc(r.priority.toLowerCase())}</span>`:''}</div><h3>${esc(r.title)}</h3>${r.customer_name?`<p class="oi-card-customer">${esc(r.customer_name)}</p>`:''}${currentStep(r)?`<div class="oi-next"><small>CURRENT TASK</small><span>${esc(currentStep(r))}</span></div>`:''}${r.status==='WAITING'&&r.waiting_on?`<div class="oi-waiting">Waiting on ${esc(r.waiting_on)}</div>`:''}${cardUpdate(r)}${source.length?`<div class="oi-card-source"><small>Source email</small><span>${esc([...source].sort((a,b)=>new Date(b.received_at)-new Date(a.received_at))[0].subject||'No subject')}</span></div>`:''}<div class="oi-card-meta">${cardSchedule(r)}${r.owner_name?`<span class="oi-card-owner" title="Assigned to ${esc(r.owner_name)}">${esc(r.owner_name)}</span>`:''}${checkProgress(r)}${unread?`<span class="oi-flag">${unread} new</span>`:''}<small title="Task reference">Task · ${esc(r.request_number)}</small></div></button><button type="button" class="oi-drag-handle" data-drag-handle="${r.id}" aria-label="Move ${esc(r.title)}. Drag, or use left and right arrow keys." title="Drag to move">${icon('grip')}</button><div class="oi-card-actions">${active(r)?`${r.status!=='READY_TO_BILL'?`<button data-card-action="done" data-task-id="${r.id}" aria-label="Finish ${esc(r.title)}" title="Done">${icon('check')}</button>`:''}<button data-card-action="wait" data-task-id="${r.id}" aria-label="${r.status==='WAITING'?'Resume':'Wait on'} ${esc(r.title)}" title="${r.status==='WAITING'?'Resume':'Wait'}">${icon(r.status==='WAITING'?'play':'pause')}</button><button data-card-action="remind" data-task-id="${r.id}" aria-label="Remind me about ${esc(r.title)}" title="Remind">${icon('clock')}</button>`:''}${source.length?`<button data-card-action="conversation" data-task-id="${r.id}" aria-label="Conversation for ${esc(r.title)}" title="Conversation">${icon('mail')}</button>`:''}${gmail?`<button data-card-action="reply" data-task-id="${r.id}" aria-label="Reply to ${esc(r.title)}" title="Reply">${icon('reply')}</button>`:''}</div></article>`}

function renderBoard(list){return `<div class="oi-board">${Object.entries(stages).filter(([k])=>k!=='CANCELLED').map(([k,l])=>{const group=list.filter(r=>r.status===k);return `<section class="oi-column" data-stage="${k}" aria-label="${esc(l)}"><h2>${l}<span>${group.length}</span></h2><div class="oi-stack">${group.map(card).join('')||'<div class="oi-empty">No requests</div>'}</div></section>`}).join('')}</div>`}
function renderList(list){return `<div class="oi-table-wrap"><table class="oi-table"><thead><tr><th>Request</th><th>Customer</th><th>Owner</th><th>Status</th><th>Current task</th><th>Due</th><th>Billing</th></tr></thead><tbody>${list.map(r=>`<tr><td><button data-request="${r.id}"><b>${esc(r.request_number)}</b><span>${esc(r.title)}</span></button></td><td>${esc(r.customer_name)}</td><td>${esc(r.owner_name||'Unassigned')}</td><td>${esc(stages[r.status])}</td><td>${esc(currentStep(r))}</td><td>${esc(when(r.due_at))}</td><td>${esc(bills[r.billing_requirement])}</td></tr>`).join('')||'<tr><td colspan="7">No requests yet. Create a request or capture an email.</td></tr>'}</tbody></table></div>`}
function renderUnreviewed(){const list=unreviewedQueue();return `<div class="oi-message-list"><div class="oi-triage-intro"><h2>${list.length?'Review incoming emails':'Your email review queue is clear.'}</h2><p class="muted">${list.length?'An email is a source. Create a task for work to do; mark No action or Trash the rest.':'New captured emails will appear here after you refresh.'}</p></div>${list.length?`<div class="oi-bulk-bar"><label><input type="checkbox" id="oi-select-all" aria-label="Select all visible conversations" ${list.every(x=>selectedMail.has(x.id))?'checked':''}> Select all</label><span id="oi-selected-count">${selectedMail.size} selected</span><button class="secondary" id="oi-bulk-review" ${selectedMail.size?'':'disabled'}>No action</button><button class="oi-icon-button" id="oi-bulk-trash" aria-label="Delete selected conversations" title="Move selected to NODARA Trash" ${selectedMail.size?'':'disabled'}>${icon('trash')}</button></div>`:''}${list.map(m=>{const thread=threadMessages(m);const related=new Set(links.filter(l=>thread.some(x=>x.id===l.message_id)).map(l=>l.request_id));const unread=thread.filter(x=>!x.deleted_at&&!x.reviewed_at).length;return `<div class="oi-swipe-row" data-swipe-message="${m.id}"><label class="oi-mail-select"><input type="checkbox" data-select-message="${m.id}" aria-label="Select ${esc(m.subject||'No subject')}" ${selectedMail.has(m.id)?'checked':''}></label><button class="oi-message" data-message="${m.id}"><div class="oi-message-top"><b>${esc(m.subject||'No subject')}</b><span class="oi-flag">${related.size?'Linked conversation':'Needs review'}</span></div><span>${esc(m.sender)} · ${esc(when(m.received_at))}</span><p>${esc(m.body.slice(0,180))}</p><small>${thread.length} email${thread.length===1?'':'s'} · ${unread} unreviewed · ${related.size} linked requests</small></button><button class="oi-trash-button secondary" data-trash-message="${m.id}" aria-label="Move conversation to NODARA Trash">${icon('trash')}</button></div>`}).join('')||'<div class="card oi-empty">No unreviewed messages match this search. Clear the search or refresh the Inbox.</div>'}</div>`}
async function editor(r=null,message=null){
 const draftId=r?.id||crypto.randomUUID();let recordChoices=[];
 const d=r||{request_type:'PICKUP',billing_requirement:'REQUIRED',title:message?.subject||'',description:message?.body||''};
 main.innerHTML=header(r?`Edit ${r.request_number}`:'New request','<button class="secondary" id="oi-back">Back</button>')+`<form id="oi-form" class="oi-form"><div class="oi-form-grid">
 ${r?`<div class="oi-field">Request type<b>${esc(types[r.request_type])}</b></div>`:pick('Service','oi-type',types,d.request_type)}
 ${input('Request title','oi-title',d.title)}${pick('Saved customer','oi-customer',customerOptions(),d.customer_id||'')}${input('Customer / transaction-only name','oi-customer-name',d.customer_name)}
 ${input('Assigned to','oi-owner',d.owner_name)}${input('Next action','oi-next',d.next_action)}${input('Due','oi-due',localDate(d.due_at),'datetime-local')}${input('Follow up','oi-follow',localDate(d.follow_up_at),'datetime-local')}
 ${pick('Billing','oi-bill',bills,d.billing_requirement)}${r?pick('Status','oi-status',stages,d.status):'<label class="oi-field" id="oi-record-field">Transaction<select id="oi-record"><option value="">Create a draft and assign the next number</option></select></label>'}
 ${r?input('Waiting on','oi-wait',d.waiting_on)+pick('Billing status','oi-bill-status',{PENDING:'Pending',BILLED:'Billed'},d.billing_status)+input('Invoice reference','oi-invoice',d.invoice_reference):''}
 ${textArea('Request details','oi-description',d.description)}</div><p class="muted" id="oi-number-note">The number is assigned when you save. Pickup requests create a linked draft transport order.</p><div class="oi-actions"><button class="primary" type="submit" id="oi-save">${r?'Save changes':'Create request'}</button></div></form>`;
 document.getElementById('oi-title').required=true;
 document.getElementById('oi-back').onclick=()=>r?detail(r.id):message?messageDetail(message.id):render();
 document.getElementById('oi-customer').onchange=e=>{document.getElementById('oi-customer-name').value=entities.find(x=>x.id===e.target.value)?.name||''};
 async function loadChoices(){const kind=value('oi-type');const transport=['PICKUP','DELIVERY','TRANSFER','DRAYAGE'].includes(kind),shipment=kind.startsWith('SHIPMENT_');const field=document.getElementById('oi-record-field');field.hidden=!(transport||shipment);document.getElementById('oi-number-note').textContent=transport?'Saving creates a draft transport order with the next TO number, or uses the existing order you select.':shipment?'Saving creates a draft shipment with its transaction number, or uses the existing shipment you select.':'Saving assigns the next request reference. Billing follows your selection.';if(!transport&&!shipment)return;const expectedKind=kind;recordChoices=await checked(supabase.from(transport?'transport_orders':'shipments').select('*').eq('organization_id',org).eq(transport?'order_type':'mode',transport?kind:kind.slice(9)).order('created_at',{ascending:false}).limit(500));if(value('oi-type')!==expectedKind)return;document.getElementById('oi-record').innerHTML=opts({'':'Create a draft and assign the next number',...Object.fromEntries(recordChoices.filter(x=>!rows.some(r=>r.transport_order_id===x.id||r.shipment_id===x.id)).map(x=>[x.id,x.order_number||x.shipment_number]))},'')}
 if(!r){document.getElementById('oi-type').onchange=async()=>{const kind=value('oi-type');document.getElementById('oi-bill').value=['PICKUP','DELIVERY','TRANSFER','DRAYAGE'].includes(kind)||kind.startsWith('SHIPMENT_')?'REQUIRED':kind==='COMPLAINT'?'NOT_REQUIRED':'UNDECIDED';try{await loadChoices()}catch(e){notice(e.message)}};try{await loadChoices()}catch(e){notice(e.message)}}
 document.getElementById('oi-form').onsubmit=e=>{e.preventDefault();run(document.getElementById('oi-save'),async()=>{const payload={title:value('oi-title'),description:value('oi-description'),customer_id:value('oi-customer')||null,customer_name:value('oi-customer-name'),owner_name:value('oi-owner'),next_action:value('oi-next'),due_at:dateValue('oi-due'),follow_up_at:dateValue('oi-follow'),billing_requirement:value('oi-bill')};let saved;
 if(r)saved=await checked(supabase.from('operations_requests').update({...payload,status:value('oi-status'),waiting_on:value('oi-wait'),billing_status:value('oi-bill-status'),invoice_reference:value('oi-invoice')}).eq('id',r.id).select().single());
 else saved=await checked(supabase.rpc('nodara_create_operations_request',{p_org:org,p_input:{...payload,request_type:value('oi-type'),existing_record_id:value('oi-record')},p_id:draftId,p_message_id:message?.id||null}));
 await reload();await detail(saved.id);})};
}
async function detail(id,tab='request'){
 const r=await checked(supabase.from('operations_requests').select('*').eq('id',id).single());
 const conversationIds=links.filter(l=>l.request_id===id).map(l=>l.message_id),conversation=messages.filter(m=>conversationIds.includes(m.id)).filter((m,i,all)=>all.findIndex(x=>groupKey(x)===groupKey(m))===i);
 main.innerHTML=`<section class="oi-workspace">${header(r.request_number,'<button class="secondary" id="oi-back">Inbox</button><button class="secondary" id="oi-quick">Quick actions & notes</button><button class="primary" id="oi-edit">Edit request</button>')}<div class="oi-detail-title"><span>${esc(types[r.request_type])} · ${esc(stages[r.status])}</span><h2>${esc(r.title)}</h2><p>${esc(r.customer_name||'Customer not assigned')} · ${esc(r.owner_name||'Unassigned')}</p></div><div class="oi-view oi-tabs">${[['request','Request'],['conversations',`Conversations (${conversation.length})`],['activity','Activity']].map(([k,l])=>`<button data-tab="${k}" class="${tab===k?'selected':''}">${l}</button>`).join('')}</div><div id="oi-tab-body"></div></section>`;
 document.getElementById('oi-back').onclick=()=>open();document.getElementById('oi-edit').onclick=()=>editor(r);document.getElementById('oi-quick').onclick=()=>fastTask(id,()=>detail(id,tab));main.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>detail(id,b.dataset.tab));
 const body=document.getElementById('oi-tab-body');
 if(tab==='request'){
 body.innerHTML=`<div class="oi-detail-grid"><section class="card"><h3>Next action</h3><p>${esc(r.next_action||'No next action set')}</p>${r.waiting_on?`<p>Waiting on ${esc(r.waiting_on)}</p>`:''}<div class="oi-actions">${pick('Move to','oi-move',stages,r.status)}<button class="secondary" id="oi-move-save">Update</button></div><dl><dt>Due</dt><dd>${esc(when(r.due_at)||'Not set')}</dd><dt>Follow up</dt><dd>${esc(when(r.follow_up_at)||'Not set')}</dd><dt>Billing</dt><dd>${esc(bills[r.billing_requirement])} · ${r.billing_status==='BILLED'?`Billed: ${esc(r.invoice_reference)}`:'Pending'}</dd></dl></section><section class="card"><h3>Details</h3><div class="oi-body">${esc(r.description||'No additional details')}</div>${r.transport_order_id||r.shipment_id?'<button class="primary" id="oi-open-record">Open linked transaction</button>':''}</section></div>`;
 document.getElementById('oi-move-save').onclick=e=>run(e.target,async()=>{await checked(supabase.from('operations_requests').update({status:value('oi-move')}).eq('id',id).select().single());await reload();await detail(id)});
 const b=document.getElementById('oi-open-record');if(b)b.onclick=async()=>{try{if(r.transport_order_id){window.nodaraSetActive?.('ops_pickups');await window.nodaraOperations.openTransportOrder(r.transport_order_id)}else {const mod=await import('./shipment-canonical-v52.js?v=20260927-awbcal1');await mod.openShipmentCanonical(r.shipment_id)}const back=document.createElement('button');back.className='secondary oi-context-back';back.textContent=`Back to request ${r.request_number}`;back.onclick=()=>{window.nodaraSetActive?.('ops_inbox');detail(id)};main.prepend(back)}catch(e){notice(e.message)}};
 }else if(tab==='conversations'){
 body.innerHTML=`<div class="oi-actions"><button class="primary" id="oi-add-email">Capture conversation</button><button class="secondary" id="oi-link-email">Link captured email</button></div>${conversation.map(m=>`<button class="oi-message" data-message="${m.id}"><b>${esc(m.subject||'No subject')}</b><span>${esc(m.sender)} · ${esc(when(m.received_at))}</span><p>${esc(m.body.slice(0,200))}</p></button>`).join('')||'<div class="oi-empty">No linked conversations yet.</div>'}`;
 document.getElementById('oi-add-email').onclick=()=>capture(r);document.getElementById('oi-link-email').onclick=()=>linkMessage(r);body.querySelectorAll('[data-message]').forEach(b=>b.onclick=()=>messageDetail(b.dataset.message,id));
 }else {const activity=await checked(supabase.from('operations_request_activity').select('*').eq('request_id',id).order('created_at',{ascending:false}));body.innerHTML=activity.map(a=>{const before=a.changes.before||{},after=a.changes.after||{};const changed=Object.keys(after).filter(k=>!['updated_at','created_at','created_by','id','organization_id'].includes(k)&&JSON.stringify(before[k])!==JSON.stringify(after[k]));return `<div class="oi-activity"><b>${a.event==='INSERT'?'Request created':'Request updated'}</b><span>${esc(when(a.created_at))}</span>${a.event==='UPDATE'?changed.map(k=>`<p>${esc(k.replaceAll('_',' '))}: ${esc(before[k]??'—')} → ${esc(after[k]??'—')}</p>`).join(''):''}</div>`}).join('')}
}
function capture(request=null){const id=crypto.randomUUID();main.innerHTML=header('Capture conversation','<button class="secondary" id="oi-back">Back</button>')+`<form id="oi-form" class="oi-form"><p class="muted">Paste the email or full thread. You can create several requests from the same conversation. Use Gmail connection for automatic capture, or paste another conversation here.</p><div class="oi-form-grid">${pick('Source','oi-source',{PASTED_EMAIL:'Email',PHONE:'Phone call',WHATSAPP:'WhatsApp',NOTE:'Note'},'PASTED_EMAIL')}${input('Subject','oi-subject')}${input('From / contact','oi-sender')}${input('Original email or conversation link (optional)','oi-url','', 'url')}${textArea('Full conversation','oi-body')}</div><button class="primary" id="oi-save">Save conversation</button></form>`;document.getElementById('oi-body').required=true;document.getElementById('oi-back').onclick=()=>request?detail(request.id,'conversations'):render();document.getElementById('oi-form').onsubmit=e=>{e.preventDefault();run(document.getElementById('oi-save'),async()=>{await checked(supabase.from('operations_messages').upsert({id,organization_id:org,subject:value('oi-subject'),sender:value('oi-sender'),body:value('oi-body'),source_url:safeUrl(value('oi-url')),source:value('oi-source')},{onConflict:'id'}).select().single());if(request)await checked(supabase.from('operations_request_messages').upsert({organization_id:org,request_id:request.id,message_id:id},{onConflict:'request_id,message_id',ignoreDuplicates:true}));await reload();messageDetail(id,request?.id)})}}
function messageDetail(id,backId=null){const m=messages.find(x=>x.id===id);if(!m)return open();const thread=threadMessages(m),threadIds=thread.map(x=>x.id);const related=rows.filter(r=>links.some(l=>threadIds.includes(l.message_id)&&l.request_id===r.id));main.innerHTML=header(m.subject||'Conversation','<button class="secondary" id="oi-back">Back</button>')+`<div class="oi-detail-grid"><section class="card"><div class="oi-message-heading"><b>${esc(m.sender||'Contact not entered')}</b><span>${thread.length} email${thread.length===1?'':'s'} · ${esc(m.source.replaceAll('_',' '))}</span></div>${thread.map(x=>`<details class="oi-thread-email" ${x.id===m.id?'open':''}><summary>${esc(x.sender||'Contact')} · ${esc(when(x.received_at))}${x.reviewed_at?' · Reviewed':' · Unreviewed'}</summary><div class="oi-body oi-email-body">${esc(x.body)}</div>${x.source_metadata?.body_truncated?'<p class="muted">Long email shortened. Open Gmail for the complete text.</p>':''}${x.source_metadata?.attachments?.length?`<p class="muted">Attachments in Gmail: ${x.source_metadata.attachments.map(a=>esc(a.name)).join(', ')}</p>`:''}${thread.length>1?`<button class="secondary" data-review-email="${x.id}">Review requests in this email</button>`:''}</details>`).join('')}${m.source==='GMAIL'?'<button class="primary" id="oi-reply-email">Reply email</button>':''}${safeUrl(m.source_url)?`<a class="secondary" href="${esc(safeUrl(m.source_url))}" target="_blank" rel="noopener noreferrer">Open original conversation</a>`:''}</section><section class="card"><h3>Requests in this conversation</h3>${related.map(r=>`<button class="oi-related" data-request="${r.id}"><b>${esc(r.request_number)}</b> ${esc(r.title)}</button>`).join('')||'<p class="muted">No requests linked yet.</p>'}<div class="oi-actions oi-vertical"><button class="primary" id="oi-suggest">${m.extraction?'Review suggestions':'Suggest requests from this email'}</button><button class="primary" id="oi-quick-extract">Quick task from email</button><button class="secondary" id="oi-extract">Create a request manually</button><button class="secondary" id="oi-attach">Attach to existing request</button><button class="secondary" id="oi-reviewed">${m.reviewed_at?'Return email to unreviewed':'This email is fully reviewed / no action'}</button></div><p class="muted">A changed subject can still link to an existing request. Every new reply remains unreviewed until you handle it.</p></section></div>`;
 document.getElementById('oi-back').onclick=()=>backId?detail(backId,'conversations'):render();
 if(!backId){const queue=unreviewedQueue(),index=queue.findIndex(x=>groupKey(x)===groupKey(m));const nav=document.createElement('div');nav.className='oi-triage-nav';nav.innerHTML=`<div><b>Conversation review</b><span>${index>=0?`${index+1} of ${queue.length} in your filtered queue`:'Captured conversation'} · Nothing is created until you approve</span></div><div class="oi-actions"><button class="secondary" id="oi-prev-email" ${index<=0?'disabled':''}>Previous</button><button class="secondary" id="oi-next-email" ${index<0||index>=queue.length-1?'disabled':''}>Next conversation</button></div>`;main.querySelector('.oi-detail-grid').before(nav);document.getElementById('oi-prev-email').onclick=()=>messageDetail(queue[index-1].id);document.getElementById('oi-next-email').onclick=()=>messageDetail(queue[index+1].id);
 if(!m.reviewed_at){const button=document.createElement('button');button.className='secondary';button.id='oi-reviewed-next';button.textContent='Mark this email reviewed & continue';document.getElementById('oi-reviewed').after(button);button.onclick=()=>run(button,async()=>{await checked(supabase.from('operations_messages').update({reviewed_at:new Date().toISOString()}).eq('id',id).select().single());await reload();const remaining=threadMessages(m).find(x=>!x.deleted_at&&!x.reviewed_at);const next=remaining||queue[index+1]||queue[index-1];if(next&&messages.some(x=>groupKey(x)===groupKey(next)&&!x.deleted_at&&!x.reviewed_at))messageDetail(next.id);else{view='unreviewed';render()}})} }
 if(document.getElementById('oi-reply-email'))document.getElementById('oi-reply-email').onclick=async e=>run(e.target,async()=>{const mod=await import('./operations-inbox-reply.js?v=20261010-editor11');await mod.composeReply({org,thread,requests:related,onBack:()=>messageDetail(id,backId)})});
 const review=async email=>{try{const mod=await import('./operations-inbox-review.js?v=20261010-editor11');await mod.reviewEmail(email,{rows,entities,onBack:()=>messageDetail(id,backId),onSaved:async()=>{await reload();messageDetail(id,backId)}})}catch(e){notice(e.message)}};
 document.getElementById('oi-suggest').onclick=()=>review(m);main.querySelectorAll('[data-review-email]').forEach(b=>b.onclick=()=>review(messages.find(x=>x.id===b.dataset.reviewEmail)));
 document.getElementById('oi-quick-extract').onclick=()=>quickCreate({org,entities,message:m,onSaved:async()=>{await reload();messageDetail(id,backId)}});
 document.getElementById('oi-extract').onclick=()=>{const selection=window.getSelection()?.toString().trim();editor(null,selection?{...m,body:selection}:m)};document.getElementById('oi-attach').onclick=()=>linkRequest(m,backId);document.getElementById('oi-reviewed').onclick=e=>run(e.target,async()=>{await checked(supabase.from('operations_messages').update({reviewed_at:m.reviewed_at?null:new Date().toISOString()}).eq('id',id).select().single());await reload();view='unreviewed';render()});main.querySelectorAll('[data-request]').forEach(b=>b.onclick=()=>fastTask(b.dataset.request))}
function linkRequest(message,backId){linkPicker('Attach to request',rows.filter(r=>!links.some(l=>l.message_id===message.id&&l.request_id===r.id)).map(r=>({id:r.id,label:`${r.request_number} · ${r.title}`})),async id=>{await checked(supabase.from('operations_request_messages').insert({organization_id:org,request_id:id,message_id:message.id}));await reload();messageDetail(message.id,backId)},()=>messageDetail(message.id,backId))}
function linkMessage(request){linkPicker('Link captured conversation',messages.filter(m=>!links.some(l=>l.message_id===m.id&&l.request_id===request.id)).map(m=>({id:m.id,label:`${m.subject||'No subject'} · ${m.sender}`})),async id=>{await checked(supabase.from('operations_request_messages').insert({organization_id:org,request_id:request.id,message_id:id}));await reload();detail(request.id,'conversations')},()=>detail(request.id,'conversations'))}
function linkPicker(title,items,save,back){main.innerHTML=header(title,'<button class="secondary" id="oi-back">Back</button>')+`<div class="oi-form">${input('Search','oi-link-search')}<div id="oi-link-list"></div></div>`;document.getElementById('oi-back').onclick=back;const draw=q=>{const host=document.getElementById('oi-link-list');host.innerHTML=items.filter(x=>x.label.toLowerCase().includes(q.toLowerCase())).map(x=>`<button class="oi-related" data-id="${x.id}">${esc(x.label)}</button>`).join('')||'<div class="oi-empty">No matches</div>';host.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>run(b,()=>save(b.dataset.id)))};draw('');document.getElementById('oi-link-search').oninput=e=>draw(e.target.value)}
window.nodaraOperationsInbox={open,openRequest:async(id,expectedOrg)=>{await open();if(expectedOrg&&expectedOrg!==org){notice('Switch to the workspace for this reminder to open its request.');return;}if(rows.some(r=>r.id===id))await fastTask(id);else notice('This request is unavailable in your current workspace.')}};

function renderQueue(list){return '<div class="oi-task-queue">'+(list.map(r=>`<article class="oi-task-row ${late(r)?'oi-overdue':''}"><button class="oi-task-main" data-quick-task="${r.id}"><div class="oi-card-top"><b>${esc(r.request_number)}</b><span>${esc(types[r.request_type])}</span></div><h3>${esc(r.title)}</h3><p>${esc(r.customer_name||'Customer not assigned')} · ${esc(r.owner_name||'Unassigned')}</p><div class="oi-next">${esc(r.next_action||'Set the next action')}</div>${r.waiting_on?`<small>Waiting on ${esc(r.waiting_on)}</small>`:''}${r.follow_up_at?`<small>Reminder ${esc(when(r.follow_up_at))}</small>`:''}${r.due_at?`<small>Due ${esc(when(r.due_at))}</small>`:''}</button><div class="oi-task-actions"><span class="oi-flag">${esc(stages[r.status])}</span><button class="secondary" data-inline-status="${r.status==='NEW'?'WORKING':r.status==='WORKING'?'WAITING':'WORKING'}" data-task-id="${r.id}">${r.status==='NEW'?'Start':r.status==='WORKING'?'Wait':'Resume'}</button><button class="secondary" data-quick-task="${r.id}">Actions · Notes</button><button class="secondary" data-request="${r.id}">Open</button></div></article>`).join('')||'<div class="card oi-empty">Your queue is clear. Add a task or review an incoming conversation.</div>')+'</div>';}
async function fastTask(id,onSaved=render){const r=rows.find(x=>x.id===id);if(!r)return;await quickTask(r,{org,team,entities,onDeleted:async()=>{await reload();render()},onSourcesChanged:async()=>{links=await allRows('operations_request_messages','created_at',['request_id','message_id']);render()},onLinkEmail:request=>pickTaskEmail(request,{org,messages:messages.filter(m=>!links.some(l=>l.request_id===request.id&&l.message_id===m.id)),onSaved:async()=>{await reload();render();await fastTask(request.id)}}),onChecklist:async(id,items)=>{checklistRows=checklistRows.filter(x=>x.request_id!==id).concat(items);if(main.querySelector('.oi-workspace'))render()},onSaved:async(saved,note)=>{if(note){noteRows=noteRows.filter(x=>x.id!==note.id);noteRows.push(note)}rows=rows.map(x=>x.id===saved.id?{...saved}:x);await onSaved()},onFull:detail,onConversation:openTaskConversation,onReply:replyTask,hasConversation:taskEmails(id).length>0,sourceEmails:taskEmails(id),hasReply:taskEmails(id).some(m=>m.source==='GMAIL'),onRecord:openFastRecord});}
async function openFastRecord(link,requestId){try{if(link.kind==='transport_orders'){window.nodaraSetActive?.('ops_pickups');await window.nodaraOperations.openTransportOrder(link.id)}else if(link.kind==='shipments'){const mod=await import('./shipment-canonical-v52.js?v=20260927-awbcal1');await mod.openShipmentCanonical(link.id)}else if(link.kind==='warehouse_receipts'){await window.nodaraOpenCanonicalWR(link.id,'record')}else{await window.nodaraCROpen(link.id)}const back=document.createElement('button');back.className='secondary oi-context-back';back.textContent='Back to request';back.onclick=()=>{window.nodaraSetActive?.('ops_inbox');detail(requestId)};main.prepend(back)}catch(e){notice(e.message)}}
async function trashMessage(id){try{const m=messages.find(x=>x.id===id);if(!m)return;const ids=threadMessages(m).filter(x=>!x.deleted_at).map(x=>x.id);if(!ids.length)return;await checked(supabase.from('operations_messages').update({deleted_at:new Date().toISOString()}).eq('organization_id',org).in('id',ids));await reload();render();undoToast('Conversation moved to NODARA Trash',async()=>{await checked(supabase.from('operations_messages').update({deleted_at:null}).eq('organization_id',org).in('id',ids));await reload();render()})}catch(e){notice(e.message)}}
async function restoreMessage(id){const m=messages.find(x=>x.id===id);if(!m)return;const ids=threadMessages(m).filter(x=>x.deleted_at).map(x=>x.id);await checked(supabase.from('operations_messages').update({deleted_at:null}).eq('organization_id',org).in('id',ids));await reload();render();}
function purgeTrash({taskId,messageId,empty=false}){
 const task=deletedTasks.find(r=>r.id===taskId),message=messages.find(m=>m.id===messageId&&m.deleted_at);if(!empty&&!task&&!message)return;
 const before=new Date().toISOString(),messageIds=message?messages.filter(m=>m.deleted_at&&groupKey(m)===groupKey(message)).map(m=>m.id):[];
 const count=empty?deletedTasks.length+new Set(messages.filter(m=>m.deleted_at).map(groupKey)).size:1;
 const {root,close,run}=drawer(empty?'Empty Trash':'Delete permanently',`<div class="oi-purge-summary"><b>${empty?`Permanently delete ${count} item${count===1?'':'s'}?`:esc(task?.title||message?.subject||'This conversation')}</b><p>This cannot be undone. ${empty||task?'Deleted tasks, their instructions, checklist, notes and history will be removed. ':''}${empty||message?'Captured conversations in Trash will be removed from NODARA. ':''}</p><p>Original Gmail emails and linked shipment, transport and warehouse records are kept.</p></div><div class="oi-edit-actions"><button class="secondary" id="oi-purge-cancel">Cancel</button><button class="oi-delete-confirm" id="oi-purge-confirm">${empty?'Empty Trash':'Delete permanently'}</button></div>`);
 root.querySelector('#oi-purge-cancel').onclick=close;root.querySelector('#oi-purge-cancel').focus();root.querySelector('#oi-purge-confirm').onclick=e=>run(e.target,async()=>{await checked(supabase.rpc('nodara_purge_inbox_trash',{p_org:org,p_task_ids:task?[task.id]:[],p_message_ids:messageIds,p_empty:empty,p_before:empty?before:null}));await reload();render();close();});
}
function renderTrash(){const seen=new Set();const list=messages.filter(m=>m.deleted_at&&[m.subject,m.sender,m.body].join(' ').toLowerCase().includes(query.toLowerCase())).filter(m=>{if(seen.has(groupKey(m)))return false;seen.add(groupKey(m));return true});return `<div class="oi-message-list"><div class="oi-triage-intro"><div class="oi-trash-heading"><h2>NODARA Trash</h2><button class="secondary oi-trash-danger" id="oi-empty-trash" ${deletedTasks.length||messages.some(m=>m.deleted_at)?'':'disabled'}>${icon('trash')} Empty Trash</button></div><p class="muted">Removed from your captured inbox. Restore deleted tasks and conversations here. Linked emails and transaction records are kept.</p></div><h3>Tasks</h3>${deletedTasks.filter(r=>[r.title,r.request_number,r.customer_name].join(' ').toLowerCase().includes(query.toLowerCase())).map(r=>`<div class="oi-swipe-row"><div class="oi-message"><b>${esc(r.title)}</b><span>Task · ${esc(r.request_number)}${r.customer_name?' · '+esc(r.customer_name):''}</span></div><div class="oi-trash-actions"><button class="secondary" data-restore-task="${r.id}">Restore</button><button class="oi-trash-danger" data-purge-task="${r.id}" aria-label="Delete ${esc(r.title)} permanently">${icon('trash')}<span>Delete permanently</span></button></div></div>`).join('')||'<div class="card oi-empty">No deleted tasks.</div>'}<h3>Conversations</h3>${list.map(m=>`<div class="oi-swipe-row"><button class="oi-message" data-message="${m.id}"><b>${esc(m.subject||'No subject')}</b><span>${esc(m.sender)}</span></button><div class="oi-trash-actions"><button class="secondary" data-restore-message="${m.id}">Restore</button><button class="oi-trash-danger" data-purge-message="${m.id}" aria-label="Delete ${esc(m.subject||'conversation')} permanently">${icon('trash')}<span>Delete permanently</span></button></div></div>`).join('')||'<div class="card oi-empty">No deleted conversations.</div>'}</div>`;}

const dayKey=d=>{const date=new Date(d);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`};
function cardUpdate(r){const note=noteRows.filter(x=>x.request_id===r.id).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at))[0];return note?`<div class="oi-card-update"><small>Latest note</small><p>${esc(note.body)}</p></div>`:'';}
function calendarEvents(list){return list.flatMap(r=>[['due_at','Due'],['follow_up_at','Reminder']].filter(([field])=>r[field]).map(([field,label])=>({r,field,label,date:new Date(r[field])}))).sort((a,b)=>a.date-b.date);}
function renderCalendar(list){const events=calendarEvents(list),start=new Date(calendarMonth);start.setDate(1-start.getDay());const selected=dayKey(calendarDay),agenda=events.filter(e=>dayKey(e.date)===selected);return `<section class="oi-calendar"><header class="oi-calendar-head"><h2>${esc(calendarMonth.toLocaleDateString(undefined,{month:'long',year:'numeric'}))}</h2><div class="oi-actions"><button class="secondary" id="oi-cal-prev" aria-label="Previous month">←</button><button class="secondary" id="oi-cal-today">Today</button><button class="secondary" id="oi-cal-next" aria-label="Next month">→</button></div></header><div class="oi-calendar-week">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=>`<span>${d}</span>`).join('')}</div><div class="oi-calendar-grid">${Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);const key=dayKey(d),items=events.filter(e=>dayKey(e.date)===key);return `<button class="oi-calendar-day ${d.getMonth()!==calendarMonth.getMonth()?'oi-other-month':''} ${key===dayKey(new Date())?'oi-calendar-today':''}" data-calendar-day="${key}" aria-pressed="${selected===key}" aria-label="${esc(d.toLocaleDateString())}, ${items.length} events"><b>${d.getDate()}</b><span class="oi-calendar-count">${items.length?items.length+' events':''}</span>${items.slice(0,2).map(e=>`<span class="oi-calendar-event">${e.label==='Reminder'?'◷':'•'} ${esc(e.r.title)}</span>`).join('')}${items.length>2?`<small>+${items.length-2} more</small>`:''}</button>`}).join('')}</div><section class="oi-calendar-agenda"><h3>${esc(calendarDay.toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'}))}</h3>${agenda.map(e=>`<button class="oi-related" data-quick-task="${e.r.id}"><small>${esc(e.date.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}))} · ${e.label}</small><b>${esc(e.r.title)}</b><span>${esc(e.r.request_number)} · ${esc(e.r.customer_name)}</span></button>`).join('')||'<p class="muted">No scheduled work for this day.</p>'}<p class="muted">${list.filter(r=>!r.due_at&&!r.follow_up_at).length} requests have no date. Calendar follows your current filters.</p></section></section>`;}
function bindCalendar(){main.querySelectorAll('[data-calendar-day]').forEach(b=>b.onclick=()=>{calendarDay=new Date(b.dataset.calendarDay+'T12:00:00');render()});const move=n=>{calendarMonth=new Date(calendarMonth.getFullYear(),calendarMonth.getMonth()+n,1);calendarDay=new Date(calendarMonth);render()};const prev=document.getElementById('oi-cal-prev');if(prev){prev.onclick=()=>move(-1);document.getElementById('oi-cal-next').onclick=()=>move(1);document.getElementById('oi-cal-today').onclick=()=>{calendarDay=new Date();calendarMonth=new Date(calendarDay.getFullYear(),calendarDay.getMonth(),1);render()}}}
function drawReminders(){let host=document.getElementById('oi-reminder-alerts');const due=rows.filter(r=>active(r)&&r.follow_up_at&&new Date(r.follow_up_at)<=new Date()).sort((a,b)=>new Date(a.follow_up_at)-new Date(b.follow_up_at));if(!due.length){host?.remove();return;}if(!host){host=document.createElement('section');host.id='oi-reminder-alerts';host.className='oi-reminder-alerts';host.setAttribute('aria-label','Due reminders');document.body.append(host)}const key=due.map(r=>r.id+':'+r.follow_up_at).join('|');if(host.dataset.key===key)return;host.dataset.key=key;host.innerHTML=`<details><summary>◷ ${due.length} reminder${due.length===1?'':'s'} due</summary><div class="oi-reminder-items">${due.map(r=>`<article><button class="oi-reminder-open" data-reminder-open="${r.id}"><b>${esc(r.title)}</b><small>${esc(r.request_number)} · ${esc(when(r.follow_up_at))}</small></button><div><button class="secondary" data-reminder-snooze="${r.id}">Snooze 1h</button><button class="secondary" data-reminder-done="${r.id}">Dismiss reminder</button></div></article>`).join('')}</div></details>`;host.querySelectorAll('[data-reminder-open]').forEach(b=>b.onclick=async()=>{if(window.__nodaraRoute!=='ops_inbox')await open();fastTask(b.dataset.reminderOpen)});host.querySelectorAll('[data-reminder-snooze],[data-reminder-done]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{const id=b.dataset.reminderSnooze||b.dataset.reminderDone;const saved=await checked(supabase.from('operations_requests').update({follow_up_at:b.dataset.reminderSnooze?new Date(Date.now()+3600000).toISOString():null}).eq('organization_id',org).eq('id',id).select().single());rows=rows.map(r=>r.id===id?saved:r);drawReminders();if(window.__nodaraRoute==='ops_inbox'&&main.querySelector('.oi-workspace')&&!document.querySelector('.oi-drawer-backdrop'))render()}catch(e){b.disabled=false;notice(e.message)}});}
function startReminders(){if(reminderTimer)return;let ticks=0,busy=false;reminderTimer=setInterval(async()=>{if(busy)return;busy=true;try{if(await getCurrentOrganizationId()!==org){document.getElementById('oi-reminder-alerts')?.remove();return;}drawReminders();if(++ticks%2===0&&!document.hidden){const refreshed=await allRows('operations_requests');deletedTasks=refreshed.filter(r=>r.deleted_at);rows=refreshed.filter(r=>!r.deleted_at);drawReminders()}}catch{document.getElementById('oi-reminder-alerts')?.remove()}finally{busy=false}},30000);}
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&window.__nodaraRoute==='ops_inbox')drawReminders()});

function checkProgress(r){const steps=checklistRows.filter(x=>x.request_id===r.id);return steps.length?`<div class="oi-card-check"><progress max="${steps.length}" value="${steps.filter(x=>x.done).length}"></progress><small>${steps.filter(x=>x.done).length}/${steps.length} tasks</small></div>`:'';}

function taskEmails(id){const ids=links.filter(l=>l.request_id===id).map(l=>l.message_id);return messages.filter(m=>ids.includes(m.id)&&!m.deleted_at).sort((a,b)=>new Date(a.received_at)-new Date(b.received_at));}
function openTaskConversation(id,messageId){const list=taskEmails(id);if(list.length)messageDetail(messageId||list.at(-1).id,id);else detail(id,'conversations');}
async function replyTask(id){try{const list=taskEmails(id).filter(m=>m.source==='GMAIL');if(!list.length)return notice('No Gmail conversation is linked.');const mod=await import('./operations-inbox-reply.js?v=20261010-editor11');await mod.composeReply({org,thread:threadMessages(list.at(-1)).filter(m=>!m.deleted_at),requests:[rows.find(r=>r.id===id)]});}catch(e){notice(e.message)}}
function bindFloatingFilters(keepOpen=false){const button=document.getElementById('oi-filter-toggle'),panel=document.getElementById('oi-filter-popover');const close=()=>{panel.hidden=true;button.setAttribute('aria-expanded','false');};const toggle=()=>{panel.hidden=!panel.hidden;button.setAttribute('aria-expanded',String(!panel.hidden));if(!panel.hidden){const rect=button.getBoundingClientRect();panel.style.top=Math.max(12,Math.min(rect.bottom+8,innerHeight-panel.offsetHeight-16))+'px';panel.style.left=Math.max(12,Math.min(rect.right-panel.offsetWidth,innerWidth-panel.offsetWidth-12))+'px';panel.tabIndex=-1;panel.focus({preventScroll:true});}};button.onclick=toggle;if(keepOpen)toggle();document.getElementById('oi-filter-close').onclick=()=>{close();button.focus();};filterEvents=new AbortController();document.addEventListener('pointerdown',e=>{if(!panel.contains(e.target)&&!button.contains(e.target))close();},{signal:filterEvents.signal});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!panel.hidden){close();button.focus();}},{signal:filterEvents.signal});}
function bindMailSelection(){const list=unreviewedQueue();const selectedKeys=new Set([...selectedMail].map(id=>messages.find(m=>m.id===id)).filter(Boolean).map(groupKey));const seen=new Set();selectedMail=new Set([...messages].sort((a,b)=>new Date(b.received_at)-new Date(a.received_at)).filter(m=>!m.deleted_at&&!m.reviewed_at&&selectedKeys.has(groupKey(m))).filter(m=>{const key=groupKey(m);if(seen.has(key))return false;seen.add(key);return true;}).map(m=>m.id));const count=document.getElementById('oi-selected-count');const sync=()=>{if(!count)return;main.querySelectorAll('[data-select-message]').forEach(c=>c.checked=selectedMail.has(c.dataset.selectMessage));count.textContent=selectedMail.size+' selected';document.getElementById('oi-bulk-review').disabled=!selectedMail.size;document.getElementById('oi-bulk-trash').disabled=!selectedMail.size;const all=document.getElementById('oi-select-all');all.checked=list.length>0&&list.every(m=>selectedMail.has(m.id));all.indeterminate=list.some(m=>selectedMail.has(m.id))&&!all.checked;};main.querySelectorAll('[data-select-message]').forEach(c=>c.onchange=()=>{c.checked?selectedMail.add(c.dataset.selectMessage):selectedMail.delete(c.dataset.selectMessage);sync();});const all=document.getElementById('oi-select-all');if(all)all.onchange=()=>{list.forEach(m=>all.checked?selectedMail.add(m.id):selectedMail.delete(m.id));main.querySelectorAll('[data-select-message]').forEach(c=>c.checked=selectedMail.has(c.dataset.selectMessage));sync();};for(const [id,kind] of [['oi-bulk-review','review'],['oi-bulk-trash','trash']]){const b=document.getElementById(id);if(b)b.onclick=()=>run(b,()=>bulkMessages(kind));}sync();}
async function bulkMessages(kind){const selected=[...selectedMail].map(id=>messages.find(m=>m.id===id)).filter(Boolean);const keys=new Set(selected.map(groupKey));const targets=messages.filter(m=>keys.has(groupKey(m))&&!m.deleted_at&&(kind==='trash'||!m.reviewed_at));if(!targets.length)return;const field=kind==='trash'?'deleted_at':'reviewed_at',stamp=new Date().toISOString(),done=[];try{for(let n=0;n<targets.length;n+=100){const batch=targets.slice(n,n+100);await checked(supabase.from('operations_messages').update({[field]:stamp}).eq('organization_id',org).in('id',batch.map(m=>m.id)));done.push(...batch);}}catch(e){if(!done.length)throw e;notice('Some emails could not be updated. Undo is available for those updated.');}selectedMail.clear();await reload();render();undoToast(`${new Set(done.map(groupKey)).size} conversations ${kind==='trash'?'moved to NODARA Trash':'marked no action'}`,async()=>{for(let n=0;n<done.length;n+=100){const ids=done.slice(n,n+100).map(m=>m.id);await checked(supabase.from('operations_messages').update({[field]:null}).eq('organization_id',org).eq(field,stamp).in('id',ids));}await reload();render();});}
