const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const text=v=>String(v??'').trim();
function qrUrl(value,size=220){return `https://api.qrserver.com/v1/create-qr-code/?size=${size}x${size}&margin=0&data=${encodeURIComponent(value)}`}
function refText(wr){const r=wr.references?.find(x=>x.is_primary)||wr.references?.[0];return r?.reference_value||wr.jobs?.reference||''}
function customer(wr){return wr.parties?.customer?.name||wr.customer?.name||''}
function labelId(wr,node,index,total){return text(node.uin||node.handling_unit_code)||`${wr.receipt_number}-${String(index+1).padStart(3,'0')}-${String(total).padStart(3,'0')}`}
function dims(n){const a=[n.length_in,n.width_in,n.height_in].map(Number);return a.every(Boolean)?`${a[0]} × ${a[1]} × ${a[2]} IN`:''}
function labelData(wr,node,index,total){const id=labelId(wr,node,index,total);return{id,qr:`NODARA|WR:${wr.receipt_number}|CARGO:${id}`,wr:wr.receipt_number,customer:customer(wr),reference:refText(wr),description:node.description||wr.jobs?.description||'',type:node.package_type||node.type||'CARGO',piece:`${index+1}/${total}`,qty:Number(node.quantity||1),uom:node.uom||node.package_type||'',weight:node.weight_lb?`${Number(node.weight_lb).toFixed(2)} LB`:'',dims:dims(node),sku:node.sku||node.part_number||'',lot:node.lot_number||'',serial:node.serial_number||''}}
function large(d){return `<article class="label l46"><header><div><span>NODARA · RECEIVING</span><strong>${esc(d.wr)}</strong></div><b>${esc(d.piece)}</b></header><main><section><div class="label-id">${esc(d.id)}</div><div class="customer">${esc(d.customer||'WAREHOUSE RECEIPT')}</div>${d.reference?`<div class="ref">REF · ${esc(d.reference)}</div>`:''}<div class="desc">${esc(d.description)}</div><div class="facts"><b>${esc(d.type)}</b><b>QTY ${esc(d.qty)} ${esc(d.uom)}</b>${d.weight?`<b>${esc(d.weight)}</b>`:''}${d.dims?`<b>${esc(d.dims)}</b>`:''}</div></section><img src="${qrUrl(d.qr,260)}"></main><footer>SCAN TO OPEN CARGO · ${esc(d.id)}</footer></article>`}
function small(d){return `<article class="label l21"><div class="small-copy"><strong>${esc(d.id)}</strong><b>${esc(d.wr)} · ${esc(d.piece)}</b><span>${esc(d.sku||d.description||d.type)}</span><span>QTY ${esc(d.qty)} ${esc(d.uom)}${d.lot?' · LOT '+esc(d.lot):''}${d.serial?' · SN '+esc(d.serial):''}</span></div><img src="${qrUrl(d.qr,150)}"></article>`}
export function printReceivingLabels({wr,cargo=[],size='4x6',selectedIds=null}={}){const roots=cargo.filter(x=>!x.parent_id),source=size==='2x1'?cargo:roots,filtered=selectedIds?.length?source.filter(x=>selectedIds.includes(x.id)):source;if(!filtered.length)throw new Error('No cargo available for labels.');const expanded=[];for(const n of filtered){const q=Math.max(1,Math.floor(Number(n.quantity||1)));for(let i=0;i<q;i++)expanded.push({...n,quantity:size==='2x1'?Number(n.quantity||1):1,__copy:i})}const total=expanded.length,html=expanded.map((n,i)=>(size==='2x1'?small:large)(labelData(wr,n,i,total))).join('');const w=window.open('','_blank','noopener,noreferrer');if(!w)throw new Error('Pop-up blocked. Allow pop-ups to print labels.');w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(wr.receipt_number)} labels</title><style>@page{margin:0;size:${size==='2x1'?'2in 1in':'4in 6in'}}*{box-sizing:border-box}html,body{margin:0;padding:0;font-family:Arial,Helvetica,sans-serif;color:#000}.label{page-break-after:always;overflow:hidden;background:#fff}.label:last-child{page-break-after:auto}.l46{width:4in;height:6in;padding:.18in;display:flex;flex-direction:column;border:1px solid #000}.l46 header{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:4px solid #000;padding-bottom:.09in}.l46 header span{display:block;font-size:10pt;font-weight:800;letter-spacing:.04em}.l46 header strong{display:block;font-size:27pt;line-height:1.05}.l46 header>b{font-size:28pt;background:#000;color:#fff;padding:.05in .1in}.l46 main{display:grid;grid-template-columns:1fr 1.35in;gap:.12in;padding:.13in 0;flex:1}.l46 main img{width:1.35in;height:1.35in;image-rendering:pixelated}.label-id{font-size:18pt;font-weight:900;overflow-wrap:anywhere}.customer{font-size:16pt;font-weight:900;margin-top:.08in}.ref{font-size:12pt;font-weight:800;margin-top:.08in}.desc{font-size:11pt;margin-top:.1in;max-height:1.2in;overflow:hidden}.facts{display:flex;flex-wrap:wrap;gap:.07in;margin-top:.16in}.facts b{border:2px solid #000;padding:.05in .07in;font-size:10pt}.l46 footer{border-top:3px solid #000;padding-top:.08in;font-size:9pt;font-weight:800}.l21{width:2in;height:1in;padding:.055in;display:grid;grid-template-columns:1fr .72in;gap:.04in;border:1px solid #000}.l21 img{width:.7in;height:.7in;align-self:center;justify-self:end;image-rendering:pixelated}.small-copy{min-width:0;display:flex;flex-direction:column;line-height:1.03}.small-copy strong{font-size:8.5pt;font-weight:900;overflow:hidden;white-space:nowrap}.small-copy b{font-size:7.5pt;margin-top:2px}.small-copy span{font-size:6.5pt;font-weight:700;overflow:hidden;white-space:nowrap;text-overflow:ellipsis;margin-top:2px}@media print{body{print-color-adjust:exact;-webkit-print-color-adjust:exact}}</style></head><body>${html}<script>window.onload=()=>setTimeout(()=>window.print(),450)<\/script></body></html>`);w.document.close();return expanded.length}
