import { supabase } from './supabase-client.js';
import { getCurrentOrganizationId } from './live-data.js';

const main=document.getElementById('main');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const css=document.createElement('style');css.textContent=`
.settings-system{max-width:1040px;margin:0 auto}.settings-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin-bottom:18px}.settings-head h1{margin:4px 0 5px}.settings-head p{margin:0;color:var(--muted)}.settings-tabs{display:flex;gap:8px;overflow:auto;margin:16px 0 20px}.settings-tab{border:1px solid var(--border);background:transparent;color:var(--muted);padding:9px 13px;border-radius:999px;white-space:nowrap}.settings-tab.active{background:#182235;color:#fff;border-color:#3e5d86}.settings-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.settings-card{border:1px solid var(--border);background:var(--panel,#0e131a);border-radius:20px;padding:17px}.settings-card h3{margin:0 0 3px}.settings-card>p{margin:0 0 16px;color:var(--muted);font-size:12px}.settings-fields{display:grid;grid-template-columns:1fr 1fr;gap:12px}.settings-field label{display:block;font-size:11px;color:var(--muted);margin-bottom:5px}.settings-field input,.settings-field select{width:100%;box-sizing:border-box}.settings-span2{grid-column:1/-1}.number-row{border:1px solid var(--border);border-radius:16px;padding:14px;margin:10px 0}.number-row-head{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:11px}.number-row-head b{font-size:15px}.number-preview{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;color:#8cc0ff;font-size:12px;margin-top:8px}.settings-savebar{position:sticky;bottom:calc(76px + env(safe-area-inset-bottom));margin-top:16px;padding:10px;border:1px solid var(--border);border-radius:16px;background:color-mix(in srgb,var(--panel,#0e131a) 92%,transparent);backdrop-filter:blur(16px);display:flex;justify-content:flex-end}.settings-savebar button{min-width:150px}.settings-note{font-size:11px;color:var(--muted);margin-top:8px}
@media(max-width:760px){.settings-head{display:block}.settings-grid,.settings-fields{grid-template-columns:1fr}.settings-span2{grid-column:auto}.settings-card{padding:14px}.number-row-head{align-items:flex-start}.settings-savebar{bottom:calc(88px + env(safe-area-inset-bottom))}}
`;document.head.appendChild(css);

const UNIT_CATS=['WEIGHT','DIMENSION','VOLUME','TEMPERATURE','DISTANCE','COUNT','PACKAGE'];
let state={tab:'units',org:null,catalog:[],profile:null,schemes:[]};
async function load(){state.org=await getCurrentOrganizationId();const [u,p,s]=await Promise.all([supabase.from('unit_catalog').select('code,name,symbol,category,active').eq('active',true).order('category').order('name'),supabase.from('organization_unit_profiles').select('*').eq('organization_id',state.org).eq('is_default',true).maybeSingle(),supabase.from('document_number_schemes').select('*').eq('organization_id',state.org).order('document_type')]);if(u.error)throw u.error;if(p.error)throw p.error;if(s.error)throw s.error;state.catalog=u.data||[];state.profile=p.data||{organization_id:state.org,profile_name:'Default',system_code:'IMPERIAL',is_default:true,weight_unit:'LB',dimension_unit:'IN',volume_unit:'CBM',temperature_unit:'F',distance_unit:'MI',default_quantity_uom:'PCS',currency_code:'USD',rounding:{weight:2,dimension:2,volume:3,currency:2}};state.schemes=s.data||[]}
const unitOpts=(cat,val)=>state.catalog.filter(x=>x.category===cat).map(x=>`<option value="${esc(x.code)}" ${x.code===val?'selected':''}>${esc(x.name)}${x.symbol?` · ${esc(x.symbol)}`:''}</option>`).join('');
function shell(){window.nodaraSetActive?.('settings_system');main.innerHTML=`<section class="settings-system"><div class="settings-head"><div><div class="eyebrow">SETTINGS</div><h1>System setup</h1><p>Control how NODARA measures cargo and generates operational document numbers.</p></div></div><div class="settings-tabs"><button class="settings-tab ${state.tab==='units'?'active':''}" data-stab="units">Units & formats</button><button class="settings-tab ${state.tab==='numbers'?'active':''}" data-stab="numbers">Document numbering</button></div><div id="settings-body"></div></section>`;main.querySelectorAll('[data-stab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.stab;shell();renderBody()});renderBody()}
function units(){const p=state.profile,r=p.rounding||{};return `<div class="settings-grid"><section class="settings-card"><h3>Measurement system</h3><p>These are the default units shown when people create and edit cargo.</p><div class="settings-fields"><div class="settings-field settings-span2"><label>System preset</label><select id="set-system"><option ${p.system_code==='IMPERIAL'?'selected':''}>IMPERIAL</option><option ${p.system_code==='METRIC'?'selected':''}>METRIC</option><option ${p.system_code==='CUSTOM'?'selected':''}>CUSTOM</option></select></div><div class="settings-field"><label>Weight</label><select id="set-weight">${unitOpts('WEIGHT',p.weight_unit)}</select></div><div class="settings-field"><label>Dimensions</label><select id="set-dimension">${unitOpts('DIMENSION',p.dimension_unit)}</select></div><div class="settings-field"><label>Volume</label><select id="set-volume">${unitOpts('VOLUME',p.volume_unit)}</select></div><div class="settings-field"><label>Temperature</label><select id="set-temperature">${unitOpts('TEMPERATURE',p.temperature_unit)}</select></div><div class="settings-field"><label>Distance</label><select id="set-distance">${unitOpts('DISTANCE',p.distance_unit)}</select></div><div class="settings-field"><label>Default quantity UOM</label><select id="set-qty">${unitOpts('COUNT',p.default_quantity_uom)}${unitOpts('PACKAGE',p.default_quantity_uom)}</select></div><div class="settings-field settings-span2"><label>Currency</label><input id="set-currency" value="${esc(p.currency_code||'USD')}" maxlength="3"></div></div></section><section class="settings-card"><h3>Rounding & display</h3><p>Keep calculations precise internally while controlling what users see.</p><div class="settings-fields"><div class="settings-field"><label>Weight decimals</label><input id="set-rw" type="number" min="0" max="6" value="${Number(r.weight??2)}"></div><div class="settings-field"><label>Dimension decimals</label><input id="set-rd" type="number" min="0" max="6" value="${Number(r.dimension??2)}"></div><div class="settings-field"><label>Volume decimals</label><input id="set-rv" type="number" min="0" max="6" value="${Number(r.volume??3)}"></div><div class="settings-field"><label>Currency decimals</label><input id="set-rc" type="number" min="0" max="4" value="${Number(r.currency??2)}"></div></div><div class="settings-note">NODARA can still convert between units; this profile controls the default operating/display units.</div></section></div><div class="settings-savebar"><button class="primary" id="save-units">Save system units</button></div>`}
const sample=s=>{const d=new Date(),yy=String(d.getFullYear()).slice(-2),yyyy=d.getFullYear(),mm=String(d.getMonth()+1).padStart(2,'0'),dd=String(d.getDate()).padStart(2,'0');let date=(s.date_format||'YYMMDD').replace('YYYY',yyyy).replace('YY',yy).replace('MM',mm).replace('DD',dd);const seq=String(s.starting_number||1).padStart(Number(s.sequence_padding||4),'0');return (s.format_template||'{PREFIX}-{DATE}-{SEQ}{SUFFIX}').replace('{PREFIX}',s.prefix||'').replace('{DATE}',date).replace('{SEQ}',seq).replace('{SUFFIX}',s.suffix||'').replace(/--+/g,'-').replace(/^-|-$/g,'')};
function numbers(){return `<section class="settings-card"><h3>Operational document numbers</h3><p>Edit the numbering scheme for WRs, CRs, shipments, transport orders, quotes and other NODARA records.</p>${state.schemes.map((s,i)=>`<div class="number-row" data-scheme="${esc(s.id)}"><div class="number-row-head"><div><b>${esc(s.name||s.document_type)}</b><div class="settings-note">${esc(s.document_type)}</div></div><label><input type="checkbox" data-k="is_active" ${s.is_active?'checked':''}> Active</label></div><div class="settings-fields"><div class="settings-field"><label>Prefix</label><input data-k="prefix" value="${esc(s.prefix||'')}"></div><div class="settings-field"><label>Suffix</label><input data-k="suffix" value="${esc(s.suffix||'')}"></div><div class="settings-field settings-span2"><label>Format</label><input data-k="format_template" value="${esc(s.format_template||'{PREFIX}-{DATE}-{SEQ}{SUFFIX}')}"></div><div class="settings-field"><label>Date format</label><select data-k="date_format"><option ${s.date_format==='YYMMDD'?'selected':''}>YYMMDD</option><option ${s.date_format==='YYYYMMDD'?'selected':''}>YYYYMMDD</option><option ${s.date_format==='YYMM'?'selected':''}>YYMM</option><option ${s.date_format==='YYYY'?'selected':''}>YYYY</option></select></div><div class="settings-field"><label>Sequence digits</label><input data-k="sequence_padding" type="number" min="1" max="12" value="${s.sequence_padding||4}"></div><div class="settings-field"><label>Reset</label><select data-k="reset_period">${['NONE','YEAR','MONTH','DAY'].map(x=>`<option ${s.reset_period===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="settings-field"><label>Start at</label><input data-k="starting_number" type="number" min="1" value="${s.starting_number||1}"></div><div class="settings-field settings-span2"><label><input type="checkbox" data-k="allow_manual_override" ${s.allow_manual_override?'checked':''}> Allow manual number override</label></div></div><div class="number-preview" data-preview>Preview · ${esc(sample(s))}</div></div>`).join('')||'<div class="notice">No numbering schemes are configured yet.</div>'}</section><div class="settings-savebar"><button class="primary" id="save-numbers">Save numbering</button></div>`}
function renderBody(){const body=document.getElementById('settings-body');if(!body)return;body.innerHTML=state.tab==='units'?units():numbers();if(state.tab==='units'){document.getElementById('set-system').onchange=e=>{if(e.target.value==='IMPERIAL'){document.getElementById('set-weight').value='LB';document.getElementById('set-dimension').value='IN';document.getElementById('set-temperature').value='F';document.getElementById('set-distance').value='MI'}if(e.target.value==='METRIC'){document.getElementById('set-weight').value='KG';document.getElementById('set-dimension').value='CM';document.getElementById('set-temperature').value='C';document.getElementById('set-distance').value='KM'}};document.getElementById('save-units').onclick=saveUnits}else{main.querySelectorAll('.number-row input,.number-row select').forEach(el=>el.oninput=updatePreview);document.getElementById('save-numbers').onclick=saveNumbers}}
async function saveUnits(){const b=document.getElementById('save-units');b.disabled=true;b.textContent='Saving…';const row={organization_id:state.org,profile_name:state.profile.profile_name||'Default',system_code:document.getElementById('set-system').value,is_default:true,weight_unit:document.getElementById('set-weight').value,dimension_unit:document.getElementById('set-dimension').value,volume_unit:document.getElementById('set-volume').value,temperature_unit:document.getElementById('set-temperature').value,distance_unit:document.getElementById('set-distance').value,default_quantity_uom:document.getElementById('set-qty').value,currency_code:document.getElementById('set-currency').value.trim().toUpperCase()||'USD',rounding:{weight:+document.getElementById('set-rw').value,dimension:+document.getElementById('set-rd').value,volume:+document.getElementById('set-rv').value,currency:+document.getElementById('set-rc').value},updated_at:new Date().toISOString()};const{error}=await supabase.from('organization_unit_profiles').upsert(row,{onConflict:'organization_id,profile_name'});if(error){alert(error.message);b.disabled=false;b.textContent='Save system units';return}state.profile=row;b.textContent='Saved ✓';setTimeout(()=>b.textContent='Save system units',1200);b.disabled=false}
function rowData(row){const id=row.dataset.scheme,s={...state.schemes.find(x=>x.id===id)};row.querySelectorAll('[data-k]').forEach(el=>s[el.dataset.k]=el.type==='checkbox'?el.checked:el.type==='number'?Number(el.value):el.value);return s}
function updatePreview(e){const row=e.target.closest('.number-row'),s=rowData(row);row.querySelector('[data-preview]').textContent='Preview · '+sample(s)}
async function saveNumbers(){const b=document.getElementById('save-numbers');b.disabled=true;b.textContent='Saving…';for(const row of main.querySelectorAll('.number-row')){const s=rowData(row);const{error}=await supabase.from('document_number_schemes').update({prefix:s.prefix,suffix:s.suffix,format_template:s.format_template,date_format:s.date_format,sequence_padding:s.sequence_padding,reset_period:s.reset_period,starting_number:s.starting_number,allow_manual_override:s.allow_manual_override,is_active:s.is_active,updated_at:new Date().toISOString()}).eq('id',s.id);if(error){alert(error.message);b.disabled=false;b.textContent='Save numbering';return}}b.textContent='Saved ✓';setTimeout(()=>b.textContent='Save numbering',1200);b.disabled=false}
export async function openSystemSettings(tab='units'){state.tab=tab;try{await load();shell()}catch(e){main.innerHTML=`<div class="eyebrow">SETTINGS</div><h1 class="title">System setup</h1><div class="notice warning">${esc(e.message)}</div>`}}
window.nodaraSystemSettings=openSystemSettings;

function injectSettingsLinks(){document.querySelectorAll('.rail-flyout[data-module="settings"] .rail-flyout-list,.mobile-module-sheet .mobile-sheet-list').forEach(list=>{if(list.dataset.systemLinks==='1')return;const looksSettings=[...list.querySelectorAll('button span')].some(x=>x.textContent==='Lists & Options');if(!looksSettings)return;list.dataset.systemLinks='1';const a=document.createElement('button');a.innerHTML='<span>System & Units</span><i>›</i>';a.onclick=()=>{document.querySelector('.rail-flyout,.mobile-module-sheet')?.remove();openSystemSettings('units')};const n=document.createElement('button');n.innerHTML='<span>Document Numbers</span><i>›</i>';n.onclick=()=>{document.querySelector('.rail-flyout,.mobile-module-sheet')?.remove();openSystemSettings('numbers')};list.prepend(n);list.prepend(a)})}
new MutationObserver(injectSettingsLinks).observe(document.body,{childList:true,subtree:true});setTimeout(injectSettingsLinks,500);
