import { supabase } from './supabase-client.js';
const main=document.getElementById('main');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function org(){const{data,error}=await supabase.rpc('bootstrap_workspace',{p_name:'NODARA Workspace'});if(error)throw error;return data}
async function resolve(){const title=main.querySelector('h1.title')?.textContent?.trim();if(!title||/^New\b/i.test(title))return null;const candidates=[];if(/^WR-/i.test(title))candidates.push(['WR','warehouse_receipts','receipt_number']);if(/^CR-/i.test(title))candidates.push(['CR','cargo_releases','release_number']);candidates.push(['SHIPMENT','shipments','shipment_number'],['TRANSPORT','transport_orders','order_number']);for(const[type,table,col]of candidates){try{const{data,error}=await supabase.from(table).select('id').eq(col,title).maybeSingle();if(!error&&data?.id)return{type,id:data.id,title}}catch{}}return null}
async function loadNotes(target){const organization_id=await org();const{data,error}=await supabase.from('transaction_notes').select('id,body,visibility,pinned,created_at,created_by').eq('organization_id',organization_id).eq('transaction_type',target.type).eq('transaction_id',target.id).order('pinned',{ascending:false}).order('created_at',{ascending:false});if(error)throw error;return data||[]}
async function openPanel(target){document.querySelector('.transaction-notes-overlay')?.remove();const overlay=document.createElement('div');overlay.className='transaction-notes-overlay';overlay.innerHTML=`<div class="transaction-notes-modal"><div class="record-commandbar"><div><div class="eyebrow">${esc(target.title)}</div><h2>Notes</h2></div><button class="subtle" data-notes-close>×</button></div><div data-notes-list><div class="muted">Loading notes…</div></div><section class="record-section"><div class="field"><label>Add note</label><textarea data-note-body rows="4" placeholder="Operational note, follow-up, exception, customer communication…"></textarea></div><div class="record-footer-actions"><select data-note-visibility><option value="INTERNAL">Internal</option><option value="CUSTOMER">Customer-visible</option></select><button class="primary" data-note-save>Save note</button></div></section></div>`;document.body.appendChild(overlay);overlay.querySelector('[data-notes-close]').onclick=()=>overlay.remove();overlay.addEventListener('click',e=>{if(e.target===overlay)overlay.remove()});const list=overlay.querySelector('[data-notes-list]');async function paint(){const notes=await loadNotes(target);list.innerHTML=notes.length?`<div class="transaction-note-list">${notes.map(n=>`<article class="transaction-note"><div><span class="status-pill">${esc(n.visibility)}</span>${n.pinned?'<span class="status-pill">PINNED</span>':''}<small>${new Date(n.created_at).toLocaleString()}</small></div><p>${esc(n.body)}</p><button class="subtle compact-btn" data-note-delete="${n.id}">Delete</button></article>`).join('')}</div>`:'<div class="empty compact">No notes yet.</div>';list.querySelectorAll('[data-note-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this note?'))return;const{error}=await supabase.from('transaction_notes').delete().eq('id',b.dataset.noteDelete);if(error)return alert(error.message);await paint()});const badge=document.querySelector('[data-transaction-notes-open]');if(badge)badge.textContent=`Notes${notes.length?` ${notes.length}`:''}`}
await paint();overlay.querySelector('[data-note-save]').onclick=async()=>{const body=overlay.querySelector('[data-note-body]').value.trim();if(!body)return;const b=overlay.querySelector('[data-note-save]');b.disabled=true;const{error}=await supabase.from('transaction_notes').insert({organization_id:await org(),transaction_type:target.type,transaction_id:target.id,body,visibility:overlay.querySelector('[data-note-visibility]').value});if(error){b.disabled=false;return alert(error.message)}overlay.querySelector('[data-note-body]').value='';b.disabled=false;await paint()}}
async function enhance(){if(main.querySelector('[data-transaction-notes-open]'))return;const target=await resolve();if(!target)return;const host=main.querySelector('.record-commandbar .context-actions,.record-commandbar,.record-header');if(!host)return;const b=document.createElement('button');b.type='button';b.dataset.transactionNotesOpen='1';b.className='secondary compact-btn';b.textContent='Notes';b.onclick=()=>openPanel(target);host.appendChild(b);try{const notes=await loadNotes(target);if(notes.length)b.textContent=`Notes ${notes.length}`}catch{}}
let q=false;new MutationObserver(()=>{if(q)return;q=true;requestAnimationFrame(async()=>{q=false;await enhance()})}).observe(main,{childList:true,subtree:true});setTimeout(enhance,600);
const style=document.createElement('style');style.textContent=`.transaction-notes-overlay{position:fixed;inset:0;z-index:10060;background:rgba(0,0,0,.72);display:grid;place-items:center;padding:18px}.transaction-notes-modal{width:min(760px,100%);max-height:90dvh;overflow:auto;background:var(--panel,#0b1119);border:1px solid var(--border);border-radius:18px;padding:16px}.transaction-note-list{display:grid;gap:8px;margin:12px 0}.transaction-note{border:1px solid var(--border);border-radius:12px;padding:12px}.transaction-note>div{display:flex;gap:6px;align-items:center}.transaction-note small{margin-left:auto;color:var(--muted)}.transaction-note p{white-space:pre-wrap;margin:10px 0}`;document.head.appendChild(style);
