import './transaction-ux-bootstrap.js?v=20260908-guided2';
import { supabase } from './supabase-client.js';
const words={one:1,two:2,three:3,four:4,five:5,six:6,seven:7,eight:8,nine:9,ten:10};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=s=>{s=String(s||'').trim().toLowerCase();return Number(words[s]??s)};
function parse(t){const x=String(t||'').trim(),p={action:/create\s+(a\s+)?(warehouse\s+receipt|wr)/i.test(x)?'create_wr':'fill'};let m;
 if((m=x.match(/(?:customer|account)(?:\s+is|\s+for)?\s+(.+?)(?=\s+(?:shipper|consignee|carrier|driver|reference|po|bol|pro|tracking|received|we received|location|put|weight|dimensions|$))/i)))p.customer=m[1].trim();
 else if((m=x.match(/create\s+(?:a\s+)?(?:warehouse\s+receipt|wr)\s+for\s+(.+?)(?=\s+(?:shipper|consignee|carrier|driver|reference|po|bol|pro|tracking|received|we received|location|put|weight|dimensions|$))/i)))p.customer=m[1].trim();
 for(const r of ['shipper','consignee','carrier','driver']){m=x.match(new RegExp(`${r}(?:\\s+is)?\\s+(.+?)(?=\\s+(?:customer|account|shipper|consignee|carrier|driver|reference|po|bol|pro|tracking|received|we received|location|put|weight|dimensions|$))`,'i'));if(m)p[r]=m[1].trim()}
 if((m=x.match(/\b(PO|BOL|PRO|TRACKING|SO|ASN|ENTRY|BOOKING|INVOICE)\s*(?:number\s*)?(?:is\s*)?([A-Z0-9._\/-]+)/i))){p.reference_type=m[1].toUpperCase();p.reference=m[2]}
 if((m=x.match(/(?:received|we received|cargo is)?\s*([0-9]+|one|two|three|four|five|six|seven|eight|nine|ten)\s+(pallets?|crates?|skids?|boxes?|cartons?|drums?|bags?|pieces?)/i))){p.quantity=num(m[1]);p.package_type=m[2].replace(/s$/i,'').toUpperCase();if(p.package_type==='BOXE')p.package_type='BOX'}
 if((m=x.match(/([0-9]+(?:\.[0-9]+)?)\s*(kg|kilos?|kilograms?|lb|lbs|pounds?)\b/i))){p.weight=Number(m[1]);p.weight_unit=/kg|kilo/i.test(m[2])?'KG':'LB'}
 if((m=x.match(/([0-9]+(?:\.[0-9]+)?)\s*(?:x|by)\s*([0-9]+(?:\.[0-9]+)?)\s*(?:x|by)\s*([0-9]+(?:\.[0-9]+)?)\s*(inches?|in|cm|centimeters?)?/i))){p.length=Number(m[1]);p.width=Number(m[2]);p.height=Number(m[3]);p.dimension_unit=/cm|cent/i.test(m[4]||'')?'CM':'IN'}
 if((m=x.match(/(?:location|put (?:it|them|cargo)?\s*(?:in|at)?|store (?:it|them|cargo)?\s*(?:in|at)?)\s+([A-Z0-9._\/-]+)/i)))p.location=m[1];
 if((m=x.match(/(?:description|commodity)(?:\s+is)?\s+(.+?)(?=\s+(?:location|reference|po|bol|pro|tracking|weight|dimensions|$))/i)))p.description=m[1].trim();
 if(/\b(?:dg|hazmat|dangerous goods)\b/i.test(x))p.dg=true;
 return p}
function overlay(transcript,p){document.querySelector('.voice-command-overlay')?.remove();const o=document.createElement('div');o.className='voice-command-overlay';const fields=Object.entries(p).filter(([k,v])=>k!=='action'&&v!==undefined&&v!==null&&v!=='');o.innerHTML=`<div class="voice-command-panel"><div class="voice-command-head"><div><div class="eyebrow">NODARA VOICE</div><h2>${p.action==='create_wr'?'Build Warehouse Receipt':'Apply voice input'}</h2></div><button class="voice-command-close">×</button></div><div class="voice-transcript">“${esc(transcript)}”</div><div class="voice-fields">${fields.map(([k,v])=>`<div class="voice-field"><span>${esc(k.replaceAll('_',' '))}</span><b>${esc(v)}</b></div>`).join('')}</div><div class="voice-command-actions"><button class="secondary" data-voice-cancel>Cancel</button><button class="primary" data-voice-apply>Apply</button></div></div>`;document.body.appendChild(o);o.querySelector('.voice-command-close').onclick=()=>o.remove();o.querySelector('[data-voice-cancel]').onclick=()=>o.remove();o.querySelector('[data-voice-apply]').onclick=async()=>{const b=o.querySelector('[data-voice-apply]');b.disabled=true;b.textContent='Applying…';try{await apply(p);o.remove()}catch(e){b.disabled=false;b.textContent='Try again';alert(e.message)}}}
const wait=(sel,ms=6000)=>new Promise((res,rej)=>{const now=document.querySelector(sel);if(now)return res(now);const end=Date.now()+ms,t=setInterval(()=>{const n=document.querySelector(sel);if(n){clearInterval(t);res(n)}else if(Date.now()>end){clearInterval(t);rej(new Error(`Could not find ${sel}`))}},80)});
async function chooseCreateParty(role,name){if(!name)return;const sel=document.querySelector(`select[data-wrc-party="${role}"]`);if(!sel)return;const hit=[...sel.options].find(o=>o.value&&o.textContent.toLowerCase().includes(name.toLowerCase()));if(hit){sel.value=hit.value;sel.dispatchEvent(new Event('change',{bubbles:true}));return}alert(`${name} is not in Entity Master yet. Type it into the smart party field or create the entity from the party editor.`)}
async function applyCreate(p){
 if(!document.querySelector('.wr-create-shell')){window.nodaraReceive?.();await wait('.wr-create-shell')}
 for(const [role,name] of [['customer',p.customer],['shipper',p.shipper],['consignee',p.consignee],['carrier',p.carrier],['driver',p.driver]])if(name)await chooseCreateParty(role,name);
 if(p.description){const d=document.getElementById('wrc-desc');if(d){d.value=p.description;d.dispatchEvent(new Event('input',{bubbles:true}))}}
 if(p.reference){const val=document.querySelector('[data-wrc-ref-value="0"]'),type=document.querySelector('[data-wrc-ref-type="0"]');if(type)type.value=p.reference_type==='INVOICE'?'INVOICE':p.reference_type;if(val){val.value=p.reference;val.dispatchEvent(new Event('input',{bubbles:true}))}}
 if(p.package_type||p.quantity||p.weight!=null||p.length!=null||p.location){document.querySelector('[data-wrc-tab="cargo"]')?.click();await new Promise(r=>setTimeout(r,80));if(!document.getElementById('wrc-type'))document.getElementById('wrc-add-cargo')?.click();await wait('#wrc-type');if(p.package_type)document.getElementById('wrc-type').value=p.package_type;if(p.quantity)document.getElementById('wrc-qty').value=p.quantity;if(p.weight!=null)document.getElementById('wrc-weight').value=p.weight;if(p.length!=null){document.getElementById('wrc-l').value=p.length;document.getElementById('wrc-w').value=p.width;document.getElementById('wrc-h').value=p.height}if(p.location){const loc=document.getElementById('wrc-location');if(loc){const match=[...loc.options].find(o=>o.textContent.toLowerCase().includes(p.location.toLowerCase()));if(match)loc.value=match.value}}}
 window.dispatchEvent(new Event('nodara:voice-applied'));
}
async function apply(p){if(p.action==='create_wr'||document.querySelector('.wr-create-shell'))return applyCreate(p);const focused=document.activeElement;if(focused&&['INPUT','TEXTAREA','SELECT'].includes(focused.tagName)){if(focused.tagName==='SELECT'){const hit=[...focused.options].find(o=>o.value&&o.textContent.toLowerCase().includes((p.reference||p.customer||p.description||'').toLowerCase()));if(hit)focused.value=hit.value}else if(p.reference||p.description)focused.value=p.reference||p.description;focused.dispatchEvent(new Event('input',{bubbles:true}));focused.dispatchEvent(new Event('change',{bubbles:true}));return}alert('Use the microphone beside a field for precise voice entry, or open New Receipt and speak the full receiving command.')}
function start(){const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SpeechRecognition)return alert('Voice commands are not supported by this browser.');const r=new SpeechRecognition();r.lang='en-US';r.interimResults=false;r.continuous=false;const btn=document.getElementById('voice-assistant');r.onstart=()=>btn?.classList.add('active');r.onend=()=>btn?.classList.remove('active');r.onresult=e=>{const t=e.results?.[0]?.[0]?.transcript||'';if(t)overlay(t,parse(t))};r.start()}
function hook(){const b=document.getElementById('voice-assistant');if(!b||b.dataset.voiceCommand)return;b.dataset.voiceCommand='1';b.onclick=start}
new MutationObserver(hook).observe(document.getElementById('app-topbar'),{childList:true,subtree:true});setTimeout(hook,350);window.nodaraVoiceCommand=start;