import { supabase } from './supabase-client.js';
const words={one:1,two:2,three:3,four:4,five:5,six:6,seven:7,eight:8,nine:9,ten:10};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=s=>{s=String(s||'').trim().toLowerCase();return Number(words[s]??s)};
function parse(t){const x=String(t||'').trim(),p={action:/create\s+(a\s+)?(warehouse\s+receipt|wr)/i.test(x)?'create_wr':'fill_wr'};let m;
 if((m=x.match(/(?:customer|account)(?:\s+is|\s+for)?\s+(.+?)(?=\s+(?:shipper|consignee|carrier|reference|po|bol|received|we received|location|put|weight|dimensions|$))/i)))p.customer=m[1].trim();
 else if((m=x.match(/create\s+(?:a\s+)?(?:warehouse\s+receipt|wr)\s+for\s+(.+?)(?=\s+(?:shipper|consignee|carrier|reference|po|bol|received|we received|location|put|weight|dimensions|$))/i)))p.customer=m[1].trim();
 for(const r of ['shipper','consignee','carrier']){m=x.match(new RegExp(`${r}(?:\\s+is)?\\s+(.+?)(?=\\s+(?:customer|account|shipper|consignee|carrier|reference|po|bol|received|we received|location|put|weight|dimensions|$))`,'i'));if(m)p[r]=m[1].trim()}
 if((m=x.match(/\b(PO|BOL|PRO|TRACKING|SO|ASN|ENTRY|BOOKING)\s*(?:number\s*)?(?:is\s*)?([A-Z0-9._\/-]+)/i))){p.reference_type=m[1].toUpperCase();p.reference=m[2]}
 if((m=x.match(/(?:received|we received|cargo is)?\s*([0-9]+|one|two|three|four|five|six|seven|eight|nine|ten)\s+(pallets?|crates?|skids?|boxes?|cartons?|drums?|bags?)/i))){p.quantity=num(m[1]);p.package_type=m[2].replace(/s$/i,'').toUpperCase();if(p.package_type==='BOXE')p.package_type='BOX'}
 if((m=x.match(/([0-9]+(?:\.[0-9]+)?)\s*(kg|kilos?|kilograms?|lb|lbs|pounds?)\b/i))){p.weight=Number(m[1]);p.weight_unit=/kg|kilo/i.test(m[2])?'KG':'LB'}
 if((m=x.match(/([0-9]+(?:\.[0-9]+)?)\s*(?:x|by)\s*([0-9]+(?:\.[0-9]+)?)\s*(?:x|by)\s*([0-9]+(?:\.[0-9]+)?)\s*(inches?|in|cm|centimeters?)?/i))){p.length=Number(m[1]);p.width=Number(m[2]);p.height=Number(m[3]);p.dimension_unit=/cm|cent/i.test(m[4]||'')?'CM':'IN'}
 if((m=x.match(/(?:location|put (?:it|them|cargo)?\s*(?:in|at)?|store (?:it|them|cargo)?\s*(?:in|at)?)\s+([A-Z0-9._\/-]+)/i)))p.location=m[1];
 if((m=x.match(/(?:description|commodity)(?:\s+is)?\s+(.+?)(?=\s+(?:location|reference|po|bol|weight|dimensions|$))/i)))p.description=m[1].trim();
 return p}
function overlay(transcript,p){document.querySelector('.voice-command-overlay')?.remove();const o=document.createElement('div');o.className='voice-command-overlay';const fields=Object.entries(p).filter(([k,v])=>k!=='action'&&v!==undefined&&v!==null&&v!=='');o.innerHTML=`<div class="voice-command-panel"><div class="voice-command-head"><div><div class="eyebrow">NODARA VOICE</div><h2>${p.action==='create_wr'?'Create Warehouse Receipt':'Apply to current WR'}</h2></div><button class="voice-command-close">×</button></div><div class="voice-transcript">“${esc(transcript)}”</div><div class="voice-fields">${fields.map(([k,v])=>`<div class="voice-field"><span>${esc(k.replaceAll('_',' '))}</span><b>${esc(v)}</b></div>`).join('')}</div><div class="voice-command-actions"><button class="secondary" data-voice-cancel>Cancel</button><button class="primary" data-voice-apply>${p.action==='create_wr'?'Build WR':'Apply changes'}</button></div></div>`;document.body.appendChild(o);o.querySelector('.voice-command-close').onclick=()=>o.remove();o.querySelector('[data-voice-cancel]').onclick=()=>o.remove();o.querySelector('[data-voice-apply]').onclick=async()=>{const b=o.querySelector('[data-voice-apply]');b.disabled=true;b.textContent='Applying…';try{await apply(p);o.remove()}catch(e){b.disabled=false;b.textContent='Try again';alert(e.message)}}}
const wait=(sel,ms=5000)=>new Promise((res,rej)=>{const now=document.querySelector(sel);if(now)return res(now);const end=Date.now()+ms;const t=setInterval(()=>{const n=document.querySelector(sel);if(n){clearInterval(t);res(n)}else if(Date.now()>end){clearInterval(t);rej(new Error(`Could not find ${sel}`))}},80)});
async function chooseParty(role,name){if(!name)return;const sel=await wait(`select[data-party="${role}"]`);const opt=[...sel.options].find(o=>o.value&&o.value!=='__new__'&&o.textContent.toLowerCase().includes(name.toLowerCase()));if(opt){sel.value=opt.value;sel.dispatchEvent(new Event('change',{bubbles:true}));await new Promise(r=>setTimeout(r,140));return}const input=sel.parentElement?.querySelector('.party-search-input');if(input){input.value=name;input.dispatchEvent(new Event('input',{bubbles:true}))}}
async function apply(p){if(p.action==='create_wr'||!document.querySelector('.wr-object-head')){window.nodaraReceive?.();await wait('.wr-object-head')}
 for(const [r,n] of [['customer',p.customer],['shipper',p.shipper],['consignee',p.consignee],['carrier',p.carrier]])if(n)await chooseParty(r,n);
 if(p.description){const d=document.getElementById('wr-description');if(d){d.value=p.description;d.dispatchEvent(new Event('input',{bubbles:true}))}}
 if(p.reference){const type=document.querySelector('[data-ref-type="0"]'),val=document.querySelector('[data-ref-value="0"]');if(type)type.value=p.reference_type||'CUSTOMER_REF';if(val){val.value=p.reference;val.dispatchEvent(new Event('input',{bubbles:true}))}}
 const type=await wait('select[id^="cv3-"][id$="-type"]');const id=type.id.match(/^cv3-(.+)-type$/)?.[1];if(id){if(p.package_type){const opt=[...type.options].find(o=>o.value===p.package_type||o.textContent.toUpperCase().startsWith(p.package_type));if(opt)type.value=opt.value}if(p.quantity){const q=document.getElementById(`cv3-${id}-qty`);if(q)q.value=p.quantity}if(p.weight!=null){const wu=document.getElementById('cv3-weight-unit');if(wu&&p.weight_unit)wu.value=p.weight_unit;const w=document.getElementById(`cv3-${id}-weight`);if(w)w.value=p.weight}if(p.length!=null){const du=document.getElementById('cv3-dim-unit');if(du&&p.dimension_unit)du.value=p.dimension_unit;for(const [k,v] of [['l',p.length],['w',p.width],['h',p.height]]){const e=document.getElementById(`cv3-${id}-${k}`);if(e)e.value=v}}type.dispatchEvent(new Event('change',{bubbles:true}));await new Promise(r=>setTimeout(r,100));if(p.location){const loc=document.getElementById(`cv3-${id}-location`);if(loc){const{data}=await supabase.from('warehouse_locations').select('id,code').or(`code.ilike.${p.location},name.ilike.%${p.location}%`).eq('active',true).limit(1);if(data?.[0]){loc.value=data[0].code;loc.dataset.locationId=data[0].id;loc.dispatchEvent(new Event('change',{bubbles:true}))}else{loc.value=p.location;loc.dispatchEvent(new Event('input',{bubbles:true}))}}}}
 window.dispatchEvent(new Event('nodara:voice-applied'))}
function start(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return alert('Voice commands are not supported by this browser.');const r=new SR();r.lang='en-US';r.interimResults=false;r.continuous=false;const btn=document.getElementById('voice-assistant');r.onstart=()=>btn?.classList.add('active');r.onend=()=>btn?.classList.remove('active');r.onresult=e=>{const t=e.results?.[0]?.[0]?.transcript||'';if(t)overlay(t,parse(t))};r.start()}
function hook(){const b=document.getElementById('voice-assistant');if(!b||b.dataset.voiceCommand)return;b.dataset.voiceCommand='1';b.onclick=start}
new MutationObserver(hook).observe(document.getElementById('app-topbar'),{childList:true,subtree:true});setTimeout(hook,350);window.nodaraVoiceCommand=start;
