import { supabase } from './supabase-client.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const TYPES=['RECEIVING','HANDLING','STORAGE','PALLET','LABEL','FORKLIFT','DOCUMENTATION','DELIVERY','OTHER'];
async function orgId(){const{data,error}=await supabase.rpc('bootstrap_workspace',{p_name:'NODARA Workspace'});if(error)throw error;return data}
async function list(jobId){const{data,error}=await supabase.from('charges').select('*').eq('job_id',jobId).order('created_at');if(error)throw error;return data||[]}
export async function openWRCharges({wr,onBack}){
 const main=document.getElementById('main');let charges=await list(wr.job_id);
 const total=()=>charges.reduce((a,c)=>a+Number(c.amount||0),0);
 function render(){main.innerHTML=`<div class="record-commandbar"><button class="secondary compact-btn" id="charge-back">‹ Receipt</button><button class="primary compact-btn" id="charge-add">＋ Add charge</button></div><div class="eyebrow">Warehouse Receipt · Charges</div><h1 class="title">${esc(wr.receipt_number)}</h1><div class="record-tabs"><button>Overview</button><button>Cargo</button><button>Documents</button><button>Activity</button><button class="active">Charges <span>${charges.length}</span></button></div><section class="record-section"><div class="section-heading"><div><h3>Charges</h3><span class="muted">Billable services tied to this receipt/job.</span></div><div class="charge-total"><span>Total</span><b>$${total().toFixed(2)}</b></div></div><div id="charge-editor"></div><div class="charge-table">${charges.length?charges.map(row).join(''):'<div class="empty compact">No charges yet.</div>'}</div></section>`;document.getElementById('charge-back').onclick=onBack;document.getElementById('charge-add').onclick=()=>editor();document.querySelectorAll('[data-edit-charge]').forEach(b=>b.onclick=()=>editor(charges.find(c=>c.id===b.dataset.editCharge)));document.querySelectorAll('[data-delete-charge]').forEach(b=>b.onclick=async()=>{const c=charges.find(x=>x.id===b.dataset.deleteCharge);if(c&&confirm(`Delete ${c.description||c.charge_type} charge?`)){const{error}=await supabase.from('charges').delete().eq('id',c.id);if(error)return alert(error.message);charges=await list(wr.job_id);render()}})}
 function row(c){return `<div class="charge-row"><button data-edit-charge="${c.id}"><span><b>${esc(c.description||c.charge_type)}</b><small>${esc(c.charge_type)} · ${Number(c.quantity||0)} × $${Number(c.unit_rate||0).toFixed(2)}</small></span><strong>$${Number(c.amount||0).toFixed(2)}</strong><span class="status-pill">${esc(c.status||'draft')}</span></button><button class="subtle danger-text" data-delete-charge="${c.id}">×</button></div>`}
 function editor(c=null){document.getElementById('charge-editor').innerHTML=`<div class="inline-editor"><div class="field"><label>Charge</label><select id="ce-type">${TYPES.map(t=>`<option ${t===c?.charge_type?'selected':''}>${t}</option>`).join('')}</select></div><div class="field"><label>Description</label><input id="ce-desc" value="${esc(c?.description||'')}" placeholder="Receiving, pallet handling…"></div><div class="field"><label>Qty</label><input id="ce-qty" type="number" min="0" step="any" value="${c?.quantity??1}"></div><div class="field"><label>Rate</label><input id="ce-rate" type="number" min="0" step="0.01" value="${c?.unit_rate??0}"></div><div class="field"><label>Status</label><select id="ce-status"><option ${c?.status==='draft'?'selected':''}>draft</option><option ${c?.status==='approved'?'selected':''}>approved</option><option ${c?.status==='invoiced'?'selected':''}>invoiced</option></select></div><div class="inline-editor-actions"><button class="secondary" id="ce-cancel">Cancel</button><button class="primary" id="ce-save">${c?'Save':'Add charge'}</button></div></div>`;document.getElementById('ce-cancel').onclick=()=>{document.getElementById('charge-editor').innerHTML=''};document.getElementById('ce-save').onclick=async()=>{const q=Number(document.getElementById('ce-qty').value),rate=Number(document.getElementById('ce-rate').value);if(q<0||rate<0)return alert('Quantity and rate cannot be negative.');const payload={organization_id:await orgId(),job_id:wr.job_id,charge_type:document.getElementById('ce-type').value,description:document.getElementById('ce-desc').value.trim()||null,side:'sell',quantity:q,unit_rate:rate,amount:q*rate,currency:'USD',status:document.getElementById('ce-status').value};const req=c?supabase.from('charges').update(payload).eq('id',c.id):supabase.from('charges').insert(payload);const{error}=await req;if(error)return alert(error.message);charges=await list(wr.job_id);render()}}
 render();
}
