import { supabase } from './supabase-client.js';
export async function listEntities(){const{data,error}=await supabase.from('entities').select('id,name,code,roles,email,phone,sop').order('name').limit(300);if(error)throw error;return data||[]}
export async function createEntityQuick(input={}){const{data:org,error:o}=await supabase.rpc('bootstrap_workspace',{p_name:'NODARA Workspace'});if(o)throw o;const payload={organization_id:org,name:String(input.name||'').trim(),code:input.code||null,roles:input.roles?.length?input.roles:['customer'],email:input.email||null,phone:input.phone||null,sop:input.sop||{}};if(!payload.name)throw new Error('Entity name is required');const{data,error}=await supabase.from('entities').insert(payload).select('id,name,code,roles,email,phone,sop').single();if(error)throw error;return data}
export async function listInventoryItems(){const{data,error}=await supabase.from('inventory_items').select('id,sku,part_number,description,base_uom,serial_tracking,lot_tracking,metadata').order('updated_at',{ascending:false}).limit(200);if(error)throw error;return data||[]}
export async function listEntityItems(entityId){const{data,error}=await supabase.from('entity_item_profiles').select('inventory_item_id,customer_part_number,customer_sku,description_override,base_uom_override,lot_tracking_override,serial_tracking_override,inventory_items(id,sku,part_number,description,base_uom,serial_tracking,lot_tracking)').eq('entity_id',entityId);if(error)throw error;return data||[]}
export async function findExistingReceiptReference(value){const q=String(value||'').trim();if(!q)return[];const{data,error}=await supabase.from('shipment_references').select('warehouse_receipt_id,reference_type,reference_value,warehouse_receipts(receipt_number)').ilike('reference_value',q).limit(10);if(error)throw error;return data||[]}
const clone=x=>JSON.parse(JSON.stringify(x));
function expandNode(node){const qty=Math.max(1,Number(node?.quantity||1)),base={...clone(node),quantity:1};delete base.id;const children=Array.isArray(node?.children)?node.children:[];base.children=children.flatMap(expandNode);return Array.from({length:qty},()=>clone(base))}
function liveCargoTree(fallback=[]){const roots=window.__nodaraCargoDraftDetails?.roots;if(!Array.isArray(roots)||!roots.length)return fallback||[];return roots.flatMap(expandNode)}
export async function createWarehouseReceiptObjectV2(input={}){const tree=liveCargoTree(input.tree||[]);const{data,error}=await supabase.rpc('create_warehouse_receipt_object_v3',{p_customer_id:input.customer_id||null,p_description:input.description||null,p_references:input.references||[],p_parties:input.parties||{},p_flags:input.flags||[],p_tree:tree});if(error)throw error;return data}
