import { supabase } from './supabase-client.js';
export async function listEntities(){const{data,error}=await supabase.from('entities').select('id,name,code,roles,email,phone,sop').order('name').limit(300);if(error)throw error;return data||[]}
export async function createEntityQuick(input={}){const{data:org,error:o}=await supabase.rpc('bootstrap_workspace',{p_name:'NODARA Workspace'});if(o)throw o;const payload={organization_id:org,name:String(input.name||'').trim(),code:input.code||null,roles:input.roles?.length?input.roles:['customer'],email:input.email||null,phone:input.phone||null,sop:input.sop||{}};if(!payload.name)throw new Error('Entity name is required');const{data,error}=await supabase.from('entities').insert(payload).select('id,name,code,roles,email,phone,sop').single();if(error)throw error;return data}
export async function listInventoryItems(){const{data,error}=await supabase.from('inventory_items').select('id,sku,part_number,description,base_uom,serial_tracking,lot_tracking,metadata').order('updated_at',{ascending:false}).limit(500);if(error)throw error;return(data||[]).map(x=>({...x,barcode:x.metadata?.barcode||'',model:x.metadata?.model||'',unit_value:x.metadata?.unit_value??'',weight_lb:x.metadata?.weight_lb??'',length_in:x.metadata?.length_in??'',width_in:x.metadata?.width_in??'',height_in:x.metadata?.height_in??''}))}
export async function listEntityItems(entityId){const{data,error}=await supabase.from('entity_item_profiles').select('inventory_item_id,customer_part_number,customer_sku,description_override,base_uom_override,lot_tracking_override,serial_tracking_override,inventory_items(id,sku,part_number,description,base_uom,serial_tracking,lot_tracking,metadata)').eq('entity_id',entityId);if(error)throw error;return data||[]}
export async function createInventoryItemQuick(input={}){const{data:org,error:o}=await supabase.rpc('bootstrap_workspace',{p_name:'NODARA Workspace'});if(o)throw o;const part=String(input.part_number||'').trim(),sku=String(input.sku||'').trim(),barcode=String(input.barcode||'').trim(),description=String(input.description||'').trim();if(!part&&!sku&&!barcode&&!description)throw new Error('Enter a part number, SKU, barcode, or description.');const metadata={...(input.metadata||{}),barcode:barcode||null,model:String(input.model||'').trim()||null,unit_value:input.unit_value===''||input.unit_value==null?null:Number(input.unit_value),weight_lb:input.weight_lb===''||input.weight_lb==null?null:Number(input.weight_lb),length_in:input.length_in===''||input.length_in==null?null:Number(input.length_in),width_in:input.width_in===''||input.width_in==null?null:Number(input.width_in),height_in:input.height_in===''||input.height_in==null?null:Number(input.height_in)};const payload={organization_id:org,part_number:part||null,sku:sku||null,description:description||null,base_uom:input.base_uom||'EA',metadata};const{data,error}=await supabase.from('inventory_items').insert(payload).select('id,sku,part_number,description,base_uom,serial_tracking,lot_tracking,metadata').single();if(error)throw error;if(input.entity_id){const profile={organization_id:org,entity_id:input.entity_id,inventory_item_id:data.id,customer_part_number:part||null,customer_sku:sku||null,description_override:description||null,base_uom_override:input.base_uom||'EA'};const{error:pe}=await supabase.from('entity_item_profiles').insert(profile);if(pe&&!String(pe.message||'').toLowerCase().includes('duplicate'))throw pe}return{...data,barcode:metadata.barcode||'',model:metadata.model||'',unit_value:metadata.unit_value??'',weight_lb:metadata.weight_lb??'',length_in:metadata.length_in??'',width_in:metadata.width_in??'',height_in:metadata.height_in??'',entity_id:input.entity_id||null}}
export async function findExistingReceiptReference(value){const q=String(value||'').trim();if(!q)return[];const{data,error}=await supabase.from('shipment_references').select('warehouse_receipt_id,reference_type,reference_value,warehouse_receipts(receipt_number)').ilike('reference_value',q).limit(10);if(error)throw error;return data||[]}
const clone=x=>JSON.parse(JSON.stringify(x));
function expandNode(node){const qty=Math.max(1,Number(node?.quantity||1)),base={...clone(node),quantity:1};delete base.id;const children=Array.isArray(node?.children)?node.children:[];base.children=children.flatMap(expandNode);return Array.from({length:qty},()=>clone(base))}
function liveCargoTree(fallback=[]){const roots=window.__nodaraCargoDraftDetails?.roots;if(!Array.isArray(roots)||!roots.length)return fallback||[];return roots.flatMap(expandNode)}
function flattenTree(nodes,out=[]){for(const n of nodes||[]){out.push(n);flattenTree(n.children||[],out)}return out}
async function persistCreatedLocations(result,tree){const source=flattenTree(tree).filter(n=>n.warehouse_location_id);if(!source.length)return;let jobId=result?.job_id||result?.jobId||null;if(!jobId){let wrId=result?.warehouse_receipt_id||result?.wr_id||null;if(!wrId&&result?.receipt_number){const{data}=await supabase.from('warehouse_receipts').select('id,job_id').eq('receipt_number',result.receipt_number).maybeSingle();wrId=data?.id;jobId=data?.job_id}if(wrId&&!jobId){const{data}=await supabase.from('warehouse_receipts').select('job_id').eq('id',wrId).maybeSingle();jobId=data?.job_id}}if(!jobId)return;const{data:created,error}=await supabase.from('cargo_units').select('id,parent_id,created_at').eq('job_id',jobId).order('created_at');if(error||!created?.length)return;const flat=flattenTree(tree);for(let i=0;i<Math.min(flat.length,created.length);i++){const loc=flat[i]?.warehouse_location_id;if(!loc)continue;await supabase.from('cargo_units').update({warehouse_location_id:loc}).eq('id',created[i].id)}}
export async function createWarehouseReceiptObjectV2(input={}){const tree=liveCargoTree(input.tree||[]);const{data,error}=await supabase.rpc('create_warehouse_receipt_object_v3',{p_customer_id:input.customer_id||null,p_description:input.description||null,p_references:input.references||[],p_parties:input.parties||{},p_flags:input.flags||[],p_tree:tree});if(error)throw error;try{await persistCreatedLocations(data,tree)}catch(e){console.warn('WR created but location linking failed',e)}return data}
