import './document-intelligence.js?v=20260912-ocr1';
import './document-intelligence-bridge.js?v=20260912-ocr1';
import './wr-mobile-ux-v20.js?v=20260912-ux1';

const main=document.getElementById('main');
let opening=false,bundlePromise=null;
function showLoadError(err){document.body.classList.remove('wr-canonical-loading');main.style.visibility='visible';console.error('NODARA Receiving failed to load',err);main.innerHTML=`<div style="max-width:760px;margin:30px auto;padding:20px"><div class="eyebrow">WAREHOUSE RECEIVING</div><h1 class="title">Receiving could not start</h1><div class="notice warning" style="margin-top:16px">${String(err?.message||err||'Unknown module error').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}</div><button class="primary wide" style="margin-top:16px" onclick="location.reload()">Reload NODARA</button></div>`}
async function loadBundle(){if(!bundlePromise)bundlePromise=Promise.all([import('./wr-canonical-v19.js?v=20260912-ux1'),import('./wr-output-studio-v11.js?v=20260911-v19a').catch(e=>{console.warn('WR output studio unavailable',e);return null}),import('./wr-media-components-v9.js?v=20260911-v19a').catch(e=>{console.warn('WR media component unavailable',e);return null}),import('./wr-document-scanner-v10.js?v=20260912-ux1').catch(e=>{console.warn('WR scanner unavailable',e);return null}),import('./wr-signature-v10.js?v=20260912-ux1').catch(e=>{console.warn('WR signature unavailable',e);return null})]).then(([canonical])=>({canonical}));return bundlePromise}
function begin(){document.body.classList.add('wr-canonical-loading');main.style.visibility='hidden'}
async function openEditor(){if(opening)return;opening=true;begin();try{window.nodaraSetActive?.('wr');const{canonical}=await loadBundle();if(typeof canonical?.openNewReceivingV19!=='function')throw new Error('Canonical New Receiving is missing.');await canonical.openNewReceivingV19();document.body.classList.remove('wr-canonical-loading');main.style.visibility='visible'}catch(e){showLoadError(e)}finally{opening=false}}
async function openExisting(id,view='guided'){if(opening)return;opening=true;begin();try{window.nodaraSetActive?.('wr');const{canonical}=await loadBundle();if(typeof canonical?.mountWarehouseReceiptV19!=='function')throw new Error('Canonical WR workspace is missing.');await canonical.mountWarehouseReceiptV19(id,{view})}catch(e){showLoadError(e)}finally{opening=false}}
window.nodaraReceive=openEditor;window.nodaraNewReceipt=openEditor;window.nodaraOpenNewWR=openEditor;window.nodaraOpenCanonicalWR=openExisting;
document.addEventListener('click',e=>{const b=e.target.closest?.('[data-go="receive"],[data-new-wr],[data-action="new-wr"]');if(!b)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();openEditor()},true);
