import { supabase } from './supabase-client.js';
const main=document.getElementById('main');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
let applying=false,lastWR='',counts={docs:0,charges:0};
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:0};
function val(row,key){return row.querySelector(`[data-cf="${key}"]`)?.value?.trim()||''}
function qty(row){return num(val(row,'quantity')||1)}
function depth(row){const m=(row.querySelector('.cargo-depth-mark')?.textContent||'').match(/L(\d+)/i);return m?Math.max(0,Number(m[1])-1):0}
function isItem(row){return !!(val(row,'sku')||val(row,'part_number'))||/ITEM|SKU/i.test(val(row,'package_type'))}
function dims(row){const l=val(row,'length_in'),w=val(row,'width_in'),h=val(row,'height_in');return l&&w&&h?`${l} × ${w} × ${h} in`:''}
function summaryText(row){const type=val(row,'package_type')||'Cargo';const q=val(row,'quantity')||'1',u=val(row,'uom')||'';const sku=val(row,'sku')||val(row,'part_number');const w=val(row,'weight_lb');return [sku?`${sku}`:`${q} ${u||type}`,w?`${w} lb`:'',dims(row)].filter(Boolean).join(' · ')}
function decorateCargo(){const tree=main.querySelector('.edit-cargo-tree');if(!tree)return;tree.classList.add('visual-cargo-tree');const rows=[...tree.querySelectorAll('.edit-cargo-row')];rows.forEach((row,i)=>{const d=depth(row);row.style.setProperty('--tree-depth',d);row.classList.toggle('cargo-item-node',isItem(row));row.classList.toggle('cargo-package-node',!isItem(row));if(!row.querySelector('.cargo-review-head')){const head=document.createElement('button');head.type='button';head.className='cargo-review-head';head.innerHTML=`<span class="cargo-node-index">${isItem(row)?'SKU':`L${d+1}`}</span><span class="cargo-review-main"><b></b><small></small></span><span class="cargo-review-chevron">⌄</span>`;row.prepend(head);head.onclick=()=>{row.classList.toggle('expanded');head.querySelector('.cargo-review-chevron').textContent=row.classList.contains('expanded')?'⌃':'⌄'};if(i===0)row.classList.add('expanded')}
 updateCargoHead(row)});}
function updateCargoHead(row){const head=row.querySelector('.cargo-review-head');if(!head)return;const type=val(row,'package_type')||'Cargo';const desc=val(row,'description');const sku=val(row,'sku')||val(row,'part_number');head.querySelector('.cargo-node-index').textContent=isItem(row)?'SKU':`L${depth(row)+1}`;head.querySelector('.cargo-review-main b').textContent=sku||desc||type;head.querySelector('.cargo-review-main small').textContent=summaryText(row);row.classList.toggle('cargo-item-node',isItem(row));row.classList.toggle('cargo-package-node',!isItem(row))}
function liveMetrics(){const rows=[...main.querySelectorAll('.edit-cargo-row')],roots=rows.filter(r=>depth(r)===0),itemRows=rows.filter(isItem);let pieces=0,gross=0,cbm=0,units=0;for(const r of roots){const q=qty(r);pieces+=q;gross+=num(val(r,'weight_lb'))*q;const l=num(val(r,'length_in')),w=num(val(r,'width_in')),h=num(val(r,'height_in'));if(l&&w&&h)cbm+=(l*w*h*0.000016387064)*q}for(const r of itemRows)units+=qty(r);const kg=gross*0.45359237,ft3=cbm*35.3146667;return{pieces,gross,kg,cbm,ft3,units,lines:roots.length}}
function selectedParty(label){const field=[...main.querySelectorAll('.field')].find(x=>x.querySelector('label')?.textContent?.trim()===label);const sel=field?.querySelector('select');return sel?.selectedOptions?.[0]?.textContent?.trim()||'—'}
function activeFlags(){return [...main.querySelectorAll('[data-edit-flag].selected')].map(x=>x.textContent.trim())}
function summaryHTML(){const m=liveMetrics(),flags=activeFlags();return `<aside class="wr-edit-summary"><div class="summary-kicker">WR SUMMARY</div><h3>${esc(lastWR||'Warehouse Receipt')}</h3><div class="summary-parties"><div><span>Customer</span><b>${esc(selectedParty('Customer / Account'))}</b></div><div><span>Shipper</span><b>${esc(selectedParty('Shipper'))}</b></div><div><span>Consignee</span><b>${esc(selectedParty('Consignee'))}</b></div><div><span>Carrier</span><b>${esc(selectedParty('Carrier'))}</b></div></div><div class="summary-flags"><span>Flags</span><b>${flags.length?esc(flags.join(' · ')):'—'}</b></div><div class="summary-counts"><div><span>Documents</span><b>${counts.docs}</b></div><div><span>Charges</span><b>${counts.charges}</b></div></div><div class="summary-cargo-title">CARGO TOTALS</div><div class="summary-metric"><span>Received pieces</span><b>${m.pieces||'—'}</b></div><div class="summary-metric"><span>Cargo lines</span><b>${m.lines}</b></div><div class="summary-metric"><span>Tracked units</span><b>${m.units||0}</b></div><div class="summary-metric"><span>Gross weight</span><b>${m.gross?`${m.gross.toFixed(2)} lb · ${m.kg.toFixed(2)} kg`:'—'}</b></div><div class="summary-metric"><span>Volume</span><b>${m.cbm?`${m.cbm.toFixed(3)} CBM · ${m.ft3.toFixed(2)} ft³`:'—'}</b></div></aside>`}
function mountSummary(){let layout=main.querySelector('.wr-edit-layout');const workspace=main.querySelector('#edit-workspace');if(!workspace)return;if(!layout){layout=document.createElement('div');layout.className='wr-edit-layout';workspace.parentNode.insertBefore(layout,workspace);layout.appendChild(workspace);const aside=document.createElement('div');aside.id='wr-edit-summary-slot';layout.appendChild(aside)}const slot=main.querySelector('#wr-edit-summary-slot');if(slot)slot.innerHTML=summaryHTML()}
async function loadCounts(){const title=main.querySelector('.title')?.textContent?.trim()||'';if(!title||title===lastWR)return;lastWR=title;try{const{data:wr}=await supabase.from('warehouse_receipts').select('id').eq('receipt_number',title).maybeSingle();if(!wr)return;const[a,c]=await Promise.all([supabase.from('warehouse_receipt_attachments').select('id',{count:'exact',head:true}).eq('warehouse_receipt_id',wr.id),supabase.from('charges').select('id',{count:'exact',head:true}).eq('warehouse_receipt_id',wr.id)]);counts={docs:a.count||0,charges:c.count||0};mountSummary()}catch{counts={docs:0,charges:0}}}
function apply(){if(applying)return;if(!main.querySelector('.edit-record-tabs')||!main.textContent.includes('Warehouse Receipt'))return;applying=true;try{lastWR=main.querySelector('.title')?.textContent?.trim()||lastWR;decorateCargo();mountSummary();loadCounts()}finally{applying=false}}
main.addEventListener('input',e=>{if(!e.target.closest?.('[data-cargo-id],.record-section'))return;const row=e.target.closest?.('[data-cargo-id]');if(row)updateCargoHead(row);mountSummary()});main.addEventListener('change',()=>{decorateCargo();mountSummary()});main.addEventListener('click',e=>{if(e.target.closest?.('[data-edit-tab],[data-edit-flag]'))setTimeout(apply,0)});
let queued=false;new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;apply()})}).observe(main,{childList:true,subtree:true});setTimeout(apply,200);
