alter table public.transaction_notes add column if not exists registry_transaction_id uuid references public.transactions(id) on delete cascade;
alter table public.transaction_notes add column if not exists note_type text not null default 'GENERAL';
alter table public.transaction_notes add column if not exists source_type text not null default 'USER';
alter table public.transaction_notes add column if not exists provenance jsonb not null default '{}'::jsonb;
alter table public.transaction_notes add column if not exists metadata jsonb not null default '{}'::jsonb;
alter table public.transaction_notes add column if not exists deleted_at timestamptz;

create table if not exists public.transaction_milestones(
 id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
 transaction_id uuid not null references public.transactions(id) on delete cascade, milestone_code text not null,label text,time_basis text not null,
 milestone_at timestamptz,milestone_date date,timezone text,location_text text,status text not null default 'ACTIVE',sequence_no integer not null default 0,
 version_no integer not null default 1,is_current boolean not null default true,supersedes_id uuid references public.transaction_milestones(id),source_type text not null default 'USER',
 provenance jsonb not null default '{}'::jsonb,metadata jsonb not null default '{}'::jsonb,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 check(milestone_at is not null or milestone_date is not null));
create unique index if not exists transaction_milestones_current_uq on public.transaction_milestones(transaction_id,milestone_code,time_basis) where is_current;
create index if not exists transaction_milestones_tx_idx on public.transaction_milestones(transaction_id,is_current);

create table if not exists public.extension_field_definitions(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,code text not null,label text not null,description text,
 target_kind text not null,applies_to text[] not null default '{}',value_type text not null,options jsonb not null default '[]'::jsonb,validation jsonb not null default '{}'::jsonb,
 default_value jsonb,required boolean not null default false,active boolean not null default true,sort_order integer not null default 0,metadata jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,target_kind,code));
create table if not exists public.extension_field_values(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,field_definition_id uuid not null references public.extension_field_definitions(id) on delete cascade,
 target_kind text not null,target_id uuid not null,transaction_id uuid references public.transactions(id) on delete cascade,value jsonb,source_type text not null default 'USER',provenance jsonb not null default '{}'::jsonb,
 metadata jsonb not null default '{}'::jsonb,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(field_definition_id,target_kind,target_id));
create index if not exists extension_field_values_tx_idx on public.extension_field_values(transaction_id);

alter table public.transaction_milestones enable row level security;
alter table public.extension_field_definitions enable row level security;
alter table public.extension_field_values enable row level security;
do $$ begin create policy transaction_milestones_org on public.transaction_milestones for all to authenticated using(public.nodara_is_org_member(organization_id)) with check(public.nodara_is_org_member(organization_id)); exception when duplicate_object then null; end $$;
do $$ begin create policy extension_field_definitions_org on public.extension_field_definitions for all to authenticated using(public.nodara_is_org_member(organization_id)) with check(public.nodara_is_org_member(organization_id)); exception when duplicate_object then null; end $$;
do $$ begin create policy extension_field_values_org on public.extension_field_values for all to authenticated using(public.nodara_is_org_member(organization_id)) with check(public.nodara_is_org_member(organization_id)); exception when duplicate_object then null; end $$;

create or replace function public.nodara_set_transaction_milestone(p_transaction_id uuid,p_milestone_code text,p_time_basis text,p_milestone_at timestamptz default null,p_milestone_date date default null,p_label text default null,p_timezone text default null,p_location_text text default null,p_provenance jsonb default '{}'::jsonb,p_metadata jsonb default '{}'::jsonb)
returns uuid language plpgsql security definer set search_path='public' as $$ declare tx public.transactions%rowtype; old public.transaction_milestones%rowtype; mid uuid; basis text:=upper(coalesce(p_time_basis,'SCHEDULED')); code text:=upper(p_milestone_code); begin select * into tx from public.transactions where id=p_transaction_id; if tx.id is null then raise exception 'Transaction not found'; end if; if auth.uid() is not null and not public.nodara_is_org_member(tx.organization_id) then raise exception 'Workspace access denied'; end if; if p_milestone_at is null and p_milestone_date is null then raise exception 'Milestone date or timestamp is required'; end if; select * into old from public.transaction_milestones where transaction_id=tx.id and milestone_code=code and time_basis=basis and is_current for update; if old.id is not null then update public.transaction_milestones set is_current=false,status='SUPERSEDED',updated_at=now() where id=old.id; end if; insert into public.transaction_milestones(organization_id,transaction_id,milestone_code,label,time_basis,milestone_at,milestone_date,timezone,location_text,status,version_no,is_current,supersedes_id,source_type,provenance,metadata,created_by) values(tx.organization_id,tx.id,code,p_label,basis,p_milestone_at,p_milestone_date,p_timezone,p_location_text,'ACTIVE',coalesce(old.version_no,0)+1,true,old.id,coalesce(p_provenance->>'source_type','USER'),coalesce(p_provenance,'{}'::jsonb),coalesce(p_metadata,'{}'::jsonb),auth.uid()) returning id into mid; perform public.nodara_record_activity(tx.id,'MILESTONE_SET','MILESTONE',coalesce(p_label,code),jsonb_build_object('milestone_id',mid,'milestone_code',code,'time_basis',basis,'milestone_at',p_milestone_at,'milestone_date',p_milestone_date),coalesce(p_provenance,'{}'::jsonb),null); return mid; end $$;

create or replace function public.nodara_add_transaction_note(p_transaction_id uuid,p_body text,p_note_type text default 'GENERAL',p_visibility text default 'INTERNAL',p_pinned boolean default false,p_provenance jsonb default '{}'::jsonb,p_metadata jsonb default '{}'::jsonb)
returns uuid language plpgsql security definer set search_path='public' as $$ declare tx public.transactions%rowtype; nid uuid; legacy_type text; begin select * into tx from public.transactions where id=p_transaction_id; if tx.id is null then raise exception 'Transaction not found'; end if; if auth.uid() is not null and not public.nodara_is_org_member(tx.organization_id) then raise exception 'Workspace access denied'; end if; if nullif(btrim(p_body),'') is null then raise exception 'Note cannot be blank'; end if; legacy_type:=case tx.transaction_type when 'WAREHOUSE_RECEIPT' then 'WR' when 'CARGO_RELEASE' then 'CR' when 'SHIPMENT' then 'SHIPMENT' when 'TRANSPORT_ORDER' then 'TRANSPORT_ORDER' else tx.transaction_type end; insert into public.transaction_notes(organization_id,transaction_type,transaction_id,registry_transaction_id,body,visibility,pinned,note_type,source_type,provenance,metadata,created_by) values(tx.organization_id,legacy_type,tx.domain_record_id,tx.id,btrim(p_body),upper(coalesce(p_visibility,'INTERNAL')),coalesce(p_pinned,false),upper(coalesce(p_note_type,'GENERAL')),coalesce(p_provenance->>'source_type','USER'),coalesce(p_provenance,'{}'::jsonb),coalesce(p_metadata,'{}'::jsonb),auth.uid()) returning id into nid; perform public.nodara_record_activity(tx.id,'NOTE_ADDED','NOTE',left(btrim(p_body),120),jsonb_build_object('note_id',nid,'note_type',upper(coalesce(p_note_type,'GENERAL')),'visibility',upper(coalesce(p_visibility,'INTERNAL'))),coalesce(p_provenance,'{}'::jsonb),null); return nid; end $$;

create or replace function public.nodara_set_extension_value(p_field_definition_id uuid,p_target_kind text,p_target_id uuid,p_value jsonb,p_transaction_id uuid default null,p_provenance jsonb default '{}'::jsonb,p_metadata jsonb default '{}'::jsonb)
returns uuid language plpgsql security definer set search_path='public' as $$ declare d public.extension_field_definitions%rowtype; tx public.transactions%rowtype; vid uuid; tk text:=upper(p_target_kind); begin select * into d from public.extension_field_definitions where id=p_field_definition_id and active; if d.id is null then raise exception 'Extension field not found or inactive'; end if; if auth.uid() is not null and not public.nodara_is_org_member(d.organization_id) then raise exception 'Workspace access denied'; end if; if upper(d.target_kind)<>tk then raise exception 'Extension field target type mismatch'; end if; if p_transaction_id is not null then select * into tx from public.transactions where id=p_transaction_id and organization_id=d.organization_id; if tx.id is null then raise exception 'Transaction not found in workspace'; end if; end if; insert into public.extension_field_values(organization_id,field_definition_id,target_kind,target_id,transaction_id,value,source_type,provenance,metadata,updated_by) values(d.organization_id,d.id,tk,p_target_id,p_transaction_id,p_value,coalesce(p_provenance->>'source_type','USER'),coalesce(p_provenance,'{}'::jsonb),coalesce(p_metadata,'{}'::jsonb),auth.uid()) on conflict(field_definition_id,target_kind,target_id) do update set transaction_id=excluded.transaction_id,value=excluded.value,source_type=excluded.source_type,provenance=excluded.provenance,metadata=public.extension_field_values.metadata||excluded.metadata,updated_by=excluded.updated_by,updated_at=now() returning id into vid; if tx.id is not null then perform public.nodara_record_activity(tx.id,'EXTENSION_FIELD_SET','EXTENSION',d.label,jsonb_build_object('field_id',d.id,'field_code',d.code,'target_kind',tk,'target_id',p_target_id,'value',p_value),coalesce(p_provenance,'{}'::jsonb),null); end if; return vid; end $$;

revoke all on function public.nodara_set_transaction_milestone(uuid,text,text,timestamptz,date,text,text,text,jsonb,jsonb) from public,anon;
revoke all on function public.nodara_add_transaction_note(uuid,text,text,text,boolean,jsonb,jsonb) from public,anon;
revoke all on function public.nodara_set_extension_value(uuid,text,uuid,jsonb,uuid,jsonb,jsonb) from public,anon;
grant execute on function public.nodara_set_transaction_milestone(uuid,text,text,timestamptz,date,text,text,text,jsonb,jsonb) to authenticated;
grant execute on function public.nodara_add_transaction_note(uuid,text,text,text,boolean,jsonb,jsonb) to authenticated;
grant execute on function public.nodara_set_extension_value(uuid,text,uuid,jsonb,uuid,jsonb,jsonb) to authenticated;
