create table if not exists public.unit_catalog (
  code text primary key, category text not null, name text not null, symbol text,
  base_unit_code text, multiplier_to_base numeric, offset_to_base numeric default 0,
  system_defined boolean not null default true, active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(),
  constraint unit_catalog_category_check check (category in ('WEIGHT','DIMENSION','VOLUME','TEMPERATURE','DISTANCE','COUNT','PACKAGE','STORAGE','TIME','TRANSACTION'))
);
insert into public.unit_catalog(code,category,name,symbol,base_unit_code,multiplier_to_base) values
('KG','WEIGHT','Kilogram','kg','KG',1),('LB','WEIGHT','Pound','lb','KG',0.45359237),('CM','DIMENSION','Centimeter','cm','CM',1),('IN','DIMENSION','Inch','in','CM',2.54),('M','DIMENSION','Meter','m','CM',100),('FT','DIMENSION','Foot','ft','CM',30.48),('CBM','VOLUME','Cubic meter','m³','CBM',1),('CUFT','VOLUME','Cubic foot','ft³','CBM',0.028316846592),('C','TEMPERATURE','Celsius','°C','C',1),('F','TEMPERATURE','Fahrenheit','°F','C',0.5555555556),('KM','DISTANCE','Kilometer','km','KM',1),('MI','DISTANCE','Mile','mi','KM',1.609344),('PCS','COUNT','Pieces','pcs',null,null),('EA','COUNT','Each','ea',null,null),('CTN','PACKAGE','Carton','ctn',null,null),('BOX','PACKAGE','Box','box',null,null),('PLT','PACKAGE','Pallet','plt',null,null),('CRT','PACKAGE','Crate','crt',null,null),('SKD','PACKAGE','Skid','skd',null,null),('DRM','PACKAGE','Drum','drm',null,null),('BAG','PACKAGE','Bag','bag',null,null),('LOCATION','STORAGE','Location','location',null,null),('SQFT','STORAGE','Square foot','ft²',null,null),('SQM','STORAGE','Square meter','m²',null,null),('HOUR','TIME','Hour','hr',null,null),('DAY','TIME','Day','day',null,null),('WEEK','TIME','Week','wk',null,null),('MONTH','TIME','Month','mo',null,null),('SHIPMENT','TRANSACTION','Shipment','shipment',null,null),('WR','TRANSACTION','Warehouse Receipt','WR',null,null),('ORDER','TRANSACTION','Order','order',null,null) on conflict(code) do nothing;

create table if not exists public.organization_unit_profiles (
 organization_id uuid not null references public.organizations(id) on delete cascade,
 profile_name text not null default 'Default', system_code text not null default 'IMPERIAL', is_default boolean not null default true,
 weight_unit text not null default 'LB' references public.unit_catalog(code), dimension_unit text not null default 'IN' references public.unit_catalog(code),
 volume_unit text not null default 'CBM' references public.unit_catalog(code), temperature_unit text not null default 'F' references public.unit_catalog(code),
 distance_unit text not null default 'MI' references public.unit_catalog(code), default_quantity_uom text not null default 'PCS' references public.unit_catalog(code),
 currency_code text not null default 'USD', rounding jsonb not null default '{"weight":2,"dimension":2,"volume":3,"currency":2}'::jsonb,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(), primary key(organization_id,profile_name),
 constraint organization_unit_profiles_system_check check(system_code in ('IMPERIAL','METRIC','CUSTOM'))
);
create unique index if not exists one_default_unit_profile_per_org on public.organization_unit_profiles(organization_id) where is_default;
create table if not exists public.organization_unit_options (organization_id uuid not null references public.organizations(id) on delete cascade, unit_code text not null references public.unit_catalog(code), enabled boolean not null default true, display_name text, sort_order integer not null default 100, metadata jsonb not null default '{}'::jsonb, primary key(organization_id,unit_code));
create table if not exists public.transaction_unit_defaults (organization_id uuid not null references public.organizations(id) on delete cascade, transaction_type text not null, weight_unit text references public.unit_catalog(code), dimension_unit text references public.unit_catalog(code), volume_unit text references public.unit_catalog(code), temperature_unit text references public.unit_catalog(code), quantity_uom text references public.unit_catalog(code), metadata jsonb not null default '{}'::jsonb, updated_at timestamptz not null default now(), primary key(organization_id,transaction_type));
create or replace function public.resolve_unit_defaults(p_organization_id uuid,p_transaction_type text default null) returns jsonb language sql stable security definer set search_path=public as $$ select jsonb_build_object('system',coalesce(t.metadata->>'system',p.system_code),'weight_unit',coalesce(t.weight_unit,p.weight_unit),'dimension_unit',coalesce(t.dimension_unit,p.dimension_unit),'volume_unit',coalesce(t.volume_unit,p.volume_unit),'temperature_unit',coalesce(t.temperature_unit,p.temperature_unit),'quantity_uom',coalesce(t.quantity_uom,p.default_quantity_uom),'distance_unit',p.distance_unit,'currency_code',p.currency_code,'rounding',p.rounding) from public.organization_unit_profiles p left join public.transaction_unit_defaults t on t.organization_id=p.organization_id and t.transaction_type=p_transaction_type where p.organization_id=p_organization_id and p.is_default limit 1 $$;

create table if not exists public.document_number_schemes (
 id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
 document_type text not null, name text not null, prefix text not null default '', suffix text not null default '',
 format_template text not null default '{PREFIX}-{DATE}-{SEQ}{SUFFIX}', date_format text not null default 'YYMMDD', sequence_padding integer not null default 4,
 reset_period text not null default 'DAY', starting_number bigint not null default 1, allow_manual_override boolean not null default true,
 is_active boolean not null default true, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 constraint document_number_padding_check check(sequence_padding between 1 and 12), constraint document_number_reset_check check(reset_period in ('NONE','YEAR','MONTH','DAY'))
);
create unique index if not exists one_active_document_number_scheme on public.document_number_schemes(organization_id,document_type) where is_active;
create table if not exists public.document_number_counters (scheme_id uuid not null references public.document_number_schemes(id) on delete cascade, period_key text not null, last_value bigint not null, updated_at timestamptz not null default now(), primary key(scheme_id,period_key));
create or replace function public.next_document_number(p_organization_id uuid,p_document_type text) returns text language plpgsql security definer set search_path=public as $$ declare s public.document_number_schemes%rowtype; k text; n bigint; seq text; d text; out_no text; org_code text; begin if not public.nodara_is_org_member(p_organization_id) then raise exception 'Not authorized for organization'; end if; select * into s from public.document_number_schemes where organization_id=p_organization_id and document_type=upper(p_document_type) and is_active limit 1; if s.id is null then insert into public.document_number_schemes(organization_id,document_type,name,prefix) values(p_organization_id,upper(p_document_type),initcap(replace(p_document_type,'_',' ')),upper(p_document_type)) returning * into s; end if; k:=case s.reset_period when 'YEAR' then to_char(current_date,'YYYY') when 'MONTH' then to_char(current_date,'YYYYMM') when 'DAY' then to_char(current_date,'YYYYMMDD') else 'ALL' end; insert into public.document_number_counters(scheme_id,period_key,last_value) values(s.id,k,s.starting_number) on conflict(scheme_id,period_key) do update set last_value=public.document_number_counters.last_value+1,updated_at=now() returning last_value into n; seq:=lpad(n::text,s.sequence_padding,'0'); d:=case when coalesce(s.date_format,'')='' then '' else to_char(current_date,s.date_format) end; select coalesce(code,'') into org_code from public.organizations where id=p_organization_id; out_no:=s.format_template; out_no:=replace(out_no,'{PREFIX}',coalesce(s.prefix,'')); out_no:=replace(out_no,'{SUFFIX}',coalesce(s.suffix,'')); out_no:=replace(out_no,'{DATE}',d); out_no:=replace(out_no,'{SEQ}',seq); out_no:=replace(out_no,'{TYPE}',upper(p_document_type)); out_no:=replace(out_no,'{ORG}',coalesce(org_code,'')); out_no:=regexp_replace(out_no,'-{2,}','-','g'); return trim(both '-' from out_no); end $$;
insert into public.organization_unit_profiles(organization_id) select id from public.organizations on conflict do nothing;
insert into public.document_number_schemes(organization_id,document_type,name,prefix,sequence_padding,reset_period) select id,x.t,x.n,x.p,4,'DAY' from public.organizations cross join (values ('WAREHOUSE_RECEIPT','Warehouse Receipt','WR'),('CARGO_RELEASE','Cargo Release','CR'),('SHIPMENT_AIR','Air Shipment','AIR'),('SHIPMENT_OCEAN','Ocean Shipment','OCN'),('SHIPMENT_GROUND','Ground Shipment','GRD'),('PICKUP','Pickup Order','PU'),('DELIVERY','Delivery Order','DL'),('TRANSFER','Transfer Order','TR'),('DRAYAGE','Drayage Order','DR')) x(t,n,p) on conflict do nothing;
