create table if not exists public.entity_contacts(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),entity_id uuid not null references public.entities(id) on delete cascade,name text not null,title text,email text,phone text,roles text[] not null default '{}',is_primary boolean not null default false,active boolean not null default true,notification_preferences jsonb not null default '{}'::jsonb,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists entity_contacts_entity_idx on public.entity_contacts(organization_id,entity_id);
create table if not exists public.entity_addresses(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),entity_id uuid not null references public.entities(id) on delete cascade,address_type text not null default 'OFFICE',name text,line1 text not null,line2 text,city text,state_region text,postal_code text,country_code text,is_primary boolean not null default false,active boolean not null default true,facility_codes jsonb not null default '{}'::jsonb,operating_hours jsonb not null default '{}'::jsonb,instructions text,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists entity_addresses_entity_idx on public.entity_addresses(organization_id,entity_id);
create table if not exists public.entity_legal_profiles(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),entity_id uuid not null unique references public.entities(id) on delete cascade,legal_name text,dba_name text,entity_type text,jurisdiction text,tax_identifier text,registration_number text,website text,payment_terms text,credit_status text,compliance jsonb not null default '{}'::jsonb,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.customer_onboarding_cases(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),customer_id uuid not null references public.entities(id),status text not null default 'DRAFT' check(status in ('DRAFT','IN_PROGRESS','WAITING_CUSTOMER','WAITING_INTERNAL','READY_FOR_SIGNATURE','SIGNED','APPROVED','ACTIVE','CANCELLED')),current_stage text,requested_services jsonb not null default '[]'::jsonb,onboarding_data jsonb not null default '{}'::jsonb,source text not null default 'INTERNAL',workflow_run_id uuid references public.workflow_runs_v2(id),started_by uuid references auth.users(id),started_at timestamptz not null default now(),completed_at timestamptz,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists customer_onboarding_customer_idx on public.customer_onboarding_cases(organization_id,customer_id,status);
alter table public.entity_contacts enable row level security;alter table public.entity_addresses enable row level security;alter table public.entity_legal_profiles enable row level security;alter table public.customer_onboarding_cases enable row level security;
do $$ declare t text; begin foreach t in array array['entity_contacts','entity_addresses','entity_legal_profiles','customer_onboarding_cases'] loop execute format('create policy %I_org_access on public.%I for all to authenticated using (nodara_is_org_member(organization_id)) with check (nodara_is_org_member(organization_id))',t,t); execute format('grant select,insert,update,delete on public.%I to authenticated',t); end loop; end $$;
