create table if not exists public.transaction_blueprints_v2(id uuid primary key default gen_random_uuid(),organization_id uuid references public.organizations(id),transaction_type text not null,code text not null,name text not null,version integer not null default 1,status text not null default 'ACTIVE' check(status in ('DRAFT','ACTIVE','ARCHIVED')),context_conditions jsonb not null default '{}'::jsonb,field_schema jsonb not null default '{}'::jsonb,lifecycle jsonb not null default '[]'::jsonb,description text,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index if not exists transaction_blueprints_v2_unique_org on public.transaction_blueprints_v2(coalesce(organization_id,'00000000-0000-0000-0000-000000000000'::uuid),code,version);
create table if not exists public.transaction_blueprint_requirements(id uuid primary key default gen_random_uuid(),blueprint_id uuid not null references public.transaction_blueprints_v2(id) on delete cascade,requirement_code text not null,requirement_type text not null,label text not null,scope text not null default 'TRANSACTION',blocking boolean not null default true,repeat_mode text not null default 'ONCE' check(repeat_mode in ('ONCE','PER_HANDLING_UNIT','PER_PACKAGE','PER_ITEM','PER_SERIAL','PER_EVENT')),conditions jsonb not null default '{}'::jsonb,configuration jsonb not null default '{}'::jsonb,sort_order integer not null default 100,active boolean not null default true,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(blueprint_id,requirement_code));
alter table public.transaction_blueprints_v2 enable row level security;alter table public.transaction_blueprint_requirements enable row level security;
create policy transaction_blueprints_v2_read on public.transaction_blueprints_v2 for select to authenticated using(organization_id is null or nodara_is_org_member(organization_id));
create policy transaction_blueprints_v2_write on public.transaction_blueprints_v2 for all to authenticated using(organization_id is not null and nodara_is_org_member(organization_id)) with check(organization_id is not null and nodara_is_org_member(organization_id));
create policy transaction_blueprint_requirements_read on public.transaction_blueprint_requirements for select to authenticated using(exists(select 1 from public.transaction_blueprints_v2 b where b.id=blueprint_id and (b.organization_id is null or nodara_is_org_member(b.organization_id))));
create policy transaction_blueprint_requirements_write on public.transaction_blueprint_requirements for all to authenticated using(exists(select 1 from public.transaction_blueprints_v2 b where b.id=blueprint_id and b.organization_id is not null and nodara_is_org_member(b.organization_id))) with check(exists(select 1 from public.transaction_blueprints_v2 b where b.id=blueprint_id and b.organization_id is not null and nodara_is_org_member(b.organization_id)));
grant select,insert,update,delete on public.transaction_blueprints_v2 to authenticated;grant select,insert,update,delete on public.transaction_blueprint_requirements to authenticated;
-- Core global blueprints and their baseline requirements were seeded in production in the same foundation pass.
-- See docs/architecture/transaction-blueprints-v2.md for the canonical seed specification.
