-- Applied to production on 2026-09-06. Non-destructive canonical v2 foundation.
-- Full canonical contracts: Service Agreement -> Requirements/Billing/Communications -> compiled transaction requirements -> actionable workflow tasks.

create table if not exists public.service_agreements (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), customer_id uuid not null references public.entities(id), service_id uuid not null references public.service_catalog(id), name text not null, agreement_version integer not null default 1, status text not null default 'DRAFT' check (status in ('DRAFT','ACTIVE','SUSPENDED','EXPIRED','TERMINATED')), effective_from date not null default current_date, effective_to date, source_document_id uuid references public.documents(id), source_template_id uuid, sla jsonb not null default '{}'::jsonb, defaults jsonb not null default '{}'::jsonb, metadata jsonb not null default '{}'::jsonb, created_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (organization_id,customer_id,service_id,agreement_version)
);
create table if not exists public.service_agreement_requirements (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), agreement_id uuid not null references public.service_agreements(id) on delete cascade, requirement_code text not null, requirement_type text not null, label text not null, scope text not null default 'TRANSACTION', blocking boolean not null default true, repeat_mode text not null default 'ONCE' check (repeat_mode in ('ONCE','PER_HANDLING_UNIT','PER_PACKAGE','PER_ITEM','PER_SERIAL','PER_EVENT')), conditions jsonb not null default '{}'::jsonb, configuration jsonb not null default '{}'::jsonb, sort_order integer not null default 100, active boolean not null default true, provenance jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(agreement_id,requirement_code)
);
create table if not exists public.service_agreement_billing_rules (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), agreement_id uuid not null references public.service_agreements(id) on delete cascade, service_id uuid not null references public.service_catalog(id), rule_code text not null, trigger_event text, basis text not null, unit text not null, rate numeric, minimum_charge numeric, maximum_charge numeric, currency text not null default 'USD', included boolean not null default false, conditions jsonb not null default '{}'::jsonb, quantity_formula jsonb not null default '{}'::jsonb, active boolean not null default true, provenance jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(agreement_id,rule_code)
);
create table if not exists public.service_agreement_communication_rules (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), agreement_id uuid not null references public.service_agreements(id) on delete cascade, event_code text not null, channel text not null default 'EMAIL' check(channel in ('EMAIL','SMS','PORTAL','WEBHOOK','INTERNAL')), recipient_role text, recipients jsonb not null default '[]'::jsonb, template_code text, conditions jsonb not null default '{}'::jsonb, automatic boolean not null default false, blocking boolean not null default false, active boolean not null default true, provenance jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.transaction_requirement_instances (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), target_type text not null, target_id uuid not null, agreement_id uuid references public.service_agreements(id), source_requirement_id uuid references public.service_agreement_requirements(id), requirement_code text not null, label text not null, scope text not null default 'TRANSACTION', scope_id uuid, blocking boolean not null default true, status text not null default 'PENDING' check(status in ('PENDING','IN_PROGRESS','SATISFIED','WAIVED','FAILED','NOT_APPLICABLE')), completion_evidence jsonb not null default '[]'::jsonb, provenance jsonb not null default '{}'::jsonb, satisfied_by uuid references auth.users(id), satisfied_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists tri_target_idx on public.transaction_requirement_instances(organization_id,target_type,target_id);
create table if not exists public.workflow_runs_v2 (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), target_type text not null, target_id uuid not null, agreement_id uuid references public.service_agreements(id), operational_context_id uuid references public.operational_contexts(id), workflow_code text not null, workflow_version integer not null default 1, status text not null default 'ACTIVE' check(status in ('ACTIVE','BLOCKED','COMPLETED','CANCELLED')), current_task_code text, compiled_from jsonb not null default '{}'::jsonb, started_by uuid references auth.users(id), started_at timestamptz not null default now(), completed_at timestamptz, updated_at timestamptz not null default now(), unique(organization_id,target_type,target_id,workflow_code,workflow_version)
);
create table if not exists public.workflow_tasks_v2 (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), workflow_run_id uuid not null references public.workflow_runs_v2(id) on delete cascade, requirement_instance_id uuid references public.transaction_requirement_instances(id), task_code text not null, label text not null, sequence_no integer not null, action_type text not null, state text not null default 'PENDING' check(state in ('PENDING','AVAILABLE','IN_PROGRESS','BLOCKED','COMPLETED','SKIPPED','FAILED')), blocking boolean not null default true, input_schema jsonb not null default '{}'::jsonb, completion_rule jsonb not null default '{}'::jsonb, action_config jsonb not null default '{}'::jsonb, provenance jsonb not null default '{}'::jsonb, completed_by uuid references auth.users(id), completed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workflow_run_id,task_code)
);
create table if not exists public.transaction_overrides (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), target_type text not null, target_id uuid not null, object_type text not null, object_id uuid, override_action text not null check(override_action in ('WAIVE','FORCE_REQUIRED','CHANGE_VALUE','MARK_NOT_APPLICABLE','REOPEN')), previous_value jsonb, new_value jsonb, reason text not null, requested_by uuid references auth.users(id), approved_by uuid references auth.users(id), created_at timestamptz not null default now()
);
create index if not exists transaction_overrides_target_idx on public.transaction_overrides(organization_id,target_type,target_id);
create table if not exists public.document_templates_v2 (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), code text not null, name text not null, document_type text not null, scope_type text not null default 'TRANSACTION', version integer not null default 1, status text not null default 'DRAFT' check(status in ('DRAFT','ACTIVE','ARCHIVED')), template_definition jsonb not null default '{}'::jsonb, field_schema jsonb not null default '{}'::jsonb, signature_schema jsonb not null default '{}'::jsonb, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id,code,version)
);
create table if not exists public.signature_requests (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), template_id uuid references public.document_templates_v2(id), document_id uuid references public.documents(id), entity_id uuid references public.entities(id), target_type text, target_id uuid, status text not null default 'DRAFT' check(status in ('DRAFT','SENT','VIEWED','SIGNED','DECLINED','VOID','EXPIRED')), signers jsonb not null default '[]'::jsonb, field_values jsonb not null default '{}'::jsonb, external_provider text, external_request_id text, sent_at timestamptz, completed_at timestamptz, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

alter table public.service_agreements enable row level security; alter table public.service_agreement_requirements enable row level security; alter table public.service_agreement_billing_rules enable row level security; alter table public.service_agreement_communication_rules enable row level security; alter table public.transaction_requirement_instances enable row level security; alter table public.workflow_runs_v2 enable row level security; alter table public.workflow_tasks_v2 enable row level security; alter table public.transaction_overrides enable row level security; alter table public.document_templates_v2 enable row level security; alter table public.signature_requests enable row level security;
do $$ declare t text; begin foreach t in array array['service_agreements','service_agreement_requirements','service_agreement_billing_rules','service_agreement_communication_rules','transaction_requirement_instances','workflow_runs_v2','workflow_tasks_v2','transaction_overrides','document_templates_v2','signature_requests'] loop execute format('create policy %I_org_access on public.%I for all to authenticated using (nodara_is_org_member(organization_id)) with check (nodara_is_org_member(organization_id))',t,t); execute format('grant select,insert,update,delete on public.%I to authenticated',t); end loop; end $$;
